### ISSUE TITLE
[client] upload `OSError: [Errno 18] Invalid cross-device link '/tmp/devpi-…/dist/….whl' -> 'dist/….whl'`

### ISSUE THREAD

**Issue by piernov** [devpi/devpi#1005]
New bug as of devpi-client 7.0.0, not present on 6.0.6.

`devpi upload` command ends in a `OSError: [Errno 18] Invalid cross-device link` error because it tries to copy from `/tmp` which may be a `tmpfs` mount point to the current directory which may be on a fixed storage so different filesystems.
This is due to the fact that `Path.rename()` which is now used at https://github.com/devpi/devpi/blob/2cf7cf1d977647ba15dea24785c488371ca47305/client/devpi/upload.py#L527 after cfb1d2f calls `os.rename()` under the hood and that does not support cross-filesystem move. A solution is to use `shutil.move()` instead.

Python has an open issue about this: https://github.com/python/cpython/issues/73991
But in the meantime and for existing Python versions (3.11.5 for me), simply replacing `x.rename(target)` with `shutil.move(x, target)` seems to solve the issue in my case.

Full output:
```
$ devpi upload
using workdir /tmp/devpi-ratt7vr7
copied repo .git to /tmp/devpi-ratt7vr7/.git
pre-build: cleaning dist
--> /tmp/devpi-ratt7vr7$ /usr/bin/python -m build 
  File "/home/piernov/.local/bin/devpi", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/piernov/devel/devpi/client/devpi/main.py", line 44, in main
    return method(hub, hub.args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/piernov/devel/devpi/client/devpi/upload.py", line 47, in main
    archives.extend(exported.setup_build(
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/piernov/devel/devpi/client/devpi/upload.py", line 527, in setup_build
    x.rename(target)
  File "/usr/lib/python3.11/pathlib.py", line 1175, in rename
    os.rename(self, target)
OSError: [Errno 18] Invalid cross-device link: '/tmp/devpi-ratt7vr7/dist/[redacted].whl' -> 'dist/[redacted].whl'
```

**Comment by eachimei** [comment]
Same issue observed on Windows as well
