### ISSUE TITLE
Cannot load packages when use base auth in gitlab registry mirror

### ISSUE THREAD

**Issue by zhu** [devpi/devpi#1006]
Setup a mirror index to `https://token_name:token@gitlab.example.com/api/v4/groups/<group name or id>/-/packages/pypi/simple`.
Response package link in the page: `https://gitlab.exmple.com/api/v4/groups/<group id>/-/packages/pypi/simple/<package name>`.
Gitlab always return package link without username and password, and use group id in the link.
But
https://github.com/devpi/devpi/blob/2cf7cf1d977647ba15dea24785c488371ca47305/server/devpi_server/mirror.py#L79
required the package link base path the same as the index path,
https://github.com/devpi/devpi/blob/2cf7cf1d977647ba15dea24785c488371ca47305/server/devpi_server/mirror.py#L81
required the package link host the same as basehost which has username and password.

**Comment by fschulze** [comment]
The basehost check on line 81 is clearly a bug. I'm reluctant to change the path check on line 79, as links to other places might interfere here. Can the mirror be set up with a ``https://token_name:token@gitlab.example.com/api/v4/groups/<group id>/-/packages/pypi/simple`` URL, so when the other check is fixed the path check wouldn't fail anymore?

**Comment by fschulze** [comment]
You should be able to replace ``.replace(path='')`` on line 57 and 81 to fix this if the changed mirror URL works.

**Comment by fschulze** [comment]
Can you test this with the just release 6.10.0?

**Comment by zhu** [comment]
> Can you test this with the just release 6.10.0?
6.10.0 works.
