### ISSUE TITLE
Incorrect version given to doczip with devpi-client version 7.0.0

### ISSUE THREAD

**Issue by eachimei** [devpi/devpi#1008]
Given a package that uses `setuptools-scm` using `pyproject.toml` (https://github.com/pypa/setuptools_scm#pyprojecttoml-usage),
when trying to upload docs (e.g. `devpi upload --only-docs --dry-run`), the generated doczip has an incorrect version (0.0.0 which is not the true version):
`built: dist\packagename-0.0.0.doc.zip [sphinx docs] 155kb`

This appears to be due to:
https://github.com/devpi/devpi/blob/2cf7cf1d977647ba15dea24785c488371ca47305/client/devpi/upload.py#L400C44-L400C44

```
    def setup_name_and_version(self):
        try:
            metadata = build.util.project_wheel_metadata(
                str(self.rootpath), isolated=False)
```
When setting `isolated=True`, the issue is resolved and we get the correct version.

I think the root-cause is: `setuptools_scm` itself is not installed in the active virtual-env (it was installed in the isolated build frontend temporary environment when the package was originally built and installed using `build`...). This is a typical use-case in CI, for example when using `tox` to prepare a "release" environment that's going to run the `devpi` commands.

Experiments:
1. Environment as is, without changing anything -- issue is reproduced:
```
>>> import build.util
>>> metadata = build.util.project_wheel_metadata(".", isolated=False)
>>> metadata["version"]
'0.0.0'
```
2. Once changing to `isolated=True`:
```
>>> metadata = build.util.project_wheel_metadata(".", isolated=True)
>>> metadata["version"]
'2.0.12'   # <-- CORRECT version based on git tag...
```
3. Keeping `isolated=False`, but manually installing `setuptools_scm[toml]` beforehand:
```
>>> metadata = build.util.project_wheel_metadata(".", isolated=False)
>>> metadata["version"]
'2.0.12'   # <-- CORRECT version based on git tag...
```

Seems that when `isolated=False` then `build` is not installing the build-system `requires`... ? 
Ah, yes, confirmed: https://github.com/pypa/build/blob/main/src/build/util.py#L47
as can be seen, only when `isolated=True` it's going to install the build-requirements...

**Comment by fschulze** [comment]
Does this happen with both devpi-client 6.x and 7.x?

With the current version, could you try ``isolated=not self.args.no_isolation``. That seems to be the most sensible fix.

As an optimization, we could look into getting the metadata from previously built artifacts like wheels and pass that on to the documentation building step.

**Comment by eachimei** [comment]
> Does this happen with both devpi-client 6.x and 7.x?

No, it started happening only with 7.0.0 due to the switch from `pep517` to `build`. As I will show below, the switch changed important functionality aspects.

As can be seen, the relevant commit included in 7.0.0:
https://github.com/devpi/devpi/commit/8bd048debcd3c5c6af9ed5923c35d446a4dc7192#diff-654fa2126392edd2daaa3b4f621ad8805e93d9ab5096727fd704dcbd222ce54fL394

The "old" code was:
```python
    def setup_name_and_version(self):
        result = pep517.meta.load(self.rootpath.strpath)
```

And if we track down `pep517.meta.load()` we can see the it winds up to:
https://github.com/pypa/pyproject-hooks/blob/v0.13.0/pep517/meta.py#L53
```python
# eachimei: `pep517.meta.load` runs this:
def build(source_dir='.', dest=None, system=None):
    system = system or load_system(source_dir)
    dest = os.path.join(source_dir, dest or 'dist')
    os.makedirs(dest, exist_ok=True)
    validate_system(system)
    hooks = Pep517HookCaller(
        source_dir, system['build-backend'], system.get('backend-path')
    )

    with hooks.subprocess_runner(quiet_subprocess_runner):
        with BuildEnvironment() as env:                # <--- eachimei: isolated environment
            env.pip_install(system['requires'])        # <--- eachimei: install the build system requirements
```

Therefore, it seems that for "apples to apples" switch from `pep517` to `build`, we should run with `isolated=True` (as described in this issue body):
```
    def setup_name_and_version(self):
        try:
            metadata = build.util.project_wheel_metadata(
                str(self.rootpath), isolated=False)    # <--- change to isolated=True, at least as a default
```

**Comment by fschulze** [comment]
Thanks for the detailed explanation. I think ``isolated=not self.args.no_isolation`` is the correct fix then, as it would do isolated builds by default, but with the ``--no-isolation`` option it would build both the releases and the docs with no isolation, so no surprises for either case.

**Comment by eachimei** [comment]
Thanks! I haven't got to give it a try yet, but it makes sense and sounds good!

**Comment by eachimei** [comment]
Tested `isolated=not self.args.no_isolation` and it looks good, works as expected.

**Comment by eachimei** [comment]
PR with the fix: https://github.com/devpi/devpi/pull/1009

**Comment by eachimei** [comment]
Thanks @fschulze ! 😃
