### ISSUE TITLE
HTTP error 502 while retrieving a wheel file

### ISSUE THREAD

**Issue by pchatterjee-cfx** [devpi/devpi#1019]
- [ ] Are you using the latest released version?
No. We are on devpi-server 5.4.1. We are hosting the internal devpi-server since 2020 and this is the first time we saw this error 
- [ ] Provide the output of ``pip list`` from the virtual environment you are using.

> Package              Version
> -------------------- ----------
> aiohttp              3.8.1
> aiosignal            1.2.0
> appdirs              1.4.4
> APScheduler          3.10.4
> argon2-cffi          21.3.0
> argon2-cffi-bindings 21.2.0
> async-timeout        4.0.2
> asyncio-nats-client  0.11.4
> asynctest            0.13.0
> attrs                21.4.0
> backports.zoneinfo   0.2.1
> bcrypt               3.2.0
> beautifulsoup4       4.10.0
> bleach               4.1.0
> boto3                1.14.44
> botocore             1.17.63
> build                0.7.0
> certifi              2021.10.8
> cffi                 1.15.0
> cfxdx-ext-graph-api  22.10.28
> cfxql                21.9.29
> Chameleon            3.9.1
> charset-normalizer   2.0.9
> check-manifest       0.47
> cmarkgfm             0.6.0
> colorama             0.4.4
> commonmark           0.9.1
> cryptography         36.0.1
> defusedxml           0.7.1
> devpi                2.2.0
> devpi-client         5.2.3
> devpi-common         3.6.0
> devpi-server         6.3.1
> devpi-web            4.0.8
> distlib              0.3.4
> docutils             0.15.2
> ed25519              1.5
> elasticsearch        7.0.5
> elasticsearch-dsl    7.0.0
> execnet              1.9.0
> filelock             3.4.2
> frozenlist           1.2.0
> funcy                1.16
> getversion           1.0.2
> greenlet             1.1.2
> grpcio               1.46.3
> grpcio-tools         1.46.3
> hupper               1.10.3
> idna                 3.3
> importlib-metadata   4.10.0
> importlib-resources  5.9.0
> itsdangerous         2.0.1
> jeepney              0.8.0
> jmespath             0.10.0
> jsonschema           4.5.1
> keyring              23.6.0
> lazy                 1.4
> meliae               0.5.1
> minio                4.0.10
> multidict            5.2.0
> nats-py              2.0.0
> nkeys                0.1.0
> numpy                1.21.5
> packaging            21.3
> pandas               1.1.1
> paramiko             2.9.1
> passlib              1.7.4
> PasteDeploy          2.1.1
> pep517               0.12.0
> pika                 1.3.1
> pip                  22.2.2
> pkginfo              1.8.2
> plaster              1.0
> plaster-pastedeploy  0.7
> platformdirs         2.4.1
> pluggy               1.0.0
> protobuf             3.20.1
> psutil               5.8.0
> py                   1.11.0
> pyarrow              8.0.0
> pycallgraph          1.0.1
> pycparser            2.21
> pydantic             1.9.0
> Pygments             2.11.1
> PyNaCl               1.4.0
> pyparsing            2.4.7
> pyramid              2.0
> pyramid-chameleon    0.3
> pyrasite             2.0
> pyrasite-gui         2.0b7
> pyrsistent           0.18.1
> python-dateutil      2.8.1
> pytz                 2021.3
> PyYAML               6.0
> rda-es-lib           21.12.6.1
> rda-extension-list   21.11.18.4
> rda-messaging        22.8.23.1
> readme-renderer      35.0
> repoze.lru           0.7
> requests             2.27.0
> requests-toolbelt    0.9.1
> rfc3986              2.0.0
> rich                 12.4.4
> ruamel.yaml          0.17.20
> ruamel.yaml.clib     0.2.6
> s3transfer           0.3.7
> SecretStorage        3.3.2
> setuptools           40.8.0
> setuptools-scm       6.3.2
> simpleeval           0.9.13
> six                  1.16.0
> soupsieve            2.3.1
> SQLAlchemy           1.4.29
> stdlib-list          0.8.0
> strictyaml           1.6.1
> tabulate             0.8.9
> toml                 0.10.2
> tomli                2.0.0
> tox                  3.24.5
> translationstring    1.4
> twine                4.0.1
> typing_extensions    4.0.1
> tzlocal              5.1
> urllib3              1.25.11
> venusian             3.0.0
> virtualenv           20.13.0
> waitress             2.0.0
> webencodings         0.5.1
> WebOb                1.8.7
> wheel                0.37.1
> Whoosh               2.7.4
> XlsxWriter           3.0.3
> yarl                 1.7.2
> zipp                 3.7.0
> zope.deprecation     4.4.0
> zope.interface       5.4.0

- [ ] Provide the Python and operating system versions under which the issue occurs.
Python 3.7.4

> DISTRIB_ID=LinuxMint
> DISTRIB_RELEASE=20.3
> DISTRIB_CODENAME=una
> DISTRIB_DESCRIPTION="Linux Mint 20.3 Una"

and

> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=18.04
> DISTRIB_CODENAME=bionic
> DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

- [ ] If possible, provide a minimal example to reproduce the issue.

devpi list

> (PYTHON37) $ devpi list -v confluent-kafka
> http://10.95.159.86:3141/root/pypi/+f/406/9e7b56e0baf9d/confluent-kafka-2.3.0.tar.gz
> http://10.95.159.86:3141/root/pypi/+f/cb2/79e369121e07c/confluent_kafka-2.3.0-cp39-cp39-win_amd64.whl
> http://10.95.159.86:3141/root/pypi/+f/210/f2d346d1006e9/confluent_kafka-2.3.0-cp39-cp39-manylinux_2_28_aarch64.whl
> http://10.95.159.86:3141/root/pypi/+f/ca3/6a8d1d49fd55c/confluent_kafka-2.3.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> http://10.95.159.86:3141/root/pypi/+f/6ae/5e6a6dcd5ce85/confluent_kafka-2.3.0-cp39-cp39-macosx_11_0_arm64.whl
> http://10.95.159.86:3141/root/pypi/+f/e5c/740ead14a2510/confluent_kafka-2.3.0-cp39-cp39-macosx_10_9_x86_64.whl
> http://10.95.159.86:3141/root/pypi/+f/cf0/15e547b82a74a/confluent_kafka-2.3.0-cp38-cp38-win_amd64.whl
> http://10.95.159.86:3141/root/pypi/+f/f98/42720ed0debcf/confluent_kafka-2.3.0-cp38-cp38-manylinux_2_28_aarch64.whl
> http://10.95.159.86:3141/root/pypi/+f/f17/5e11facaf1213/confluent_kafka-2.3.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> http://10.95.159.86:3141/root/pypi/+f/4f9/998f781a1da0c/confluent_kafka-2.3.0-cp38-cp38-macosx_11_0_arm64.whl
> http://10.95.159.86:3141/root/pypi/+f/b53/9064fef353869/confluent_kafka-2.3.0-cp38-cp38-macosx_10_9_x86_64.whl
> http://10.95.159.86:3141/root/pypi/+f/047/0dc5e56e63969/confluent_kafka-2.3.0-cp37-cp37m-win_amd64.whl
> http://10.95.159.86:3141/root/pypi/+f/128/ddb28c19ab57c/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_28_aarch64.whl
> http://10.95.159.86:3141/root/pypi/+f/cec/97f8c6564b165/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> http://10.95.159.86:3141/root/pypi/+f/ebf/460d90478bcd1/confluent_kafka-2.3.0-cp37-cp37m-macosx_10_9_x86_64.whl
> http://10.95.159.86:3141/root/pypi/+f/d63/4d4d9914b0a28/confluent_kafka-2.3.0-cp36-cp36m-win_amd64.whl
> http://10.95.159.86:3141/root/pypi/+f/252/92a9a8ef7765c/confluent_kafka-2.3.0-cp36-cp36m-manylinux_2_28_aarch64.whl
> http://10.95.159.86:3141/root/pypi/+f/bc2/4c57a52c20664/confluent_kafka-2.3.0-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> http://10.95.159.86:3141/root/pypi/+f/030/fb237927ec229/confluent_kafka-2.3.0-cp36-cp36m-macosx_10_9_x86_64.whl
> http://10.95.159.86:3141/root/pypi/+f/1cc/f6483d8653562/confluent_kafka-2.3.0-cp312-cp312-win_amd64.whl
> http://10.95.159.86:3141/root/pypi/+f/7fd/1ab257d4fa0e2/confluent_kafka-2.3.0-cp312-cp312-manylinux_2_28_aarch64.whl
> http://10.95.159.86:3141/root/pypi/+f/e08/b601e09a584c6/confluent_kafka-2.3.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> http://10.95.159.86:3141/root/pypi/+f/af6/0af786a7b8cbe/confluent_kafka-2.3.0-cp312-cp312-macosx_11_0_arm64.whl
> http://10.95.159.86:3141/root/pypi/+f/6b4/6ce75bda0c092/confluent_kafka-2.3.0-cp312-cp312-macosx_10_9_x86_64.whl
> http://10.95.159.86:3141/root/pypi/+f/1c6/b29d57df99dab/confluent_kafka-2.3.0-cp311-cp311-win_amd64.whl
> http://10.95.159.86:3141/root/pypi/+f/7f9/f4099aaf2c5da/confluent_kafka-2.3.0-cp311-cp311-manylinux_2_28_aarch64.whl
> http://10.95.159.86:3141/root/pypi/+f/e9b/42bf1b75fdd9a/confluent_kafka-2.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> http://10.95.159.86:3141/root/pypi/+f/ec1/7b26d6155feea/confluent_kafka-2.3.0-cp311-cp311-macosx_11_0_arm64.whl
> http://10.95.159.86:3141/root/pypi/+f/d55/fbdcd75586dd1/confluent_kafka-2.3.0-cp311-cp311-macosx_10_9_x86_64.whl
> http://10.95.159.86:3141/root/pypi/+f/a6a/bece28598fa2b/confluent_kafka-2.3.0-cp310-cp310-win_amd64.whl
> http://10.95.159.86:3141/root/pypi/+f/1eb/a38061e9ed1c0/confluent_kafka-2.3.0-cp310-cp310-manylinux_2_28_aarch64.whl
> http://10.95.159.86:3141/root/pypi/+f/620/46e8a75c7a688/confluent_kafka-2.3.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> http://10.95.159.86:3141/root/pypi/+f/9ab/2217875b731bd/confluent_kafka-2.3.0-cp310-cp310-macosx_11_0_arm64.whl
> http://10.95.159.86:3141/root/pypi/+f/5df/845755cd3ebb9/confluent_kafka-2.3.0-cp310-cp310-macosx_10_9_x86_64.whl

pip install

> (PYTHON37) $ pip install confluent-kafka==2.3.0 -i http://10.95.159.86:3141/macaw/qa-rda-dev/ --trusted-host 10.95.159.86 --no-cache-dir
> WARNING: Skipping confluent-kafka as it is not installed.
> Looking in indexes: http://10.95.159.86:3141/macaw/qa-rda-dev/
> Collecting confluent-kafka==2.3.0
>   ERROR: HTTP error 502 while getting http://10.95.159.86:3141/root/pypi/%2Bf/cec/97f8c6564b165/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=cec97f8c6564b16504d30fe42c22fd4a86c406dbcd45c337b93c21e876e20628 (from http://10.95.159.86:3141/macaw/qa-rda-dev/+simple/confluent-kafka/)
> ERROR: Could not install requirement confluent-kafka==2.3.0 from http://10.95.159.86:3141/root/pypi/%2Bf/cec/97f8c6564b165/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=cec97f8c6564b16504d30fe42c22fd4a86c406dbcd45c337b93c21e876e20628 because of HTTP error 502 Server Error: Bad Gateway for url: http://10.95.159.86:3141/root/pypi/%2Bf/cec/97f8c6564b165/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl for URL http://10.95.159.86:3141/root/pypi/%2Bf/cec/97f8c6564b165/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=cec97f8c6564b16504d30fe42c22fd4a86c406dbcd45c337b93c21e876e20628 (from http://10.95.159.86:3141/macaw/qa-rda-dev/+simple/confluent-kafka/)

devpi-server logs

> 2023-12-13 08:47:58,745 INFO  [req193083] GET /macaw/qa-rda-dev/confluent-kafka/
> 2023-12-13 08:47:59,154 INFO  [req193084] GET /macaw/qa-rda-dev/+simple/confluent-kafka/
> 2023-12-13 08:48:00,756 INFO  [req193085] GET /root/pypi/+f/cec/97f8c6564b165/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> 2023-12-13 08:48:00,808 WARNI Certificate did not match expected hostname: files.pythonhosted.org. Certificate: {'subject': ((('commonName', 'r.shared-319-default.ssl.fastly.net'),),), 'issuer': ((('countryName', 'BE'),), (('organizationName', 'GlobalSign nv-sa'),), (('commonName', 'GlobalSign Atlas R3 DV TLS CA 2023 Q1'),)), 'version': 3, 'serialNumber': '01D06257899F0DD2481ECE65A0533F7E', 'notBefore': 'Apr 10 04:55:11 2023 GMT', 'notAfter': 'May 11 04:55:10 2024 GMT', 'subjectAltName': (('DNS', 'r.shared-319-default.ssl.fastly.net'),), 'OCSP': ('http://ocsp.globalsign.com/ca/gsatlasr3dvtlsca2023q1',), 'caIssuers': ('http://secure.globalsign.com/cacert/gsatlasr3dvtlsca2023q1.crt',), 'crlDistributionPoints': ('http://crl.globalsign.com/ca/gsatlasr3dvtlsca2023q1.crl',)}
> 2023-12-13 08:48:00,809 WARNI [req193085] [Wtx434618] OS error during httpget of https://files.pythonhosted.org/packages/44/2b/c84376dcdfea3cb2e5c4223d3683751e3ed142481103447cc2d4169c2520/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl at /usr/lib/python3.7/site-packages/devpi_server/views.py:1338::iter_cache_remote_file
> 2023-12-13 08:48:00,811 ERROR [req193085] [Wtx434618] error -1 getting https://files.pythonhosted.org/packages/44/2b/c84376dcdfea3cb2e5c4223d3683751e3ed142481103447cc2d4169c2520/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> 2023-12-13 08:48:01,393 INFO  [req193086] GET /macaw/qa-rda-dev/pip/
> 2023-12-13 08:48:01,699 INFO  [req193087] GET /macaw/qa-rda-dev/+simple/pip/
> 2023-12-13 08:50:56,095 INFO  [req193088] GET /macaw/qa-rda-dev/confluent-kafka/
> 2023-12-13 08:50:56,350 INFO  [req193089] GET /macaw/qa-rda-dev/+simple/confluent-kafka/
> 2023-12-13 08:50:57,904 INFO  [req193090] GET /root/pypi/+f/cec/97f8c6564b165/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> 2023-12-13 08:50:57,960 WARNI Certificate did not match expected hostname: files.pythonhosted.org. Certificate: {'subject': ((('commonName', 'r.shared-319-default.ssl.fastly.net'),),), 'issuer': ((('countryName', 'BE'),), (('organizationName', 'GlobalSign nv-sa'),), (('commonName', 'GlobalSign Atlas R3 DV TLS CA 2023 Q1'),)), 'version': 3, 'serialNumber': '01D06257899F0DD2481ECE65A0533F7E', 'notBefore': 'Apr 10 04:55:11 2023 GMT', 'notAfter': 'May 11 04:55:10 2024 GMT', 'subjectAltName': (('DNS', 'r.shared-319-default.ssl.fastly.net'),), 'OCSP': ('http://ocsp.globalsign.com/ca/gsatlasr3dvtlsca2023q1',), 'caIssuers': ('http://secure.globalsign.com/cacert/gsatlasr3dvtlsca2023q1.crt',), 'crlDistributionPoints': ('http://crl.globalsign.com/ca/gsatlasr3dvtlsca2023q1.crl',)}
> 2023-12-13 08:50:57,961 WARNI [req193090] [Wtx434618] OS error during httpget of https://files.pythonhosted.org/packages/44/2b/c84376dcdfea3cb2e5c4223d3683751e3ed142481103447cc2d4169c2520/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl at /usr/lib/python3.7/site-packages/devpi_server/views.py:1338::iter_cache_remote_file
> 2023-12-13 08:50:57,963 ERROR [req193090] [Wtx434618] error -1 getting https://files.pythonhosted.org/packages/44/2b/c84376dcdfea3cb2e5c4223d3683751e3ed142481103447cc2d4169c2520/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> 2023-12-13 08:50:58,545 INFO  [req193091] GET /macaw/qa-rda-dev/pip/
> 2023-12-13 08:50:58,858 INFO  [req193092] GET /macaw/qa-rda-dev/+simple/pip/

**NOTE:** I am able to download the wheel file using wget

**Comment by fschulze** [comment]
> * [ ]  Are you using the latest released version?
>       No. We are on devpi-server 5.4.1. We are hosting the internal devpi-server since 2020 and this is the first time we saw this error

This is contradicted by your pip list:
> > devpi-server         6.3.1

> > 2023-12-13 08:48:00,756 INFO  [req193085] GET /root/pypi/+f/cec/97f8c6564b165/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> > 2023-12-13 08:48:00,808 WARNI Certificate did not match expected hostname: files.pythonhosted.org. Certificate: {'subject': ((('commonName', 'r.shared-319-default.ssl.fastly.net'),),), 'issuer': ((('countryName', 'BE'),), (('organizationName', 'GlobalSign nv-sa'),), (('commonName', 'GlobalSign Atlas R3 DV TLS CA 2023 Q1'),)), 'version': 3, 'serialNumber': '01D06257899F0DD2481ECE65A0533F7E', 'notBefore': 'Apr 10 04:55:11 2023 GMT', 'notAfter': 'May 11 04:55:10 2024 GMT', 'subjectAltName': (('DNS', 'r.shared-319-default.ssl.fastly.net'),), 'OCSP': ('http://ocsp.globalsign.com/ca/gsatlasr3dvtlsca2023q1',), 'caIssuers': ('http://secure.globalsign.com/cacert/gsatlasr3dvtlsca2023q1.crt',), 'crlDistributionPoints': ('[http://crl.globalsign.com/ca/gsatlasr3dvtlsca2023q1.crl',)}](http://crl.globalsign.com/ca/gsatlasr3dvtlsca2023q1.crl',)%7D)
> > 2023-12-13 08:48:00,809 WARNI [req193085] [Wtx434618] OS error during httpget of https://files.pythonhosted.org/packages/44/2b/c84376dcdfea3cb2e5c4223d3683751e3ed142481103447cc2d4169c2520/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl at /usr/lib/python3.7/site-packages/devpi_server/views.py:1338::iter_cache_remote_file
> > 2023-12-13 08:48:00,811 ERROR [req193085] [Wtx434618] error -1 getting https://files.pythonhosted.org/packages/44/2b/c84376dcdfea3cb2e5c4223d3683751e3ed142481103447cc2d4169c2520/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> > 2023-12-13 08:48:01,393 INFO  [req193086] GET /macaw/qa-rda-dev/pip/
> > 2023-12-13 08:48:01,699 INFO  [req193087] GET /macaw/qa-rda-dev/+simple/pip/
> > 2023-12-13 08:50:56,095 INFO  [req193088] GET /macaw/qa-rda-dev/confluent-kafka/
> > 2023-12-13 08:50:56,350 INFO  [req193089] GET /macaw/qa-rda-dev/+simple/confluent-kafka/
> > 2023-12-13 08:50:57,904 INFO  [req193090] GET /root/pypi/+f/cec/97f8c6564b165/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> > 2023-12-13 08:50:57,960 WARNI Certificate did not match expected hostname: files.pythonhosted.org. Certificate: {'subject': ((('commonName', 'r.shared-319-default.ssl.fastly.net'),),), 'issuer': ((('countryName', 'BE'),), (('organizationName', 'GlobalSign nv-sa'),), (('commonName', 'GlobalSign Atlas R3 DV TLS CA 2023 Q1'),)), 'version': 3, 'serialNumber': '01D06257899F0DD2481ECE65A0533F7E', 'notBefore': 'Apr 10 04:55:11 2023 GMT', 'notAfter': 'May 11 04:55:10 2024 GMT', 'subjectAltName': (('DNS', 'r.shared-319-default.ssl.fastly.net'),), 'OCSP': ('http://ocsp.globalsign.com/ca/gsatlasr3dvtlsca2023q1',), 'caIssuers': ('http://secure.globalsign.com/cacert/gsatlasr3dvtlsca2023q1.crt',), 'crlDistributionPoints': ('[http://crl.globalsign.com/ca/gsatlasr3dvtlsca2023q1.crl',)}](http://crl.globalsign.com/ca/gsatlasr3dvtlsca2023q1.crl',)%7D)
> > 2023-12-13 08:50:57,961 WARNI [req193090] [Wtx434618] OS error during httpget of https://files.pythonhosted.org/packages/44/2b/c84376dcdfea3cb2e5c4223d3683751e3ed142481103447cc2d4169c2520/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl at /usr/lib/python3.7/site-packages/devpi_server/views.py:1338::iter_cache_remote_file
> > 2023-12-13 08:50:57,963 ERROR [req193090] [Wtx434618] error -1 getting https://files.pythonhosted.org/packages/44/2b/c84376dcdfea3cb2e5c4223d3683751e3ed142481103447cc2d4169c2520/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
> > 2023-12-13 08:50:58,545 INFO  [req193091] GET /macaw/qa-rda-dev/pip/
> > 2023-12-13 08:50:58,858 INFO  [req193092] GET /macaw/qa-rda-dev/+simple/pip/

> **NOTE:** I am able to download the wheel file using wget

From where? devpi, or directly from ``https://files.pythonhosted.org/packages/44/2b/c84376dcdfea3cb2e5c4223d3683751e3ed142481103447cc2d4169c2520/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl``?

It seems like something has trouble resolving the certificate. Judging from your pip list you use a version which uses ``aiohttp``. Could you try with the following release candidate for devpi-server 6.10.0 which uses ``httpx`` instead?

https://m.devpi.net/fschulze/dev/devpi-server/6.10.0.dev0
https://m.devpi.net/fschulze/dev/+f/0d1/fc7a6efaaec94/devpi_server-6.10.0.dev0-py3-none-any.whl

**Comment by pchatterjee-cfx** [comment]
> This is contradicted by your pip list:
> 
>         devpi-server 6.3.1
This is not the deployed version but the version on my laptop. My apologies. I sent the pip list from client's perspecrtive. The deployed server servion is 5.4.1

pip list from server

> Package                    Version
> -------------------------- ---------
> apipkg                     1.5
> appdirs                    1.4.4
> argon2-cffi                20.1.0
> attrs                      19.3.0
> certifi                    2020.6.20
> cffi                       1.14.0
> chardet                    3.0.4
> check-manifest             0.42
> devpi-client               5.2.2
> devpi-common               3.6.0
> devpi-plumber              0.5.1
> devpi-server               5.4.1
> distlib                    0.3.1
> execnet                    1.7.1
> filelock                   3.0.12
> hupper                     1.10.2
> idna                       2.10
> importlib-metadata         1.7.0
> itsdangerous               1.1.0
> lazy                       1.4
> packaging                  20.4
> passlib                    1.7.2
> PasteDeploy                2.1.0
> pep517                     0.8.2
> pip                        20.1.1
> pkginfo                    1.5.0.1
> plaster                    1.0
> plaster-pastedeploy        0.7
> pluggy                     0.13.1
> py                         1.9.0
> pycparser                  2.20
> pyparsing                  2.4.7
> pyramid                    1.10.4
> python-dateutil            2.8.1
> repoze.lru                 0.7
> requests                   2.24.0
> ruamel.yaml                0.16.10
> ruamel.yaml.clib           0.2.0
> setuptools                 42.0.2
> six                        1.15.0
> strictyaml                 1.0.6
> supervisor                 4.1.0
> toml                       0.10.1
> tox                        3.17.1
> translationstring          1.4
> twitter.common.contextutil 0.3.11
> twitter.common.dirutil     0.3.11
> twitter.common.lang        0.3.11
> urllib3                    1.25.9
> venusian                   3.0.0
> virtualenv                 20.0.27
> waitress                   1.4.4
> WebOb                      1.8.6
> wheel                      0.34.2
> zipp                       3.1.0
> zope.deprecation           4.4.0
> zope.interface             5.1.0


> From where? devpi, or directly from https://files.pythonhosted.org/packages/44/2b/c84376dcdfea3cb2e5c4223d3683751e3ed142481103447cc2d4169c2520/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl?

Directly from the URL

**Comment by fschulze** [comment]
You might have to update the ``certifi`` package, but I'm not sure what ``requests`` is using. This is not directly a devpi-server bug, but somewhere in the ``requests`` dependencies. If you install the same packages in a virtual environment, then it is likely that a plain ``requests.get("...")`` will also fail. You can then test in the virtualenv what you have to update.

**Comment by pchatterjee-cfx** [comment]
One observation is that I don't run into this issue if I use `root/pypi` index directly. Only when I use any of the other indices that I encounter this issue. 

> (PYTHON37) $ pip uninstall confluent-kafka && pip install confluent-kafka==2.3.0 -i http://10.95.159.86:3141/macaw/qa-rda-dev/ --trusted-host 10.95.159.86 --no-cache-dir
> WARNING: Skipping confluent-kafka as it is not installed.
> Looking in indexes: http://10.95.159.86:3141/macaw/qa-rda-dev/
> Collecting confluent-kafka==2.3.0
>   ERROR: HTTP error 502 while getting http://10.95.159.86:3141/root/pypi/%2Bf/cec/97f8c6564b165/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=cec97f8c6564b16504d30fe42c22fd4a86c406dbcd45c337b93c21e876e20628 (from http://10.95.159.86:3141/macaw/qa-rda-dev/+simple/confluent-kafka/)
> ERROR: Could not install requirement confluent-kafka==2.3.0 from http://10.95.159.86:3141/root/pypi/%2Bf/cec/97f8c6564b165/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=cec97f8c6564b16504d30fe42c22fd4a86c406dbcd45c337b93c21e876e20628 because of HTTP error 502 Server Error: Bad Gateway for url: http://10.95.159.86:3141/root/pypi/%2Bf/cec/97f8c6564b165/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl for URL http://10.95.159.86:3141/root/pypi/%2Bf/cec/97f8c6564b165/confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=cec97f8c6564b16504d30fe42c22fd4a86c406dbcd45c337b93c21e876e20628 (from http://10.95.159.86:3141/macaw/qa-rda-dev/+simple/confluent-kafka/)
> 
> [notice] A new release of pip available: 22.2.2 -> 23.3.1
> [notice] To update, run: pip install --upgrade pip
> (PYTHON37) $ pip uninstall confluent-kafka && pip install confluent-kafka==2.3.0 --no-cache-dir
> WARNING: Skipping confluent-kafka as it is not installed.
> Collecting confluent-kafka==2.3.0
>   Downloading confluent_kafka-2.3.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.0 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 18.2 MB/s eta 0:00:00
> Installing collected packages: confluent-kafka
> Successfully installed confluent-kafka-2.3.0

**Comment by fschulze** [comment]
When you use pip directly with pipy.org, then your client is accessing it and the libraries you have installed are relevant, which are most likely newer than the ones on the server. The problem is most likely outdated libraries/certificates (in for example certifi) on your server.

**Comment by pchatterjee-cfx** [comment]
The issue is resolved by switching to the latest version of devpi-server. We were due for an upgrade for some time. I used the opportunity to move to the latest version.
Thank you Florian.
