### ISSUE TITLE
Devpi test fails with something related to build(i assume)

### ISSUE THREAD

**Issue by Stefanhg** [devpi/devpi#1025]
Hello,

When looking at the HTML output on pypi i noticed my tests was failing even tho it is executed though Devpi and I am unsure if this is caused by either Tox, setuptools or Devpi but since Tox passes if i do it manually I would assume it must be Devpi or setuptools. 
Error message is not very obvious so I can't figure out where the issue belongs. All tests passes from Tox's side.

**Requirements:**
```
setuptools>=45 setuptools_scm[toml]>=6.2

pip==23.3.2
setuptools==69.0.3
wheel==0.42.0
```

I don't know how this issues is possible to reproduce so hopefully issue can be found without the need of an example.

It writes the same setup command 5 times where it fails all of the times that it is called but with different output.:
For each `Setup output` written below the same `Setup command` is sent

**Output from website:**
```
Setup command:
C:\Users\shg\AppData\Local\Temp\devpi-test-z0fljiqy\targz\blab_log-0.1.1\.tox\.pkg_external_sdist_meta\Scripts\python.EXE C:\Python310\lib\site-packages\pyproject_api\_backend.py True setuptools.build_meta __legacy__

Setup output:
Backend: run command _optional_hooks with args {}
Backend: Wrote response {'return': {'get_requires_for_build_sdist': True, 'prepare_metadata_for_build_wheel': True, 'get_requires_for_build_wheel': True, 'build_editable': True, 'get_requires_for_build_editable': True, 'prepare_metadata_for_build_editable': True}} to C:\Users\shg\AppData\Local\Temp\pep517__optional_hooks-r30soj1f.json

Setup output 2:
Backend: run command get_requires_for_build_sdist with args {'config_settings': None}
running egg_info
writing blab_log.egg-info\PKG-INFO
writing dependency_links to blab_log.egg-info\dependency_links.txt
writing requirements to blab_log.egg-info\requires.txt
writing top-level names to blab_log.egg-info\top_level.txt
reading manifest file 'blab_log.egg-info\SOURCES.txt'
writing manifest file 'blab_log.egg-info\SOURCES.txt'
Backend: Wrote response {'return': []} to C:\Users\shg\AppData\Local\Temp\pep517_get_requires_for_build_sdist-x3tlyeaz.json

Setup output 3:
Backend: run command get_requires_for_build_wheel with args {'config_settings': None}
running egg_info
writing blab_log.egg-info\PKG-INFO
writing dependency_links to blab_log.egg-info\dependency_links.txt
writing requirements to blab_log.egg-info\requires.txt
writing top-level names to blab_log.egg-info\top_level.txt
reading manifest file 'blab_log.egg-info\SOURCES.txt'
writing manifest file 'blab_log.egg-info\SOURCES.txt'
Backend: Wrote response {'return': ['wheel']} to C:\Users\shg\AppData\Local\Temp\pep517_get_requires_for_build_wheel-7tll3qs4.json

The next two setup command and setup output does pip install wheel and pip freeze --all and passes

Setup output 6:
Backend: run command prepare_metadata_for_build_wheel with args {'metadata_directory': 'C:\\Users\\shg\\AppData\\Local\\Temp\\devpi-test-z0fljiqy\\targz\\blab_log-0.1.1\\.tox\\.pkg_external_sdist_meta\\.meta', 'config_settings': None}
running dist_info
creating C:\Users\shg\AppData\Local\Temp\devpi-test-z0fljiqy\targz\blab_log-0.1.1\.tox\.pkg_external_sdist_meta\.meta\blab_log.egg-info
writing C:\Users\shg\AppData\Local\Temp\devpi-test-z0fljiqy\targz\blab_log-0.1.1\.tox\.pkg_external_sdist_meta\.meta\blab_log.egg-info\PKG-INFO
writing dependency_links to C:\Users\shg\AppData\Local\Temp\devpi-test-z0fljiqy\targz\blab_log-0.1.1\.tox\.pkg_external_sdist_meta\.meta\blab_log.egg-info\dependency_links.txt
writing requirements to C:\Users\shg\AppData\Local\Temp\devpi-test-z0fljiqy\targz\blab_log-0.1.1\.tox\.pkg_external_sdist_meta\.meta\blab_log.egg-info\requires.txt
writing top-level names to C:\Users\shg\AppData\Local\Temp\devpi-test-z0fljiqy\targz\blab_log-0.1.1\.tox\.pkg_external_sdist_meta\.meta\blab_log.egg-info\top_level.txt
writing manifest file 'C:\Users\shg\AppData\Local\Temp\devpi-test-z0fljiqy\targz\blab_log-0.1.1\.tox\.pkg_external_sdist_meta\.meta\blab_log.egg-info\SOURCES.txt'
reading manifest file 'C:\Users\shg\AppData\Local\Temp\devpi-test-z0fljiqy\targz\blab_log-0.1.1\.tox\.pkg_external_sdist_meta\.meta\blab_log.egg-info\SOURCES.txt'
writing manifest file 'C:\Users\shg\AppData\Local\Temp\devpi-test-z0fljiqy\targz\blab_log-0.1.1\.tox\.pkg_external_sdist_meta\.meta\blab_log.egg-info\SOURCES.txt'
creating 'C:\Users\shg\AppData\Local\Temp\devpi-test-z0fljiqy\targz\blab_log-0.1.1\.tox\.pkg_external_sdist_meta\.meta\blab_log-0.1.1.dist-info'
Backend: Wrote response {'return': 'blab_log-0.1.1.dist-info'} to C:\Users\shg\AppData\Local\Temp\pep517_prepare_metadata_for_build_wheel-bfctwjs7.json

Setup output 7:
Backend: run command _exit with args {}
Backend: Wrote response {'return': 0} to C:\Users\shg\AppData\Local\Temp\pep517__exit-8f_evlh4.json
```

**Comment by Stefanhg** [comment]
@fschulze I updated the description.
It is a internal site so i can't link to it.
I just gave it another look:
The HTML is generated under the "tox result" section on the devpi web server (apparently that's what powers this)
It runs:
devpi-web 4.1.1
devpi-server 6.9.0
devpi-ldab 2.1.0
devpi-jenkins 2.0.0

**Comment by fschulze** [comment]
Still trying to figure out what you mean. It sounds like you have a problem with the display of tox results in devpi-web? There is a known issue with the new ``.pkg_external`` stuff from tox4: https://github.com/devpi/devpi/issues/971 Are the tests actually failing and you don't know why? Or are they only marked as failing even though they passed?

**Comment by Stefanhg** [comment]
Sorry for the confusion.
My problem is related to `.pkg_external_sdist_meta`. It always says that it failed with the output mentioned in my issue description. I don't know what part of it is an error or what is OK. It seems like when it runs the pyproject_api\_backend.py it assums the result is a error or something like that.

If i run Tox manually it passes but when I run `devpi test` it fails in `.pkg_external_sdist_meta`.
I am really unsure what actually fails in it IF there even is a fail. Could be a bug that the output is incorrect.

**Comment by fschulze** [comment]
I'm pretty sure it is just the output in devpi-web. The ``devpi test`` command should exit with a return code of 0 where ever you run it (I guess CI?). So this is most likely a duplicate of https://github.com/devpi/devpi/issues/971

**Comment by Stefanhg** [comment]
@fschulze I tested `devpi test` again and checked the return code. Indeed you are right.
It returns 0.
So I do agree it must be a duplicate of https://github.com/devpi/devpi/issues/971
That is surely better than an actual bug within the running of tests.
Closing issue!
