### ISSUE TITLE
Cannot use a mirror that have do not have a list in /pypi/web/simple, namely sjtu pypi mirror

### ISSUE THREAD

**Issue by loeeeee** [devpi/devpi#1041]
Thanks a lot for the helpful project. :)

# Problem description

I am trying to set up devpi as a local mirror of `https://mirror.sjtu.edu.cn/pypi/web/simple`. After following steps mentioned in [Issue: Changing mirror_url doesn't seem to work](https://github.com/devpi/devpi/issues/817#issue-693300568), I managed to get it working. But because of the rate limit, the download speed of uncached packages is not ideal. So, I changed the index_url to `https://mirror.sjtu.edu.cn/pypi/web/simple`, a known fast mirror, but devpi-server fail to pull any index from it.

i.e., in the client machine,
```
$ pip install numpy
Looking in indexes: https://pypi.mylocalserver.com/root/pypi/+simple/
ERROR: Could not find a version that satisfies the requirement numpy (from versions: none)
ERROR: No matching distribution found for numpy
```

in the server,
```
Jun 17 06:33:33 Uranus devpi-server[16140]: 2024-06-17 06:33:33,204 INFO  [req35] GET /root/pypi/+simple/numpy/
Jun 17 06:33:33 Uranus devpi-server[16140]: 2024-06-17 06:33:33,205 ERROR [req35] [Rtx18] while handling https://pypi.mylocalserver.com/root/pypi/+simple/numpy/:
Jun 17 06:33:33 Uranus devpi-server[16140]: The project numpy does not exist.
```

Also, there are no log entries, like when I was using mirror from Aliyun, saying that getting index from blahblahblah (some huge number queued). Unfortunately, because the log was flushed, I am not able to paste those here. And I don't fell like reinstall devpi to reproduce this. But I will try if it is really necessary.

As far as I know, devpi, when mirroring, tries to pull the list of index from https://somemirror.com/pypi/web/simple/. However, in this case, the mirror "https://mirror.sjtu.edu.cn/pypi/web/simple", works a bit differently.

On [its page](https://mirror.sjtu.edu.cn/pypi/web/simple), it says

>No route for pypi/web/simple.
>
>mirror-intel uses S3-like storage backend, which means that you could not browse files like other mirror sites. Please follow our instructions to set up your software registry. If you intend to browse, we have provided an experimental API to browse bucket.
>
>[Browse pypi/web/simple](https://mirror.sjtu.edu.cn/pypi/web/simple/?mirror_intel_list)

Is this kind of mirror supported or I might need a different mirror? I kinda like this mirror, it goes really fast, like fully utilizing 1000 Mbps broadband connection kind of fast, but it has a rate limit of how often one IP could download something, can be annoying sometimes.

---
# Additional information

```
$ devpi index root/pypi
https://pypi.mylocalserver.com/root/pypi:
  type=mirror
  volatile=True
  mirror_url=https://mirrors.sustech.edu.cn/pypi/web/simple
  mirror_web_url_fmt=https://pypi.org/project/{name}/
  title=PyPI
```
Note that `pypi.mylocalserver.com` is not a real domain name, I use my own domain name here and it has a publicly valid SSL cert.

I believe this is the latest version as the time of writing.
```
$ devpi-server --version
6.11.0
```

```
$ pip list
Package              Version
-------------------- -----------
anyio                4.4.0
argon2-cffi          23.1.0
argon2-cffi-bindings 21.2.0
attrs                23.2.0
beautifulsoup4       4.12.3
build                1.2.1
certifi              2024.6.2
cffi                 1.16.0
Chameleon            4.5.4
charset-normalizer   3.3.2
check-manifest       0.49
cmarkgfm             2024.1.14
defusedxml           0.7.1
devpi                2.2.0
devpi-client         7.0.3
devpi-common         4.0.4
devpi-server         6.11.0
devpi-web            4.2.2
docutils             0.21.2
h11                  0.14.0
httpcore             1.0.5
httpx                0.27.0
hupper               1.12.1
idna                 3.7
iniconfig            2.0.0
itsdangerous         2.2.0
lazy                 1.6
nh3                  0.2.17
packaging            24.1
packaging-legacy     23.0.post0
passlib              1.7.4
PasteDeploy          3.1.0
pip                  24.0
pkginfo              1.11.1
plaster              1.1.2
plaster-pastedeploy  1.0.1
platformdirs         4.2.2
pluggy               1.5.0
py                   1.11.0
pycparser            2.22
Pygments             2.18.0
pyproject_hooks      1.1.0
pyramid              2.0.2
pyramid-chameleon    0.3
python-dateutil      2.9.0.post0
readme_renderer      43.0
repoze.lru           0.7
requests             2.32.3
ruamel.yaml          0.18.6
ruamel.yaml.clib     0.2.8
setuptools           70.0.0
six                  1.16.0
sniffio              1.3.1
soupsieve            2.5
strictyaml           1.7.3
translationstring    1.4
urllib3              2.2.1
venusian             3.1.0
waitress             3.0.0
WebOb                1.8.7
Whoosh               2.7.4
zope.deprecation     5.0
zope.interface       6.4.post2
```

```
$ python3 --version
Python 3.12.3
```

The server is running in a Ubuntu 24.04 LTS in a LXC container using a Debian 12 kernel with Proxmox VE patch applied.

**Comment by fschulze** [comment]
You can try setting ``mirror_no_project_list`` to ``true`` for that index. I added that feature in 6.9.0, but got no feedback on it yet. See https://github.com/devpi/devpi/discussions/887 and #1006

**Comment by loeeeee** [comment]
> You can try setting `mirror_no_project_list` to `true` for that index. I added that feature in 6.9.0, but got no feedback on it yet. See #887 and #1006

This setting makes wonders! Everything works like a charm! Thank you so much!

Solution:

After following #817,

```
devpi index root/pypi mirror_url="https://mirror.sjtu.edu.cn/pypi/web/simple" mirror_no_project_list=True
```

😀
