### ISSUE TITLE
Running devpi-server as upstream cache in HA mode

### ISSUE THREAD

**Issue by kostas-rf** [devpi/devpi#1050]
Hi,

We currently run devpi-server in Kubernetes as an upstream proxy/cache on a single instance (statefulset pod), which works with no issues.

A (fair) question was raised about the resiliency of this setup as it currently doesn't support a highly available solution due to only using a single instance. I had a look into the documentation about the HA setup options (server replication etc.), which seems a bit overkill since we do not publish any packages directly on to the devpi-server.

My question is if running two identical (in terms of config) instances behind a reverse proxy would be possible. I understand that the cached files would be different on each instance, but that is not a problem as long as these can be fetched from upstream.

Do you foresee any issue with the above setup? Would there be any issue if requests land randomly on anyone of the two instances? 

Thanks!

**Comment by fschulze** [comment]
From your description I guess you use devpi only with installers like pip on the ``root/pypi`` index? For that scenario I see no issue with your idea. To be certain no one uses it differently I would block all URLs besides ``/root/pypi/+simple/.*`` in the proxy. The only *weirdness* that can happen is different available files after new releases were made, due to different cache expiry times caused by different access patterns. Those should be limited to the default expiration time of 30 minutes and resolve after that.

**Comment by kostas-rf** [comment]
Thank you for your suggestions. Will close this for now and report back if there are any issues.

**Comment by kostas-rf** [comment]
Hi @fschulze,

We did this setup in kubernetes, but we noticed the following issue:

When requests come in they can land on different pods, for example requesting a package we see the following:

1. Initial request `GET /root/artifactory/+simple/pyjwt/` lands on `pod 1`
2. Request to download the package `GET /root/artifactory/+f/3b0/2fb0f44517787/PyJWT-2.9.0-py3-none-any.whl` lands on `pod 2`. At this point we get the below error:

```
ERROR [req75817] [Rtx26] while handling https://devpi.example.com/root/artifactory/+f/3b0/2fb0f44517787/PyJWT-2.9.0-py3-none-any.whl:
no such file
```

Of course if i manually send a `GET /root/artifactory/+simple/pyjwt/` requests to `pod 2` then the download works.

Is this the expected behavior? If yes, is there a way to make it work consistently across different instances?

Thanks!

**Comment by fschulze** [comment]
Ah, yes, that is expected. You would need to setup session affinity in the frontend proxy, so subsequent requests from the same client go to the same pod.

**Comment by kostas-rf** [comment]
Exactly what we ended up doing, which seems to work fine for now. 

Is there a plan to make this work without the session affinity? Maybe a potential feature to support HA setups?

If not, not a problem. Mostly a nice-to-have.

Thanks

**Comment by fschulze** [comment]
This is an enterprise requirement and you can contact mail@pyfidelity.com to discuss the details for a contract.

**Comment by kostas-rf** [comment]
Understood, closing this for now.
