### ISSUE TITLE
Packages built with hatch will not upload to devpi

### ISSUE THREAD

**Issue by anselor** [devpi/devpi#1052]
devpi client is unable to upload packages built using hatch.
Reports:

does not contain PKGINFO: skipping.

Just try pulling the latest version of `structlog` or `pydantic` and upload to devpi.

**Comment by fschulze** [comment]
I just tried it locally with:
https://files.pythonhosted.org/packages/78/a3/e811a94ac3853826805253c906faa99219b79951c7d58605e89c79e65768/structlog-24.4.0.tar.gz
https://files.pythonhosted.org/packages/bf/65/813fc133609ebcb1299be6a42e5aea99d6344afb35ccb43f67e7daaa3b92/structlog-24.4.0-py3-none-any.whl

And both uploaded fine.

This check is done locally in devpi-client using the ``pkginfo`` library. Maybe that one needs an update in your installation?

As a workaround you could try to use twine for upload.

**Comment by anselor** [comment]
Thank you! `pkginfo` was the issue. Perhaps it would be a good idea to specify a minimum version for `pkginfo` going forward so that it gets updated in sync?

**Comment by fschulze** [comment]
Which version did you have before? It would at least make sense to give a hint in the error message.

**Comment by anselor** [comment]
Old version I had was 1.5.0.1

**Comment by fschulze** [comment]
As ``devpi-client`` still supports Python 3.7 I updated the pin to 1.10.0 which supports metadata 2.3. With 1.11.0 there will be warnings about unknown (future) versions.
