### ISSUE TITLE
devpi-web: Link to download the doczip

### ISSUE THREAD

**Issue by jrast** [devpi/devpi#1062]
Is it possible to download the doczip file uploaded for a package via the web interface?

If not (in the current version):

- Is there interest in such a feature?
- What would it take to realize? Some hints on how to do this would help to play around with this idea.

**Comment by fschulze** [comment]
Currently it is not possible.

I didn't have the need yet, and nobody asked yet. So I can't say whether there is interest. I would welcome it being added though.

Take a look at ``get_docs_info`` and where it is used (in code and the result in templates), maybe that is already enough to get you going. If not, feel free to ask for more pointers. I guess it would make most sense to show a download link on the version details page, but if you think another place is better, feel free to try it.
