### ISSUE TITLE
Provide better SSL protocol support

### ISSUE THREAD

**Issue by melvyn-sopacua** [devpi/devpi#408]
My openssl library on internet facing servers do not have SSLv3 protocol enabled (as per [Deployment best practices](https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices#22-use-secure-protocols)).

Using a very thin layer we can be more robust with protocol selections:

```python
import ssl
import requests
from requests.packages.urllib3.poolmanager import PoolManager
from requests.adapters import HTTPAdapter
from requests.exceptions import SSLError


class HttpsAdapter(HTTPAdapter):
    poolmanager = None

    def __init__(self, protocol, **kwargs):
        if isinstance(protocol, str):
            self.ssl_proto = getattr(ssl, 'PROTOCOL_' + protocol)
        else:
            self.ssl_proto = protocol

        super().__init__(**kwargs)

    def init_poolmanager(self, connections, maxsize, block=False, **kwargs):
        self.poolmanager = PoolManager(
            num_pools=connections, maxsize=maxsize, block=block,
            ssl_version=self.ssl_proto
        )

url = 'https://pypi.python.org/'
print('Using OpenSSL {}'.format(ssl.OPENSSL_VERSION))

try:
    with requests.Session() as s:
        s.mount('https://', HttpsAdapter('TLSv1_2'))
        response = s.get(url)
except SSLError:
    try:
        with requests.Session() as s:
            s.mount('https://', HttpsAdapter('TLSv1_1'))
            response = s.get(url)
    except SSLError:
        try:
            with requests.Session() as s:
                s.mount('https://', HttpsAdapter('TLSv1'))
                response = s.get(url)
        except SSLError:
            with requests.Session() as s:
                s.mount('https://', HttpsAdapter('SSLv3'))
                response = s.get(url)


print(response.status_code)
```
Note that this still won't fix connecting to servers that offer EC ciphers as first option, when using OpenSSL 1.1 and Python < 3.6.1, because of [bpo-29697](http://bugs.python.org/issue29697).

**Comment by fschulze** [comment]
What exactly is the problem? Can't devpi-server connect to PyPI when SSLv3 is disabled? What error/log output do you see in that case?

**Comment by melvyn-sopacua** [comment]
Sorry for the late response.
I dug into this deeper and the sole issue is the referenced bug in Python itself. As soon as an EC certificate is presented, devpi (but also pip and anything using urllib3) cannot connect, if OpenSSL version is >=1.1.0.
When I tried the above testing code, I was "secretly" using OpenSSL 1.0.1, hiding the root cause. So no issue here and closing.
