### ISSUE TITLE
proposed modification to semantics of PyPI `changelog_since_serial` call.

### ISSUE THREAD

**Issue by ewdurbin** [devpi/devpi#410]
👋 devpi team! I'm ernest, and I work with handful of others on the PSF Infrastructure "Staff". One my primary focuses has always been the health and safety of PyPI.

Recently, when debugging some reoccurring bad behavior in our backends, I discovered some incredibly out of date bandersnatch mirrors requesting gigabytes worth of data from the `changelog_since_serial` XMLRPC method by providing a wildly old serial.

More details here: https://bitbucket.org/pypa/bandersnatch/issues/89/calls-to-changelog_since_serial-for-very

While investigating top users of this endpoint, it boiled down to `bandersnatch` and `devpi`, at well above 99% of calls.

Due to the technical limitations of leaving this endpoint open to such requests, the `bandersnatch` maintainer proposed a solid solution which appears to be compatible with (albeit older) releases of devpi up to 2.2.2 when XMLRPC calls were removed (thank you, sincerely from the bottom of my heart).

Proposed modification:
  - Calls to `changelog_since_serial` will only provide a safe number of sequential journal entries rather than all journal entries up to the current serial.
  - Example, If the current serial were 2800000 a request for `changelog_since_serial(1)` would return journal entries 2 through 50001 rather than 2 through 2800000.
  - Callers would be expected to handle the provided journal entries however they please, calling `changelog_since_serial` once again with their new position in the journal. 50001 in the example above.

It appears that the above would be compatible with devpi's utilization of the API from [it's introduction](https://github.com/devpi/devpi/blob/42c165b01ce5917b267bcbadab73fb991b22e5a4/server/devpi_server/extpypi.py#L337-L346) through [it's final incarnation before being deprecated](https://github.com/devpi/devpi/blob/05f21c7c9cdbd231f5569038ae9d43badd49db38/server/devpi_server/extpypi.py#L403-L413) 

Given that devpi-server is a heavy consumer of this endpoint, I wanted to ensure that the maintainers of the project could confirm this wouldn't be disruptive to the user base before taking action.

Thanks again! Really appreciate devpi's place in the Python Packaging community.

**Comment by fschulze** [comment]
Thanks for the heads up!

I'm pretty sure this won't affect anyone. The old installations will just iteratively catch up as you already stated. Also any devpi-server installation < 4.0.0 won't work correctly with PyPI anyway, due to the changed project name normalization which causes packages with dots in their name to not be accessible (#343, #344).

I think the returned result will indicate the current serial in a http header, so any consumer of the API can update it to automatically detect that not all data was returned yet.

**Comment by ewdurbin** [comment]
change has been implemented in https://github.com/pypa/pypi-legacy/commit/760edfa98f5dc3210578215785e62ec9d7253e80, and is live on testpypi.python.org for now.

**Comment by fschulze** [comment]
@ewdurbin is this on production as well now?

**Comment by ewdurbin** [comment]
@fschulze it is.
