### ISSUE TITLE
consider using systemd for process/log management in the systemd template

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [devpi/devpi#417]
systemd is capable of handling process output and termination using signals - it may be a good idea to start to use it that way instead of invoking a homegrown process management

**Comment by tuukkamustonen** [comment]
How about those distros that don't use `systemd`? I assume such exist.

**Comment by fschulze** [comment]
He meant something else. Currently even when using systemd the custom process management of devpi is used, which doesn't make sense. This is only about the systemd template used when creating the example configuration files.

**Comment by RonnyPfannschmidt** [comment]
correct - for the systemd template - systemd is far more capable at managing all details than devpi is

**Comment by fschulze** [comment]
I have simplified the systemd template in 02c1c61cd79423acd47a480cf03e51c43d8487ff.
