### ISSUE TITLE
consider to remove the custom daemon management alltogether

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [devpi/devpi#427]
with the rise of tools like systemd user units and other process monitors, devpi should consider to remove its own handmade daemon management, as all the dedicated versions are far more feature-full and well-documented

**Comment by fschulze** [comment]
It's mainly for the "run it on my laptop" use case.

@hpk42 what do you think about removing it?

**Comment by RonnyPfannschmidt** [comment]
@fschulze from my pov systemd user units are far better for something like that (since they do log output management and various other details

also these days deploying a instance via docker + a mounted volume may be more practical than stuffing some stuff into some folder

**Comment by fschulze** [comment]
It's deprecated more prominently now and the example configurations have been improved. The only remaining place to remove them are the docs, which isn't trivial, because they are run with regendocs.

**Comment by fschulze** [comment]
All preparations are done and the next major release will get #708
