### ISSUE TITLE
consider publishing official docker images

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [devpi/devpi#428]
the idea is to have a docker image that supports devpi and using the data folder as a mounted volume that will automatically be upgraded/migrated

that way its easy to manage a isolated easy to update way of devpi deployment

**Comment by cprieto** [comment]
@RonnyPfannschmidt I can take care of this, in fact, I already made one ready to run for my local development of images (thanks to slow connection in hotels and such).

**Comment by RonnyPfannschmidt** [comment]
@cprieto it would be nice to have the a Dockerfile in the root folder as a starting point

we then need to decide whether to make a travis stage for building them or if we do them manually 

for release deployment stability reasons the continuous deployment variant the docker registry offers doesn't provide the interaction i consider necessary

also we need a migration/backup story for users that use/upgrade via docker

**Comment by fschulze** [comment]
I don't want to add it to the repository, because then we have to maintain it. I'm happy to link to one though.
