### ISSUE TITLE
how to change default mirror url pypi.python.org/simple/ with devpi-server

### ISSUE THREAD

**Issue by robertding** [devpi/devpi#433]
i start devpi-server version 4.3.0 as cache server
with cmd  `devpi-server --serverdir /root/packages/ --port 5555 --host=0.0.0.0  --start`
how can i change the default cache mirror?

**Comment by fschulze** [comment]
What do you mean by "default cache mirror"? Do you mean the URL pip uses, or the URL for the PyPI cache?

**Comment by robertding** [comment]
sorry i didn't make it clear. i want to change the default url  `pypi.python.org/simple/ ` to another mirror url like `mirrors.aliyun.com` when a package not accessable in my devpi server.

**Comment by robertding** [comment]
@fschulze sorry i dont exactly know the differnet between `pip uses`(client side usage?) and `PyPi cache`.
 I tried to modify the pip.conf in my devpi server, but it didn't work.  The devpi server still tring to get missing package from pypi.python.org which is far slow in my country.
I tried to modify the source code `config.py` under `devpi_server`, still not working. Thanks for your help.

**Comment by fschulze** [comment]
You can change ``mirror_url`` on the ``root/pypi`` index. Something like this should work (from my head, untested): ``devpi index root/pypi mirror_url="..."``. It must point to the simple index of the mirror.

**Comment by fschulze** [comment]
Did my answer solve your issue?

**Comment by blackholll** [comment]
i have the same requirement
@fschulze  
is this contol download package from ?  
in you reply, how to  "change mirror_url on the root/pypi index"?
# server/devpi_server/extpypi.py?

class PyPIStage(BaseStage):
    def __init__(self, xom, username, index, ixconfig):
        super(PyPIStage, self).__init__(xom, username, index, ixconfig)
        self.httpget = self.xom.httpget  # XXX is requests/httpget multi-thread safe?
        self.cache_expiry = self.ixconfig.get(
            'mirror_cache_expiry', xom.config.args.mirror_cache_expiry)
        self.xom = xom
        if xom.is_replica():
            url = xom.config.master_url
            self.mirror_url = url.joinpath("%s/+simple/" % self.name).url
        else:
            url = URL(self.ixconfig['mirror_url'])
            self.mirror_url = url.asdir().url

**Comment by blackholll** [comment]
and i have try to change mirror_url in main.py/_pypi_ixconfig_default/, it doesn't work

**Comment by fschulze** [comment]
You don't have to change code, use the devpi client to set the option on the index. For example to change the url for root/pypi:
```
devpi index root/pypi mirror_url="..."
```

**Comment by blackholll** [comment]
@fschulze  i think you have not understand my mean.   normally, when someone install a package that haven‘t  cached in devpi server, the devpi server when download the package from pipy.python.org.   but  we are in china, the speed is slow. so  i expect the devpi server download package from pypi.doubanio.com/simple  but not pypi.python.org.  this should be work on devpi server but not client.

**Comment by fschulze** [comment]
That's exactly what I'm saying. If you run ``devpi index root/pypi`` you should get something like this:
```
% devpi index root/pypi
https://d.rzon.de:8141/root/pypi:
  type=mirror
  volatile=False
  mirror_url=https://pypi.python.org/simple/
  mirror_web_url_fmt=https://pypi.python.org/pypi/{name}
  title=PyPI
```
Now you run ``devpi index root/pypi mirror_url="https://pypi.doubanio.com/simple/"`` and you should get something like:
```
% devpi index root/pypi mirror_url="https://pypi.doubanio.com/simple/"
/root/pypi changing mirror_url: https://pypi.doubanio.com/simple/
https://d.rzon.de:8141/root/pypi:
  type=mirror
  volatile=False
  mirror_url=https://pypi.doubanio.com/simple/
  mirror_web_url_fmt=https://pypi.python.org/pypi/{name}
  title=PyPI
```
Now packages will be downloaded from the mirror instead of regular pypi.

**Comment by blackholll** [comment]
@fschulze 
I run devpi server by supervisor, and the command is  :" /data/virtualenv/devpi/bin/devpi-server --port 404%(process_num)d --serverdir /data/project/devpiserver --outside-url=http://pypi.xxxxx.com".
how to run devpi index root/pypi mirror_url="https://pypi.doubanio.com/simple/"?   there has no args like 'mirror_url'.

**Comment by fschulze** [comment]
You need ``devpi-client`` for that, it's not a command line option of the server, but a setting in the database of the server, which you can manipulate with ``devpi-client``. See documentation, starting with https://devpi.net/docs/devpi/devpi/stable/+d/quickstart-releaseprocess.html

**Comment by blackholll** [comment]
ths very much,  it works

**Comment by pkuwwt** [comment]
Not work any more?

`devpi index root/index` root/pypi mirror_url=“...” get 

```
PATCH http://127.0.0.1:3141/root/pypi
403 Forbidden: Access was denied. To this resource
Unauthorized: PyPIVIEW failed permission check
```

**Comment by pkuwwt** [comment]
Oh, I should 

```
devpi-server --passwd root
devpi-server --start 
```

**Comment by pkuwwt** [comment]
Then there is another problem:

```
PATCH http://127.0.0.1:3141/root/pypi
500 Internal Server Error: Internal Server Error

The server encountered an unexpected internal server error

(Generated by waitress)
```

**Comment by fschulze** [comment]
You should see the traceback for the ``500 Internal Server Error`` in the devpi-server logs. In your case they should be located in ``~/.devpi/server/``. Could you paste that traceback here?

**Comment by pkuwwt** [comment]
@fschulze no, there is no logs in `~/.devpi/server/`

**Comment by fschulze** [comment]
Please try with 4.8.1. There is a fix included which I thought was already released with 4.8.0, but which I forgot.

**Comment by gary02** [comment]
Hi, I have run `devpi index root/pypi mirror_url="https://pypi.doubanio/com/simple"`， but devpi-server still fetch packages from `files.pythonhosted.org`. 

 This is my log:

```2019-12-19 12:47:56,752 INFO  [IDXQ] [Rtx780] Processed a total of 212121 projects and queued 7
2019-12-19 12:47:58,500 INFO  [req2] GET /laixi/stag/django/
2019-12-19 12:47:58,503 INFO  [req3] GET /laixi/stag/+simple/django/
2019-12-19 12:47:58,623 WARNI [req3] [Rtx780] serving cached links for https://pypi.doubanio.com/simple/django/ because returned serial -1, cache_serial 6073711 is better!
2019-12-19 12:47:58,750 WARNI [req3] [Rtx780] serving cached links for https://pypi.doubanio.com/simple/django/ because returned serial -1, cache_serial 6073711 is better!
2019-12-19 12:47:58,888 INFO  [req4] GET /root/pypi/+f/402/5317ca01f75fc/Django-2.2.6-py3-none-any.whl
2019-12-19 12:47:59,746 INFO  [req4] [Wtx780] reading remote: https://files.pythonhosted.org/packages/b2/79/df0ffea7bf1e02c073c2633702c90f4384645c40a1dd09a308e02ef0c817/Django-2.2.6-py3-none-any.whl, target root/pypi/+f/402/5317ca01f75fc/Django-2.2.6-py3-none-any.whl```

**Comment by fschulze** [comment]
The mirror doesn't send the ``x-pypi-serial`` header, because of that it uses old data (indicated by the ``serving cached links`` lines. You have to remove the ``root/pypi`` index and re-create it with ``devpi index -c root/pypi type=mirror mirror_url=https://pypi.doubanio.com/simple/`` so it uses your mirror from the start.

**Comment by gary02** [comment]
> The mirror doesn't send the `x-pypi-serial` header, because of that it uses old data (indicated by the `serving cached links` lines. You have to remove the `root/pypi` index and re-create it with `devpi index -c root/pypi type=mirror mirror_url=https://pypi.doubanio.com/simple/` so it uses your mirror from the start.
Thank you for your reply!
I just find that  `--extra-index-url` option can meet my needs too.

**Comment by yunfan** [comment]
@fschulze i had met this issue too, and from the discussions above i learnt much, but the index re-create you mentioned raised error for the target index `root/pypi` exists, so how to remove the index `root/pypi` i had searched the quickstart and havnt found a hints on this

also i want to ensure that my demands is possible

first i want to run a devpi-server which indicate the upstream server to a none-official pypa but a mirrors, because like the above guys, i am chinese :[

second i want the server i had just setted could be used like another mirror to pip, for eg,
`pip search -i http://mydevpi-server:8080/simple  devpi-server` 

is that possible or should i find other alternatives?

**Comment by fschulze** [comment]
> @fschulze i had met this issue too, and from the discussions above i learnt much, but the index re-create you mentioned raised error for the target index `root/pypi` exists, so how to remove the index `root/pypi` i had searched the quickstart and havnt found a hints on this

You can remove the index with ``devpi index --delete root/pypi``. You have to be logged in as ``root``.

> also i want to ensure that my demands is possible
> 
> first i want to run a devpi-server which indicate the upstream server to a none-official pypa but a mirrors, because like the above guys, i am chinese :[

If you don't have any data in your server yet, you can also use the ``--no-root-pypi`` option when running ``devpi-init``. Then you can manually add the mirror index: ``devpi index -c root/pypi type=mirror mirror_url=...``.

> second i want the server i had just setted could be used like another mirror to pip, for eg,
> `pip search -i http://mydevpi-server:8080/simple devpi-server`
> 
> is that possible or should i find other alternatives?

For ``pip search`` you need to use the URL to the index itself, not it's "simple" URL. For a locally running devpi this would work like this: ``pip search -i http://localhost:3141/user/index/ ...``
You can also put this into a ``pip.conf``:
```ini
[global]
index_url = http://localhost:3141/user/index/+simple/
[search]
index = http://localhost:3141/user/index/
```

**Comment by yunfan** [comment]
@fschulze  thanks very much i had finally make it work

**Comment by johncf** [comment]
> You can also put this into a `pip.conf`:
> 
> ```ini
> [global]
> index_url = http://localhost:3141/user/index/+simple/
> ...
> ```

This is a bit unrelated... Is the best-practice for specifying index url with the final `+simple` part? It works even when I keep specify it as `http://localhost:3141/user/index`. (I have `devpi-web` installed too. Is that why it works?)

**Comment by fschulze** [comment]
@johncf  It works without ``+simple``, but it causes a redirect every time and only specific user agents are redirected, so it might not work with every tool.
