### ISSUE TITLE
allow me to set the current devpi index with an environment variable

### ISSUE THREAD

**Issue by glyph** [devpi/devpi#437]
I want the equivalent to `devpi use` which only affects the current shell, so that I can test multiple indexes side-by-side in different windows, rather than having the configuration live in files that are shared on my entire account.

I already do this with pip & twine via `PIP_INDEX_URL` and `TWINE_UPLOAD_URL` respectively; it would be nice if the devpi client command line could be configured similarly.

**Comment by fschulze** [comment]
Thanks for the suggestion. This is also a nice way to have different targets for ``devpi upload``.

**Comment by hpk42** [comment]
sounds like a good idea to add ``DEVPI_INDEX`` -- the determination order would then be

1. ``DEVPI_INDEX`` if set
2. home-dir state (current devpi use) 

and maybe while we are at it, also "0. command line option"?

**Comment by fschulze** [comment]
That could be done by allowing a full URL as index. For example ``devpi upload https://devpi.net/fschulze/dev``.
