### ISSUE TITLE
Improve instructions for devpi-web installation and related search index creation

### ISSUE THREAD

**Issue by vlcinsky** [devpi/devpi#442]
[Doc states](http://doc.devpi.net/latest/quickstart-pypimirror.html#using-pip-search) in bold, that devpi-web must be installed **"before you initially start devpi-server"**.

Being a human, I try to read quickly and my takeaway was - "Oh, with devpi-web, I have to plan in advance and later installation is possible only with export/import or other time consuming activities".

The fact is, this is not true as there is great `devpi-server --recreate-search-index` command.

I would propose following changes to documentation:
- the bold statement shall read **"ensure search index is created"**.
- recommend call to `devpi-server --recreate-search-index` for all cases. Even though freshly started server creates the index automatically, it takes some time (3 minutes 35 secs in my case) and user is likely to test pip search command and be surprised by incomplete results.

All the changes are purely in documentation but I believe, they could help creating better feeling about the solution (what counts).

**Comment by fschulze** [comment]
Unfortunately that is only half of what needs to happen. Unpacking the docs and creating html from the description isn't done by ``--recreate-search-index``.

**Comment by fschulze** [comment]
This can now be improved, because the other things devpi-web did during event handling are now done on demand.

**Comment by fschulze** [comment]
With devpi-web 4.0.0 this is obsolete.
