### ISSUE TITLE
`devpi install` fails if used against server with devpi-lockdown

### ISSUE THREAD

**Issue by vlcinsky** [devpi/devpi#443]
Following discussion in issue #331 I set up `devpi-server` with `devpi-web` and `devpi-lockdown`. Used nginx configuration as proposed on `devpi-lockdown` pages.

The aim is to have index page with basic authentication to allow (a bit) secured access to our index via pip command.

What works well:
- web page incl. login page
- devpi subcommands
  - login
  - logoff
  - index
  - list (all packages as well specific package versions)
  - upload
- pip search and pip install with --index set to url in style http://user:pswd@pypi.private.one/user/prod

What fails:
- `devpi install` command fails.

```bash
(venv)$ devpi install boto
-->  /home/javl/.pip$ /home/javl/sandbox/playwith_devpi/.tox/py36/bin/pip install -U -i http://pypi.local/javl/dev/+simple/ boto  [PIP_USE_WHEEL=1,PIP_PRE=1]
Collecting boto
  Could not find a version that satisfies the requirement boto (from versions: )
No matching distribution found for boto
command failed
```
while

``` bash
(venv)$ pip install -U -i http://user:pswd@pypi.local/javl/dev/+simple/ boto
Collecting boto
  Downloading http://pypi.local/root/pypi/+f/e97/2e30f16c1f875/boto-2.48.0-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 100.0MB/s 
Installing collected packages: boto
Successfully installed boto-2.48.0
```

The reason seems to be that `devpi install` is using `pip` with `--index` but it does not put into it username and password.

**Comment by ilya86oz** [comment]
user\pass in index-url in pip.conf works for me

```
[global]

index-url = http://<username>:<password>@<host>/<repo>/+simple/
trusted-host = <host>
```
