### ISSUE TITLE
How to remove one .whl file from a release?

### ISSUE THREAD

**Issue by wimglenn** [devpi/devpi#448]
There's a package with multiple wheels built for different architecture.  The 2.7 wheel has an issue and needs to be removed from the index.  

The `devpi remove` sub-command just accepts a single positional argument:

    positional arguments:
      spec             remove info/files for a project/version/release file from
                       the current index. Example specs: 'pytest' or
                       'pytest>=2.3.5'

Asking to remove a version number lists all the wheels:

    $ devpi remove "somepackage==1.2.3"
    About to remove the following releases and distributions
    version: 1.2.3
      - https://devpi/x/y/+f/cafef00d/somepackage-1.2.3-268-cp27-cp27mu-linux_x86_64.whl
      - https://devpi/x/y/+f/cafef00d/somepackage-1.2.3-268-cp36-cp36m-linux_x86_64.whl
    Are you sure (yes/no)?

It just prompts to remove all or none.  How to specify the 'spec' to only remove the 2.7 wheel?  It's not working to just ssh into devpi server and getting rid of the file itself; this leaves the devpi metadata all screwed up and the index views still think that the wheel exists.  

The devpi client version is 3.0.0 and the server version is 4.0.0.

**Comment by fschulze** [comment]
Unfortunately this isn't possible at the moment. There is no API endpoint in devpi-server that allows deletion of individual files. This is certainly something that should be possible though.

**Comment by wimglenn** [comment]
Hi @fschulze , thank you for the prompt response.  If this is not possible from devpi client, can you suggest a way to do it: 
- from devpi server CLI
- through a Python interpreter directly, on the machine hosting server

Alternatively, a way to cleanup the metadata after simply removing the files directly from the host?

**Comment by wimglenn** [comment]
Thanks for the answer.  You may convert this issue into a feature request, or just close it if you like.  Cheers.

**Comment by cjw296** [comment]
Workaround would be to download the one you want to keep, delete them both, then re-upload the one you wanted to keep.

**Comment by fschulze** [comment]
With devpi-server a single release can be deleted using a ``DELETE`` request on it's URL. For now one has to use ``curl`` or similar tool, which is a bit cumbersome because of authentication etc. I plan to add support for it in devpi-client.
