### ISSUE TITLE
Packages not on mirror_whitelist should not be queried on the mirror server

### ISSUE THREAD

**Issue by danielpanteleit** [devpi/devpi#451]
Today I noticed that packages that are not on mirror_whitelist are still queried on the mirror server.  At least this is the case in the web interface when accessing the package details. Not sure if this is limited to the web interface and only necessary to print the warning:

> Because this project isn't in the mirror_whitelist, no releases from root/pypi are included.

Here is a partial tracedump that occurred because pypi was not reachable:

```
  File "/usr/local/lib/python3.6/site-packages/devpi_web/views.py", line 539, in version_get
    whitelist_info = stage.get_mirror_whitelist_info(name)
  File "/usr/local/lib/python3.6/site-packages/devpi_server/model.py", line 496, in get_mirror_whitelist_info
    in_index = stage.has_project_perstage(project)
  File "/usr/local/lib/python3.6/site-packages/devpi_server/extpypi.py", line 413, in has_project_perstage
    links = self.get_simplelinks_perstage(project)
  File "/usr/local/lib/python3.6/site-packages/devpi_server/extpypi.py", line 326, in get_simplelinks_perstage
    (response.status_code, url))
devpi_server.model.UpstreamError: -1 status on GET https://pypi.python.org/simple/somepackage/
```

This was on devpi-server 4.3.0 and devpi-web 3.2.0

**Comment by fschulze** [comment]
I've also seen this. I thought I looked at it already, but either I missed another case, or I didn't make a PR yet for some reason. Thanks for reporting.

**Comment by fschulze** [comment]
It is only for the warning and I currently don't see a way this could be prevented while still keeping the warning.
