### ISSUE TITLE
Creating indices as non root user with `--restrict-mode` ?

### ISSUE THREAD

**Issue by cournape** [devpi/devpi#457]
My understanding is that to avoid any user to be able to create indices, one should use the `--restrict-mode` option for `devpi-server`. Unfortunately, this then prevents any non root (or other group/user specified in `--restrict-mode`) to create indices. I would like to be able to create arbitrary  `<org>/<repo>` indices, w/o having to harcode the set of `<org>` (aka users) into the `--restrict-mode` option. Is that possible ? Or am I using the wrong mental model for how you are supposed to user users/groups ?

**Comment by fschulze** [comment]
With plain ``devpi-server`` you indeed have to list every user which is able to create indices with ``--restrict-modify``. If you use something like [devpi-ldap](https://github.com/devpi/devpi-ldap), then you can use groups as well. Any user listed should then be able to create arbitrary other indices. They are basically admin users.

**Comment by fschulze** [comment]
No follow up for quite some time, so I assume this issue is solved.
