### ISSUE TITLE
Fresh install of depvi-server 4.3 doesn't start

### ISSUE THREAD

**Issue by jaap3** [devpi/devpi#459]
I just tried to set up a fresh install of devpi-server but was unable to start the server.

I tried this with multiple python version (Python 3.5 on CentOS, Python2.7 on OSX and Python3.4 on OSX), all with the same result

```
$ devpi-server --init --start
[...]
RuntimeError: Could not start process devpi-server
```

**Comment by fschulze** [comment]
Can you try without ``--start`` in foreground mode? With that you should see any error messages more easily. Otherwise you should find the logs somewhere in ``~/.devpi/server/``.

**Comment by RonnyPfannschmidt** [comment]
@jaap3 @fschulze there has been a regression in the new pluggy release - a downgrade of pluggy may resolve

see #458 for reference

**Comment by jaap3** [comment]
Yep, seems that's the culprit

**Comment by RonnyPfannschmidt** [comment]
reopening to make it more discoverable until the fix is released

**Comment by fschulze** [comment]
The pluggy 0.5.1 release is out and fixes this issue.
