### ISSUE TITLE
Please make a dot release

### ISSUE THREAD

**Issue by vartec** [devpi/devpi#460]
Hi,
They've been quite a lot of fixes in since April. 
Could you please make `X.X.1` release including them? 
Thanks!

**Comment by fschulze** [comment]
I have released devpi-common 3.2.0rc1, devpi-server 4.3.1rc1, devpi-web 3.2.1rc1 and devpi-client 3.1.0rc1.

**Comment by fschulze** [comment]
Final releases are out
