### ISSUE TITLE
Website Docs are Out of Date

### ISSUE THREAD

**Issue by Julian** [devpi/devpi#466]
It looks like https://devpi.net/docs/devpi/devpi/latest/+d/quickstart-server.html still documents version 4.0.

(And specifically, the quickstart instructions are missing a mention of `--init`)

**Comment by fschulze** [comment]
Thanks for the reminder. They will be updated after 4.3.1 final is released, which contains a fix required to create the documentation.

**Comment by fschulze** [comment]
The docs are now up to date.
