### ISSUE TITLE
about the index url format

### ISSUE THREAD

**Issue by blackholll** [devpi/devpi#467]
the official pip install mirror url like pypi.python.org/simple(http://xxxx.com/simple).  but mirror_url that run in devpi  like http://xxxx.com/root/pypi 。 I try to create a index by creater a user that named 'simple', the server tell me must create a index under the user, that mean the mirror_url will be 'http://xxxx.com/simple/xxx' , but not http://xxxx.com/simple. 
before I user pypiserver, the mirror_url is just like http://xxxx.com/simple. because i need  cache package,  change to devpi.  i don't want to change url( may be it's can be solved by nginx redirect）. is there any other idea?

**Comment by blackholll** [comment]
@fschulze

**Comment by fschulze** [comment]
Are you trying to mirror a devpi mirror? I'm confused be your usage of ``mirror_url``.

**Comment by blackholll** [comment]
can i change the url  "http://pypi.xxx.com/xxxx/dev/+simple/" to "http://pypi.xxx.com/simple/"

**Comment by fschulze** [comment]
Currently only with a redirect via nginx. A rewrite wouldn't work, because the URLs on the simple page are relative and would point to the wrong place.

**Comment by fschulze** [comment]
See #535 for a proposed way to get absolute links to enable this use case.

**Comment by fschulze** [comment]
Absolute URLs can now be enabled with devpi-server 4.6.0. With that your use case should be possible.
