### ISSUE TITLE
[Feature Request] Adding acl_test_upload to index configuration

### ISSUE THREAD

**Issue by lbrack** [devpi/devpi#469]
We would like to propose the introduction a new index configuration field called *acl_test_upload*. This field would be similar to *acl_upload* but would, instead, restrict the upload of test results (as opposed to release files) to an index.

To preserve backward compatibility, this field should default to *:ANONYMOUS:*. If set to a list of users, only logged in users that are members of this ACL can upload results. If the ACL is not set to *:ANONYMOUS:* and if the logged in user is not a member, test results shall be ignored by the devpi server. 

**Rationale for change**

In some cases, tests associated to a distribution require a specific test bed (e.g. peripheral equipment). Currently, even if the setup fails, such failures appear as an red exclamation mark leading other users to believe that there is a problem with the underlying code. 

This mechanism would prevent false negative from tainting indices (for instance non volatile indices, e.g. production indices) while ensuring that devpi behaves the same way as in previous releases for people who do not have this problem/constraint. 

Many thanks for your attention to this request.

Cheers/Laurent

**Comment by gotcha** [comment]
See #486

**Comment by lbrack** [comment]
Thanks a bunch.

**Comment by fschulze** [comment]
Implemented in devpi-server 4.4.0.
