### ISSUE TITLE
upload --only-docs, no project named 'name' was ever registered

### ISSUE THREAD

**Issue by jaraco** [devpi/devpi#471]
Attempting to upload docs with `devpi upload --only-docs`, I'm getting an error:

```
...
built: /app/dist/qq7-1.34.10.doc.zip [sphinx docs] 1942.496kb
400 FAIL doc_upload of qq7-1.34.10.doc.zip to https://devpi-master.my.corp/root/main/
no project named 'qq7' was ever registered
POST to https://devpi-master.my.corp/root/main/ FAILED
```

It's true, I've never registered a project.

It seems devpi doesn't have a register command. I tried using distutils' register command, but it requires additional configuration, failing with:

```
$ python3.6 setup.py register -r https://devpi-master.my.corp/root/main/
...
ValueError: https://devpi-master.my.corp/root/main/ not found in .pypirc
```

Surely there should be a way to initialize a new project for publishing docs without having to fallback to distutils.

I haven't yet tried running simply `upload`, because I don't want to actually publish the package.

**Comment by jaraco** [comment]
I thought I'd worked around the problem by performing a full upload, then removing that version. But even after doing this, subsequent `--only-docs` attempts would fail with the same error. It seems it's not possible to have docs without a published package.

**Comment by jaraco** [comment]
We haven't uploaded in a while, so the versions may be relevant.

devpi-server-4.2.1
devpi-web-3.1.1

I do recall raising this issue before, though I can't find where.

**Comment by fschulze** [comment]
The version is indeed relevant:

4.3.0 (2017-04-23)
==================

- allow upload of documentation without first registering the project or
  uploading releases.

...

Please let us know if upgrading fixes it

**Comment by fschulze** [comment]
BTW, we are eating our own dog food now:
http://doc.devpi.net
https://github.com/devpi/devpi/commit/ffcf31c6e47be97535f739441972cbaece766c55

**Comment by jaraco** [comment]
Very cool. Thanks for your help with this!
