### ISSUE TITLE
Does not appear to be possible to --import without creating root/pypi

### ISSUE THREAD

**Issue by skylerbunny** [devpi/devpi#477]
I've been banging my head against this for hours today, and I want to make sure I haven't missed anything. If not, I'd definitely call this a bug.

Suppose I already have a saved set of indexes in the directory 'dumpdir'. I move it to a new machine without access to the internet. My purpose is to bring up devpi in this isolated environment, by first importing the indexes, and then being able to start the server.

I can INIT a server with --no-root-pypi:
devpi-server --restrict-modify root --init --no-root-pypi --host 127.0.0.1 --port 3141

After creating any local indexes I wish and populating them, I can EXPORT these, and as export explains, it doesn't export mirrors. Great, that's exactly what I want:
devpi-server --export /backup/dumpdir

The problem is that I can't IMPORT with --no-root-pypi. I've tried variations of commands, and none of them seem to do what I want, which is to both:
* Create the indexes referred to in the export dump and
* NOT create a root/pypi index, which this isolated devpi instance won't ever be able to reach anyway.

Expected result:
devpi-server --no-root-pypi --serverdir SERVERDIR --import /backup/dumpdir

should cleanly: both import local indexes, and not create a root/pypi mirror, just as happens with --init.

Currently it attempts to run and then oddly gives the error "fatal: serverdir must not contain users or stages: SERVERDIR"

**Comment by fschulze** [comment]
This is a bug and I will open a PR with a fix soon.

**Comment by fschulze** [comment]
See #478

**Comment by fschulze** [comment]
Fixed with devpi-server 4.4.0.
