### ISSUE TITLE
links on doc.devpi.net are not opening correctly

### ISSUE THREAD

**Issue by hpk42** [devpi/devpi#482]
The "Mailing list" and "issue tracker" links are not opening correctly on doc.devpi.net, probably since docs was moved to being served from devpi-server itself.

**Comment by fschulze** [comment]
This is caused by embedding the docs via iframe and those links being blocked from being embedded via content security headers. I have a fix in the works.

**Comment by hpk42** [comment]
it seems that is fixed now.  thanks!
