### ISSUE TITLE
Some Devpi pages not PEP 503 compliant

### ISSUE THREAD

**Issue by skylerbunny** [devpi/devpi#494]
I know these are minor niggles, but in trying to describe to someone 'how to prove that a PyPI simple index or package URL is valid', I discovered that Devpi is, itself, not completely PEP 503 ( https://www.python.org/dev/peps/pep-0503/ ) compliant in terms of the HTML it returns for simple indexes. Among those I found:

* Simple Devpi indexes do not currently have a trailing ```</html>``` tag
* Simple indexes lead with ```<html>```, which is not valid HTML5 by the C3 validator (and by the PEP standard above); it should lead with ```<!DOCTYPE html>```
* Simple indexes should point to a package name with a trailing slash (```<a href="pip/">pip</a><br/>``` not ```<a href="pip">pip</a>```) to avoid unnecessary redirection that PEP 503 requires (see below)
* Redirection of the URL ```INDEX/+simple``` sends a user to ```INDEX/-simple```, a 404, which is presumably unintended behavior (I'd assume it's meant to redirect to ```INDEX/+simple/```?)

* Package listings *underneath* the simple index should lead with ```<!DOCTYPE html>```, not ```<html>``` as per validation above
* If directed to the URL ```.../+simple/package```, the user should be redirected to the URL ```.../+simple/package/``` as per PEP 503

Thanks for looking into these.

**Comment by fschulze** [comment]
Thanks for the summary. I wasn't aware of that pep. I will look into it and point you to the PR for review.

**Comment by fschulze** [comment]
The PEP has more things we should implement, like the exposure of ``requires_python``. We need to add that to mirror indexes as well.

**Comment by fschulze** [comment]
@skylerbunny can you take a look at #513?

**Comment by skylerbunny** [comment]
Hey there. I did a pull of the branch on #513 and put it through quick paces. Determinations made:

- All MUSTs on the PEP 503 page appear to be addressed.
- All of the cases I mentioned (which amount to the MUSTs) appear to be addressed, against a local index. The SHOULD of redirection of a non-slash-ending URL to a slash-ending-URL is addressed.

I didn't specifically check mirrors (e.g., the default mirror), though I expect if they use the same code to generate +simple in their respective indexes, they should be fine.

There are of course other SHOULDs in 503, like checksums, but I think it's safe to say devpi's simple indexes are at least made 'compliant' by this PR, and additions like checksums could be construed as a future feature request.

Nice job.
