### ISSUE TITLE
Running replica with postgres backend for devpi.net

### ISSUE THREAD

**Issue by hpk42** [devpi/devpi#498]
@gotcha: what's the status of the postgres-replication instance for devpi.net?

**Comment by gotcha** [comment]
I must admit it went off my radar.

**Comment by hpk42** [comment]
k, but you did some things -- so what is the status (even if only half-complete and roughly described)?

**Comment by gotcha** [comment]
Florian and I were stuck in Freiburg with #489. Then Florian fixed it.

Florian updated the setup that runs at https://pgrep.devpi.net/

I just updated to all latest versions, with his support.
