### ISSUE TITLE
Add option for configuration file

### ISSUE THREAD

**Issue by fschulze** [devpi/devpi#502]
Currently all settings need to be passed as options on the command line. We should add an option to use a configuration file. I suggest to look into how pip handles that, as it allows all command line options to be supplied via a config file.

We should also look into whether we should support default locations or if it exclusively works via the command line option.

There currently is some mix of state and configuration kept in ``.nodeinfo`` which must also be handled differently.

This change is needed to remove state from the filesystem to fully implement #373

**Comment by fschulze** [comment]
My thoughts so far, heavily influenced by [how pip does it](https://pip.pypa.io/en/stable/user_guide/#configuration) :

**Locations**
- first, a config file specified on the command line
- then look for user specific config, this is for supporting the on your laptop use case
- at last a site wide config

Only the selected config file will be used, no merging.
Should we warn or error if there is a user and site wide config?

**Environment variables**

Config file options can also be set via environment variables. The format will be ``DEVPI_<UPPER_LONG_NAME>`` with dashes replaced by underscores.

**Precedence**

- command line options come first
- then environment variables
- lastly the setting from the config


rfc @gotcha, @jaraco, @r2dan, @StephanErb, @hpk42

**Comment by fschulze** [comment]
Maybe ``DEVPISERVER_<UPPER_LONG_NAME>`` is better in case we want to do something similar with devpi-client at some point.

**Comment by jaraco** [comment]
This looks good. It suits our needs in a Heroku-like environment - where we could supply all parameters via environment variables... or indicate our settings.yaml file. The flexibility seems well factored.

**Comment by fschulze** [comment]
There is #573 implementing this now.
