### ISSUE TITLE
pytest_devpi_server plugin rename broke my own server runner plugin

### ISSUE THREAD

**Issue by eeaston** [devpi/devpi#505]
Hi there, I'm the maintainer of this suite of Pytest plugins: https://github.com/manahl/pytest-plugins.

One of the plugins is a fixture for running up a devpi server on a transient host and port, then tearing it down once the fixture drops out of scope. 

This commit here: https://github.com/devpi/devpi/commit/c59e3adc5c3ce3eb7803f74644a70fd56a05d776
.. now means I can't install my own plugin as you've registered under the same module name.

Looking at the code of that plugin I'm not exactly sure what it does as it seems to just define a couple command-line options.  

Could you let me know what this plugin is for, and if there is any chance you could rename it? I can't see any useable fixtures registered when installing both devpi-server and pytest and running 'py.test --fixtures'.

Thanks,
Ed

**Comment by fschulze** [comment]
It's needed to share the devpi server tests with the postgresql plugin. I could rename them with a _internal suffix if still needed since you seem to have renamed it on your side already.

**Comment by fschulze** [comment]
No reply in more than 3 weeks and the referenced commits in this ticket indicate the problem is being handled.
