### ISSUE TITLE
Confirm that crawling from PyPI is not needed anymore

### ISSUE THREAD

**Issue by gotcha** [devpi/devpi#518]
Since external links are not enabled on PyPI, we might remove the crawling code: `perform_crawling` from `extpypi.py` might be removed.

**Comment by fschulze** [comment]
See [PEP 438](https://www.python.org/dev/peps/pep-0438/) and [PEP 470](https://staging2.python.org/dev/peps/pep-0470/). I briefly looked through them, but am not sure about the current state. I found this thread, but haven't read it yet: https://mail.python.org/pipermail/distutils-sig/2015-August/026731.html

**Comment by fschulze** [comment]
https://twitter.com/EWDurbin/status/1017426216373182468

**Comment by gotcha** [comment]
AFAICS in https://mail.python.org/pipermail/distutils-sig/2015-September/026790.html

> Just so everyone knows what
to expect, my plan is to implement all of the deprecation parts while PyPI
legacy is still running and then use the final cut over to Warehouse as the
final step to actually remove it.
