### ISSUE TITLE
devpi crashes when using Accept headers, for some paths

### ISSUE THREAD

**Issue by gonvaled** [devpi/devpi#521]
Requesting from the top works, without `Accept` header:

```
$ http localhost:3141 --print h
HTTP/1.1 200 OK
Content-Length: 5834
Content-Type: text/html; charset=UTF-8
Date: Thu, 08 Mar 2018 12:28:16 GMT
Server: waitress
X-Devpi-Api-Version: 2
X-Devpi-Master-Uuid: 585f9eb156224aba896e134bf4c07e4d
X-Devpi-Serial: 281
X-Devpi-Server-Version: 4.1.1
X-Devpi-Uuid: 585f9eb156224aba896e134bf4c07e4d
```
And with `Accept` header:

```
$ http localhost:3141 Accept:"text/html" --print h
HTTP/1.1 200 OK
Content-Length: 5834
Content-Type: text/html; charset=UTF-8
Date: Thu, 08 Mar 2018 12:27:38 GMT
Server: waitress
X-Devpi-Api-Version: 2
X-Devpi-Master-Uuid: 585f9eb156224aba896e134bf4c07e4d
X-Devpi-Serial: 281
X-Devpi-Server-Version: 4.1.1
X-Devpi-Uuid: 585f9eb156224aba896e134bf4c07e4d
```

Requesting from `/root/public/` works without `Accept` header:
```
$ http localhost:3141/root/public --print h                                                                                                                          
HTTP/1.1 200 OK
Content-Length: 3200
Content-Type: application/json
Date: Thu, 08 Mar 2018 12:22:07 GMT
Server: waitress
X-Devpi-Api-Version: 2
X-Devpi-Master-Uuid: 585f9eb156224aba896e134bf4c07e4d
X-Devpi-Serial: 281
X-Devpi-Server-Version: 4.1.1
X-Devpi-Uuid: 585f9eb156224aba896e134bf4c07e4d
```

But fails with `Accept` header:
```
$ http localhost:3141/root/public Accept:"text/html" --print h                                                                                                       

http: error: ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

The server crashes and is restarted by docker (I am running devpi in a docker container). The logs do not report anything special, just a GET request, and then I see that the server restarts.

This is annoying because when browsing the UI with a web browser (Chrome), I am unable to open `/root/public` (or any other path except the top-level path), since Chrome is automatically inserting `Accept` headers.

I am running:
```
$ devpi-server --version
4.1.1
```

**Comment by fschulze** [comment]
I just checked with Safari and it also inserts Accept headers and it works without issue for me. The devpi-server version you use is pretty old, it's possible that one of the dependencies like waitress or WebOb have changed something which breaks in that old version. Also devpi-server 4.2.0 contained a security related fix, so you should try again with the current 4.4.0 release.

**Comment by fschulze** [comment]
Do you have the devpi-web plugin installed?

**Comment by gonvaled** [comment]
I am basing my docker container on this: https://github.com/muccg/docker-devpi. Which has:

https://github.com/muccg/docker-devpi/blob/master/.env

```
DOCKER_DEVPI_SERVER_VERSION=4.1.1
DOCKER_DEVPI_CLIENT_VERSION=2.7.0
DOCKER_DEVPI_WEB_VERSION=3.1.1
```

I can try to build the image from scratch, and use newer versions.

Have you been able to check with a command line tool (`http` / `curl`) with `Accept` headers?

I assume your `devpi` is not running in a container, right?

**Comment by fschulze** [comment]
I just tried with curl without issues. I have it running without containers, but I manage installations in VMs, FreeBSD jails and my OS X Laptop, though most of those have nginx in front.

**Comment by fschulze** [comment]
Have you seen https://github.com/muccg/docker-devpi/issues/11?

**Comment by gonvaled** [comment]
Interesting, thanks. Could very well be related.

**Comment by fschulze** [comment]
Any update on this?

**Comment by fschulze** [comment]
No feedback for 3 months. Feel free to reopen with more information.
