### ISSUE TITLE
devpi upload uwsgi does not contain PKGINFO, skipping

### ISSUE THREAD

**Issue by Soliangxin** [devpi/devpi#524]
An error occurred while using the command to upload the package downloaded by pypi official website
```
devpi upload --from-dir requirements
uwsgi-2.0.12.tar.gz: does not contain PKGINFO, skipping
uwsgi-2.0.13.1.tar.gz: does not contain PKGINFO, skipping
```
Ask how to solve this problem?

**Comment by RonnyPfannschmidt** [comment]
it seems that those releases of uwsgi deliberately/accidentally left out the pkg-info - its included in the most recent ones - please evaluate if updating is a option for you

**Comment by Soliangxin** [comment]
Hello, this is the version I specified when installing third-party open source software. Is there a solution to this problem?

**Comment by fschulze** [comment]
You can push from root/pypi to one of your indexes, no need to reupload:
```
devpi push --index root/pypi uwsgi==2.0.12 your/index
```

**Comment by Soliangxin** [comment]
Hello, the built devpi server is not connected to the external network in the company's internal network. What should be done in this situation?

**Comment by fschulze** [comment]
The only workaround I can think of at the moment is unpacking the source and upload from that

**Comment by petrovicboban** [comment]
We've updated some packages, and it's fine:    
```
devpi-client==4.0.1
devpi-common==3.2.1
virtualenv==15.2.0
```

**Comment by fschulze** [comment]
I wonder what is happening here. Either there is a bug in distutils, or twine is doing something different than devpi upload. The latter would explain how such wheels ended up on PyPI at all.

**Comment by di** [comment]
This is likely because the affected users have `pkginfo<1.4.2`, which cannot parse a [Metadata 2.1](https://www.python.org/dev/peps/pep-0566/) `PKG-INFO` file.

The devpi client should pin `pkginfo>=1.4.2` (currently it's `pkginfo>=1.2b1`).

Anyone experiencing this problem should be able to resolve it by doing `pip install -U pkginfo`.

**Comment by henryborchers** [comment]
Tried this and this fixed the problem for me.

**Comment by jaraco** [comment]
Confirmed - I have pkginfo 1.4.1.
