### ISSUE TITLE
Per package ACL

### ISSUE THREAD

**Issue by pierreluctg** [devpi/devpi#528]
Hi, would it be possible to some kind of per package ACL. For shared indexes I want to be able to restrict who can upload specific packages.

This would be similar to Owners and Maintainers on PyPi.python.org

**Comment by fschulze** [comment]
This is a pretty big change that has far reaching implications.

I have started another project which might solve your issue in another way:
https://github.com/fschulze/devpi-pr
Currently it only consists of the README and that isn't finished yet, but the general idea should come through already. I will soon continue working on it. You are also welcome to give feedback there if you think it might work out for you.

If the above project doesn't solve your use case, then this would either need to be implemented by you, someone else or require funding. You can contact https://merlinux.eu if you are interested in funding this feature.

**Comment by fschulze** [comment]
No plans to implement this without someone funding it.
