### ISSUE TITLE
Better authentication for "push" to external index

### ISSUE THREAD

**Issue by fschulze** [devpi/devpi#529]
Currently ``devpi push`` to an external index requires the user credentials to be sent to the devpi server. Warehouse is planning to introduce [API keys](https://github.com/pypa/warehouse/issues/994) which would allow this to be handled in a better way.

**Comment by brainwane** [comment]
We've rolled out [scoped API tokens for package upload on PyPI](https://blog.python.org/2019/07/pypi-now-supports-uploading-via-api.html). Please [test](https://wiki.python.org/psf/WarehousePackageMaintainerTesting) the beta feature and let us know what you think!

**Comment by fschulze** [comment]
I tested an "all projects" token as replacement for username/password and that worked just fine.

Once more caveats are available it will get way more interesting.

**Comment by fschulze** [comment]
Additional caveats are now added with upcoming devpi-client 6.0.0.
