### ISSUE TITLE
devpi login username not support https schema

### ISSUE THREAD

**Issue by hanbaga** [devpi/devpi#534]
devpi use https://pypi.xxx.com
devpi login root

devpi-server will receive http schema request

How to support https

**Comment by fschulze** [comment]
For https you need a reverse proxy like nginx or haproxy in front of devpi which handles the TLS encryption.

**Comment by hanbaga** [comment]
why devpi-client not support https.

**Comment by fschulze** [comment]
Devpi client supports https, but the server must be set up correctly. Does ``devpi getjson /+api`` return https URLs in it's output? If not, then you need to setup the outside URL correctly. Either using the ``X-Outside-URL`` header if you have a reverse proxy in front of devpi-server, or by using the ``--outside-url`` command line option.

**Comment by fschulze** [comment]
No more feedback in 3 months. Feel free to reopen with more information.

**Comment by fschulze** [comment]
@aquadrehz did you set the ``X-Outside-URL`` proxy header correctly? Does ``/+api`` contain the correct URLs? I'm assuming you don't actually try https on localhost, because that doesn't work. If you use a self signed certificate, you have to add it in a way the Python ``requests`` library can find it. Look for documentation on the ``REQUESTS_CA_BUNDLE`` environment variable.

**Comment by aquadrehz** [comment]
I use generated configure from 
> devpi --gen-config

which result as following. It's work in browser correctly but not trusted (Not display green lock)

```
    location @proxy_to_app {
        # For check working
        # autoindex on;
        # autoindex_exact_size off;
        proxy_pass http://localhost:3141;
        proxy_set_header X-outside-url $scheme://$host:$server_port;
        proxy_set_header X-Real-IP $remote_addr;
    }
```

Then I have hack the code as MrMontesa mention from https://github.com/devpi/devpi/issues/548
```
auth=basic_auth, cert=cert, verify='/etc/ssl/certs/ca-bundle.crt'
```
and add bash profile
```
rehash /etc/ssl/certs
export REQUESTS_CA_BUNDLE = '/etc/ssl/certs/'`
```
This allow me to login but still SSL error when
> devpi upload

Where should I check next?

**Comment by aquadrehz** [comment]
Is there any option to ignore certificate as curl?
@fschulze

**Comment by fschulze** [comment]
From ``curl --help``: ``--insecure``

I can't help much further for self signed certificates, because we don't support it and I never tried it myself.

**Comment by arobbins805** [comment]
I am having a similar issue.
Here is my configuration:

- A client computer with the REQUESTS_CA_BUNDLE env variable set to the server certificate
- An apache server with a reverse proxy on 443 using self-signed keys on <my_server_port>. Here is the reverse proxy config.
```
<VirtualHost *:443>
        <Location my_proxy_location>
                ProxyPass http://localhost:3141
                ProxyPassReverse http://localhost:3141
        </Location>
</VirtualHost>
```
- A local host devpi instance on <my_server_hostname> on port 3141
```
devpi-server:
  host: localhost
  port: 3141
  outside-url: https://<my_server_hostname>/<my_proxy_location>
```
With both of these running, devpi use does the following:
`#> devpi use https://<my_server_hostname>/<my_proxy_location> --client-cert=<my_client_cert> -l`

```
Using existing client cert for 'https://<my_server_hostname>/<my_proxy_location>'.
root/pypi       bases=                volatile=False
```
When I attempt to login, devpi login does the following:
`#> devpi login root`

```
password for user root:
SSL verification failed 'https://<my_server_hostname>/<my_proxy_location>/+login':
HTTPSConnectionPool(host='<my_server_hostname>', port=443): Max retries exceeded with url: /devpi/+login (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')],)",),))
```

Has anyone gotten self-signed certs to work with the login command?

**Comment by fschulze** [comment]
Personally I just use letsencrypt to get a certificate and use /etc/hosts and/or DNS to point to localhost or my internal server which isn't accessible from the outside in any way. This is working well for 2 years now. I use [certsling](https://pypi.org/project/certsling/) to do the certificate stuff locally. Self signed certificates are just too painful.

**Comment by arobbins805** [comment]
I did some more digging. Here is what I found:
From my previous comment,
If you use,
`REQUEST_CA_BUNDLE=<path_to_server_cert> devpi use https://<my_server_hostname>/<my_proxy_location> --client-cert=<my_client_cert> -l`

devpi will return:
```
Using existing client cert for 'https://<my_server_hostname>/<my_proxy_location>'.
root/pypi       bases=                volatile=False
```
This is correct and the self-signed certs work.
In addition to listing the indexs, devpi also saves the following configuration to the file: ~/.devpi/client/current.json

```
{
    "client_cert": {
        'https://<my_server_hostname>:443/<my_proxy_location>/': <my_client_cert>
    },
    "features": [
        "server-keyvalue-parsing"
    ],
    "login": 'https://<my_server_hostname>/<my_proxy_location>/+login'
}
```

Now that the server is cached, you can attempt to login:
`REQUEST_CA_BUNDLE=<path_to_server_cert> devpi login root --password ''`

This fails as described above with:
```
SSL verification failed 'https://<my_server_hostname>/<my_proxy_location>/+login':
HTTPSConnectionPool(host='<my_server_hostname>', port=443): Max retries exceeded with url: /devpi/+login (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')],)",),))
```

If you debug the requests and responses, you will find that login uses the url: https://<my_server_hostname>/<my_proxy_location>/+login
Similarly,

`REQUEST_CA_BUNDLE=<path_to_server_cert> devpi index -l`

will use the url: 
`https://<my_server_hostname>/<my_proxy_location>/root`

If you read the code, that accesses the client_cert, from the current.json file, you will notice that the url is used to lookup the client_cert value. In the cases of these two commands, the url is different from the url that was saved when 'devpi use. 

There is one more thing to note, the urls are processed using the method: _get_normalized_url. This method (devpi_client::use.py::Current) will add the port to the url.

All of this implies that if you add the key, value pair to the client_cert dictionary for the url that you are trying to access, the client_cert will be picked up. Here is an example:

```
{
    "client_cert": {
        'https://<my_server_hostname>:443/<my_proxy_location>/': <my_client_cert>,
        'https://<my_server_hostname>:443/<my_proxy_location>/+login': <my_client_cert>
    },
    "features": [
        "server-keyvalue-parsing"
    ],
    "login": 'https://<my_server_hostname>/<my_proxy_location>/+login'
}
```
Now, trying the login again:

`#>REQUEST_CA_BUNDLE=<path_to_server_cert>  devpi login root --password ''`

returns 

`logged in 'root' at None, credentials valid for 10.00 hours`

For the command,

`REQUEST_CA_BUNDLE=<path_to_server_cert> devpi index -l`

add this key, value pair to the client_cert dictionary, with your username where 'root' is

`'https://<my_server_hostname>:443/<my_proxy_location>/root': <my_client_cert>`

Hope this helps for anyone looking for a workaround.

-Andrew

**Comment by fschulze** [comment]
Check the output of ``https://<my_server_hostname>/<my_proxy_location>/+api``. If the URLs in there don't match your hostname, then the ``X-Outside-Url`` header in your proxy configuration is wrong.

**Comment by fschulze** [comment]
@kierun Is your SSL certificate working properly for your devpi domain? Self signed certificates are basically unsupported, because requests uses its own certificate store.

**Comment by kierun** [comment]
Yes, *error between floor and keyboard*

`REQUESTS_CA_BUNDLE` should be the authority certificate, not the hostname's… 

Sorry to waste your time.

/me gets a dunce hat and goes a sit in the corner.
