### ISSUE TITLE
devpi-server no arguments --recreate-search-index with python34

### ISSUE THREAD

**Issue by hanbaga** [devpi/devpi#538]
devpi-server --recreate-search-index
usage: devpi-server [-h] [--host HOST] [--port PORT] [--threads THREADS]
                    [--outside-url URL] [--debug] [--profile-requests NUM]
                    [--logger-cfg LOGGER_CFG] [--mirror-cache-expiry SECS]
                    [--replica-max-retries NUM] [--offline-mode]
                    [--no-root-pypi] [--version]
                    [--role {master,replica,standalone,auto}]
                    [--master-url MASTER_URL] [--replica-cert pem_file]
                    [--gen-config] [--secretfile path] [--requests-only]
                    [--passwd USER] [--serverdir DIR] [--init]
                    [--restrict-modify SPEC] [--keyfs-cache-size NUM]
                    [--storage NAME] [--export PATH] [--hard-links]
                    [--import PATH] [--no-events] [--start] [--stop]
                    [--status] [--log]
devpi-server: error: unrecognized arguments: --recreate-search-index

**Comment by hanbaga** [comment]
@fschulze  can u help me to check the issue.   or what can I do will improve searching performance.

**Comment by fschulze** [comment]
What search performance issues do you have? Did you install devpi-web? It's required for the search and the command line option comes from it. The option is rarely needed though.

**Comment by hanbaga** [comment]
it is work through installing devpi-web
