### ISSUE TITLE
Can I upload already built sphinx documentation located in a specific directory

### ISSUE THREAD

**Issue by henryborchers** [devpi/devpi#546]
I have docs that are already generated as part of a CI step. I cannot figure out how I can add them to my existing DevPi repo.

The following command creates new docs but doesn't include any of the autodocs for my c-extensions. 

    devpi upload --only-docs

However, if I build the project myself and then use the python build directory to generate the Sphinx docs, I get the complete docs with my C-Extensions .

However, if I use the following command, the documentation is not found.

    devpi upload --only-docs --from-dir ../dist

Oddly enough, if there is a .whl file this dist directory, it is uploaded even if I have the --only-docs flag.

Any idea what I'm doing wrong?

**Comment by fschulze** [comment]
Try ``devpi upload ../dist/pkg...-doc.zip`` to upload the zip file directly, it will be associated with the latest uploaded version. With ``--version`` you should be able to specify the version explicitly.

That the whl file is uploaded sounds like a bug.

**Comment by henryborchers** [comment]
D'oh! My mistake! It wasn't working for me because I had it as ./dist/pkg...-docs.zip instead of ./dist/pkg...-doc.zip.

Sorry about that.

**Comment by jaraco** [comment]
When I try to do this (with or without `--only-docs`), I get an error: 

```
release runtests: commands[3] | devpi upload --only-docs dist/docs.zip
docs.zip: does not contain PKGINFO, skipping
```

Does the file have to have a certain name?
