### ISSUE TITLE
InsecureRequestWarning Error when using devpi use

### ISSUE THREAD

**Issue by MrMontesa** [devpi/devpi#548]
Hey specialists,
I have a small problem using devpi since I added an SSL cert to the default webpage. Devpi server is running as a vhost on the same IP so I have tested SNI (Server Name identification).
`openssl s_client --connect devpi.domain.com:443` fails but 
`openssl s_client --connect devpi.domain.com:443 -servername devpi.domain.com ` works nicely. Also the Root cert for the SSL is properly installed in /etc/ssl/certs/ca-bundle.crt on my CentOS 7.5 server. All browsers do have green EV (enhanced validation) bar, So I'm quite sure that my webserver is running fine.

This is how I tested devpi-client:

```
sebastian@server~# python -m venv ~/.envs/devpi
sebastian@server~# ~/.envs/devpi/bin/python -V
Python 3.6.3
sebastian@server~# ~/.envs/devpi/bin/pip install devpi-client
...
Installing collected packages: pkginfo, idna, urllib3, certifi, chardet, requests, py, devpi-common, pluggy, virtualenv, six, tox, check-manifest, devpi-client
Successfully installed certifi-2018.4.16 chardet-3.0.4 check-manifest-0.37 devpi-client-4.0.2 devpi-common-3.2.3 idna-2.6 pkginfo-1.4.2 pluggy-0.6.0 py-1.5.3 requests-2.18.4 six-1.11.0 tox-3.0.0 urllib3-1.22 virtualenv-16.0.0
sebastian@server~# ~/.envs/devpi/bin/devpi --version
devpi-client 4.0.2
sebastian@server~# ~/.envs/devpi/bin/devpi use https://devpi.domain.com
/home/sebastian/.envs/devpi/lib64/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Warning: https certificate validation failed (self signed?), trusted-host will be set for pip
using server: https://devpi.domain.com/ (not logged in)
no current index: type 'devpi use -l' to discover indices
/home/sebastian/.pip/pip.conf: no config file exists
~/.pydistutils.cfg     : no config file exists
~/.buildout/default.cfg: no config file exists
always-set-cfg: no
```

Any idea on how to get this solves would be appreciated. In case I'm missing some information, please let me know.
Thanks much for your help

**Comment by fschulze** [comment]
Is it actually a self signed certificate? I haven't used a self signed cert for quite a while, but my guess is that you would also get issues with pip. I doubt there is an easy way to get rid of the warning.

If it is not self signed, is the certificate chain correct? If the domain is accessible from the outside, I would use https://www.ssllabs.com/ssltest/ to check it.

**Comment by fschulze** [comment]
Recent 2.7 releases and I think everything since Python 3.4 is SNI aware. We use ``requests``, as does pip. You should check the requests docs, as far as I remember it has some info on self signed certificates etc.

**Comment by MrMontesa** [comment]
Thanks for pointing that out. I did some research and found the [verify option](http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification) for requests.
After digging a bit through devpi code, I found the place where the SSL verification was made. A dirty hack in adding the absolute path to my certs

```
[sebastian@server devpi]$ diff main.py main.py.bac
129c129
<                                   auth=basic_auth, cert=cert, verify='/etc/ssl/certs/ca-bundle.crt')
---
>                                   auth=basic_auth, cert=cert, verify=verify)
```
made it working and I was able to connect to my devpi installation from CLI.

I know, hacking the source this way is really bad. I guess the `verify=verify` can be configured, right? Some advice on this would be highly appreciated!
Thanks much

**Comment by fschulze** [comment]
Just wanted to write about ``REQUESTS_CA_BUNDLE``. I'd say that is the best solution in your case, unless there is a way to add your cert to the global CA bundle.
Can this ticket be closed?

**Comment by MrMontesa** [comment]
This is my global CA bundle :-)
```
[sebastian.@server ~]$ grep -c 'BEGIN CERTIFICATE' /etc/ssl/certs/ca-bundle.crt
156
```
Thats why I'm wondering it didn't work out of the box.
At least I have a working solution so this ticket can be closed. Thanks for your help.
