### ISSUE TITLE
devpi test exits with an error when acl_toxresult_upload is not ANONYMOUS

### ISSUE THREAD

**Issue by lbrack** [devpi/devpi#555]
When an index has its ``acl_toxresult_upload`` (#469) configuration field set to anything but :ANONYMOUS: and you run tests with devpi test, the command fails even though all tests were successful because the server returns 403 when the client attempts to upload test results. 

While this is okay when running interactively, it is a problem in a CI environment for obvious reasons. 
While the first thing that comes to mind is to simply not return an error in that particular case, this could hide genuine problems. 

Just to bring more clarity, we use pytest in python projects to test systems which are external to those projects, and the same distribution can be used for long periods of time leading to a large and useless accumulation of tox results, bogging down our devpi server. 

So an option to disable the tox result uploads or to instruct the devpi client to ignore the 403 error (and issue a simple warning) would be much welcome. 

Many thanks for the outstanding work by the way. 

**Environment Information:**

> devpi-client 4.0.2
> devpi-findlinks 2.0.0
> devpi-server 4.4.0
> devpi-web 3.2.2

Below is an example

```
  py35-dev: commands succeeded
  py36-dev: commands succeeded
  py27-dev: commands succeeded
  congratulations :)
wrote json report at: /var/folders/rt/s5hlby7n69v1kvng23px5kdw0000gn/T/devpi-test0/targz/toxreport.json
posting tox result data to https://devpi-us.dolby.net/lpbrac/gti-wallet/+f/760/d5b54685ca688/gti-mmi-0.1.dev194+g14bce0f.d20180619.tar.gz
POST https://devpi-us.dolby.net/lpbrac/gti-wallet/+f/760/d5b54685ca688/gti-mmi-0.1.dev194+g14bce0f.d20180619.tar.gz
403 Forbidden: Access was denied to this resource.
Unauthorized: PyPIView failed permission check
$ echo $?
1
```

**Comment by fschulze** [comment]
Since 2.7.0 devpi-client has the ``--no-upload`` option, is that enough?

Another solution would be separate exit codes for various error cases, so the CI could react differently.

**Comment by lbrack** [comment]
That is perfect. Thank you. I should have payed more attention to the help. Sorry about making noise for nothing.
