### ISSUE TITLE
devpi client should allow deletion of a specific file

### ISSUE THREAD

**Issue by gotcha** [devpi/devpi#579]
> With devpi-server 4.6.0 a single release can be deleted using a DELETE request on it's URL. For now one has to use curl or similar tool, which is a bit cumbersome because of authentication etc. I plan to add support for it in devpi-client.

https://github.com/devpi/devpi/issues/448#issuecomment-404763560
https://github.com/devpi/devpi/issues/446#issuecomment-404763756

**Comment by fschulze** [comment]
Implemented in client 4.1.0 with server 4.6.0.
