### ISSUE TITLE
Bug: Seriously inefficient byte concatenation hindering and breaking streamed downloads

### ISSUE THREAD

**Issue by DomHudson** [devpi/devpi#598]
## Summary

I am experiencing issues pulling large packages from my root/pypi mirror. The downloads start fast but progressively get slower over time. Eventually the download will become very very slow and never complete. The issue is most prevalent to me with the Tensorflow package where the wheel is large - approximately 60MB.

## The cause

I have investigated this issue and believe it is caused by inefficient byte concatenation in [`filestore.iter_cache_remote_file`](https://github.com/devpi/devpi/blob/master/server/devpi_server/filestore.py#L298)

Repeatedly concatenating these byte-strings is triggering excessive garbage collection or memory reallocation.

The following is a working example of this, this code is extracted from `devpi_common.request` and `devpi_server.filestore`. 

The original code gets progressively slower as it loops to around iteration 3971 before becoming unresponsive. This takes approximately 40 seconds on my machine.

The fixed code runs at a linear speed and completes the entire download (6148 iterations) in 9 seconds.

## Original code
This code is almost identical to what is currently in devpi. I just extracted it to prove the problem.
```python
import sys
from requests import Session
from requests.adapters import HTTPAdapter
from requests.exceptions import ConnectionError, RequestException, BaseHTTPError, SSLError

class RetrySession(Session):
    def __init__(self, max_retries):
        super(RetrySession, self).__init__()
        if max_retries is not None:
            self.mount('https://', HTTPAdapter(max_retries=max_retries))
            self.mount('http://', HTTPAdapter(max_retries=max_retries))

def new_requests_session(agent=None, max_retries=None):
    if agent is None:
        agent = "devpi"
    else:
        agent = "devpi-%s/%s" % agent
    agent += " (py%s; %s)" % (sys.version.split()[0], sys.platform)
    session = RetrySession(max_retries)
    session.headers["user-agent"] = agent
    session.ConnectionError = ConnectionError
    session.RequestException = RequestException
    session.Errors = (RequestException, BaseHTTPError)
    session.SSLError = SSLError
    return session

session = new_requests_session()

URL = 'https://files.pythonhosted.org/packages/ce/d5/38cd4543401708e64c9ee6afa664b936860f4630dd93a49ab863f9998cd2/tensorflow-1.11.0-cp36-cp36m-manylinux1_x86_64.whl'

r = session.get(
    URL,
    stream = True,
    allow_redirects = True,
    timeout = 5
)

content = b''
i = 0
while 1:
    data = r.raw.read(10240)
    print('Iteration %s' % i)
    i += 1
    if not data:
        break
    content = content + data

print('Done')
```

## Fixed code
The fixed code assigns the byte-strings to an array before joining them at the end.
```python
contents = []
i = 0
while 1:
    print('Iteration %s' % i)
    i += 1
    data = r.raw.read(10240)
    if not data:
        break
    contents.append(data)

content = b''.join(contents)

print('Done')
```

**Comment by fschulze** [comment]
Thanks for looking into this. I was under the impression that string concatenation speed was equal to the append/join version since Python 2.7, but one should always benchmark such assumptions, which I didn't.

**Comment by DomHudson** [comment]
Fixed by https://github.com/devpi/devpi/pull/599

**Comment by DriverX** [comment]
Thanks for this!
