### ISSUE TITLE
Uploading a new package via twine fails

### ISSUE THREAD

**Issue by rhelms** [devpi/devpi#605]
I'm not sure if devpi is supposed to support uploads via twine, but I've seen plenty of examples around using `twine upload`, and it seems to be the most convenient method, considering the automation I'm trying to achieve.

I'm attempting to push a built package from a Jenkins pipline, but I'm getting the following error.

```
HTTPError: 400 Client Error: no project named '****-jwt' was ever registered for url: http://<host>:3141/****/stable/
```
I'm using twine instead of devpi because I have to run the command via pipenv in my Jenkins pipeline, and can specify the username and password via environment variables. devpi doesn't seem to have a single line option, and requires a login, a use and then an upload command to get the job done. 
I'm also aware that devpi has options to run builds via Jenkins, but I'd rather control the build first, and push into devpi at this point.

Looking at the source code, it would appear that twine is launching straight into a file_upload with the command I'm using.
```
sh '$HOME/.local/bin/pipenv run twine upload --verbose --repository-url http://<host>:3141/otw/stable/ dist/*'
```
And the error occurs because it (the stage) doesn't know about the normalized project.

This is the full output from the Jenkins log:
```
+ /var/jenkins_home/.local/bin/pipenv run twine upload --verbose --repository-url http://<host>:3141/****/stable/ dist/****_jwt-20181025-py2.py3-none-any.whl dist/****_jwt-20181025.tar.gz

Uploading distributions to http://<host>:3141/****/stable/
Uploading ****_jwt-20181025-py2.py3-none-any.whl

  0%|          | 0.00/8.92k [00:00<?, ?B/s]
100%|██████████| 8.92k/8.92k [00:00<00:00, 143kB/s]
Content received from server:
<html>
 <head>
  <title>400 no project named '****-jwt' was ever registered</title>
 </head>
 <body>
  <h1>400 no project named '****-jwt' was ever registered</h1>
  <br/><br/>



 </body>
</html>
HTTPError: 400 Client Error: no project named '****-jwt' was ever registered for url: http://<host>:3141/****/stable/
```

At first I thought I might have a mismatch between my package name in setup.py and something else, but apparently the name gets normalized, and the underscore in my setup.py gets replaced with a dash.

Next, I saw somewhere that twine shouldn't need to explicitly register with PyPI, and thought devpi might allow the same thing, considering none of the examples I saw mentioned it.

As a part of my own troubleshooting, I'm going to try an explicity registration via twine first, and see if that does the trick. If it doesn't, I'll also have a harder look for a devpi one liner that will allow me to upload a distribution.

**Comment by rhelms** [comment]
Registering with the *.tar.gz did the trick, and devpi didn't seem to have an issue with repeated register commands.

That's functionality enough to satisfy me, so I'll close this issue. 

However, if you wanted to reopen or create new issues to add the ability to register and upload a package (or wheel) as an all-in-one operation, that would be swell.

**Comment by fschulze** [comment]
What do you mean with "Registering with the *.tar.gz did the trick"? I thought twine doesn't support registering at all anymore.

I was thinking for quite a while now about supporting uploads without registering, but am a bit uneasy about the repercussions on expected usage. Now I'm thinking about allowing it on volatile indexes and require registration on non-volatile indexes.

In general I'd like to move towards promoting usage of standard tools like twine for devpi and make devpi client less and less needed. We are also thinking about adding login and some admin pages to devpi-web.

**Comment by rhelms** [comment]
Twine still has a register function. It's Warehouse that is used by PyPI that no longer requires registering from twine.
Apparently devpi does require a registration, so before doing my twine upload, I did a twine register dist/*.tar.gz to ensure the sdist was uploaded for registration. This was then followed by a twine upload dist/* that uploaded the sdist and wheel packages.
I guess the trick with not requiring registration is being able to process the sdist (unless that same information is available in a wheel) before any wheel packages for a new package. That might mean uploading all the files, and then finding the sdist to do the automatic registration, and then perform normal upload actions. I must admit, I've never processed an upload with Python before, but I'm guessing it's much the same as PHP, where all the uploads are completed before the actual view is run, and you can look at what files were actually uploaded.

**Comment by jaraco** [comment]
I ran into this issue today also.

```
release runtests: commands[2] | python -m twine upload 'dist/*'
Uploading distributions to https://devpi.yougov.net/root/yg/
Uploading yg.traffic-1.0-py2.py3-none-any.whl

  0%|          | 0.00/7.26k [00:00<?, ?B/s]
100%|██████████| 7.26k/7.26k [00:01<00:00, 7.01kB/s]HTTPError: 400 Client Error: no project named 'yg.traffic' was ever registered for url: https://devpi.yougov.net/root/yg/
```

I suggest this issue be re-opened. Since devpi doesn't require a separate 'register' step and PyPI doesn't require a separate register step, devpi should probably do the same.
