### ISSUE TITLE
how to mirror PYPI public server?

### ISSUE THREAD

**Issue by GreatBahram** [devpi/devpi#611]
Hi
I want to mirror pypi server but not all of the packges, I just want some of them, is there any whitelist plugin for that?
Can I have both public caching mechanism and private pypi repository at the same time? how?
Should I use cheese shop source for my internal pypi?

Thanks

**Comment by fschulze** [comment]
A whitelist isn't possible at the moment.

You can create an index and add ``root/pypi`` in it's ``bases`` option. There you can upload your private packages. That's all described in the documentation at http://docs.devpi.net

**Comment by GreatBahram** [comment]
Thanks
