### ISSUE TITLE
How do I mirror pypi completely with devpi?

### ISSUE THREAD

**Issue by GreatBahram** [devpi/devpi#613]
Hi,
How do I mirror pypi completely I mean I don't want to just cache it.
Does `devpi` can do this? Second solution is to first mirror the pypi with `bandersnatch` and then run `devpi` on that? is there any better solution?

Thanks

**Comment by fschulze** [comment]
Devpi doesn't support that. I'd say ``bandersnatch`` is the correct solution for that and then add a mirror index in devpi that points to it.

**Comment by GreatBahram** [comment]
Thanks
