### ISSUE TITLE
unknown hook 'devpiserver_hookimpl' on updating devpi-web to 3.4.0, 3.4.1 or 3.5.0

### ISSUE THREAD

**Issue by prupert** [devpi/devpi#614]
We encountered the following error when running `devpi-server` after updating the `devpi-web`  package to 3.4.0, 3.4.1 or 3.5.0. It seems to be working when using devpi-web==3.3.0.

```
Traceback (most recent call last):
File "/home/devpi/venv/bin/devpi-server", line 11, in <module>
sys.exit(main())
File "/home/devpi/venv/lib/python3.5/site-packages/devpi_server/main.py", line 54, in main
pluginmanager = get_pluginmanager()
File "/home/devpi/venv/lib/python3.5/site-packages/devpi_server/config.py", line 35, in get_pluginmanager
pm.check_pending()
File "/home/devpi/venv/lib/python3.5/site-packages/pluggy.py", line 498, in check_pending
(name, hookimpl.plugin))
pluggy.PluginValidationError: unknown hook 'devpiserver_hookimpl' in plugin <module 'devpi_web.main' from '/home/devpi/venv/lib/python3.5/site-packages/devpi_web/main.py'>
```

**Comment by fschulze** [comment]
What is your devpi-server version? The oldest devpi-server version we test with devpi-web is 4.2.1 from 2016-12-22.

**Comment by prupert** [comment]
We started with devpi-server 4.6.0 and devpi-web 3.3.0, and wanted to update to the latest devpi-server 4.8.0 and devpi-web 3.5.0. We saw the error regardless of devpi-server version. We also tried 4.7.1.

**Comment by fschulze** [comment]
I don't see how this can happen with a regular installation or update. Could you please try it with a fresh virtualenv and a copy of your server state instead of trying to update the virtualenv?

**Comment by fschulze** [comment]
No reply in 3 months, feel free to reopen with more info.
