### ISSUE TITLE
How to list cached packages?

### ISSUE THREAD

**Issue by GreatBahram** [devpi/devpi#616]
I ran these instructions [link](https://devpi.net/docs/devpi/devpi/stable/+doc/quickstart-pypimirror.html) (your simple quick-start) and then I created another indices that inherited from `root/pypi` and after that I installed some packages on that via `devpi install` command ( no to mention that I ran `dev use new_index` before installing anything).
Now I want to list cached packages in this index? I've tried `devpi list` but it shows nothing empty output and `devpi install -l` shows the `pip freeze` result.
Output of `devpi list`:
```bash
(devpi) user:~/ $ devpi list                                                                                                                                         
(devpi) user:~/ $
```
Output of `devpi getjson http://localhost:3141/root`
```bash
{
    "result": {
        "indexes": {
            "pypi": {
                "mirror_url": "https://pypi.org/simple/",
                "mirror_web_url_fmt": "https://pypi.org/project/{name}/",
                "title": "PyPI",
                "type": "mirror",
                "volatile": false
            },
            "second": {
                "acl_toxresult_upload": [
                    ":ANONYMOUS:"
                ],
                "acl_upload": [
                    "root"
                ],
                "bases": [
                    "root/pypi"
                ],
                "mirror_whitelist": [],
                "pypi_whitelist": [],
                "type": "stage",
                "volatile": true
            }
        },
        "username": "root"
    },
    "type": "userconfig"
}

```
Any suggestions?

**Comment by fschulze** [comment]
Currently that is only possible after you restart devpi-server in offline mode.

What do you need the list for?

**Comment by GreatBahram** [comment]
I want to show to user a list of current cached packages. that does not make sense to make offline only for showing the list, does it?
I was wonder is there any way to check the mirror url? for example if user entered `https://google.com` before adding the index, show suitable error message? something like `--test-url` ?

**Comment by fschulze** [comment]
> I want to show users a list of current cached packages.

But why? Adding a feature always adds maintenance cost. The information is available internally, but exposing it isn't trivial.

Same for ``--test-url``. I'm not sure how it should be tested. The mirror can be a static view of the filesystem. There is nothing we can check that holds true for all use cases. Since adding a mirror is a fairly advanced use case, I think the users should know what they do. The URL can be fixed easily anyway.

If the private index inherits the mirror via ``bases``, then it's already one URL. You can also add a third index which has the mirror and the private index as ``bases``.

**Comment by GreatBahram** [comment]
Just for my curiosity, when I installed something and I searched devpi storage directory there was only the latest version in that directory, but when I tried to remove that package with `devpi remove` it shows all different version of that package. 
* firstly, where does `devpi` save other versions?
```bash
 ➜ pwd
/home/bahram/.devpi/server/+files/root/pypi
 ➜ find . -type f | grep tinydb
./+f/a2a/bc4a478ec23ff/tinydb-3.12.1-py2.py3-none-any.whl
./+f/e72/d38eebd4f5a1a/tinydb-3.0.0.zip
```
* Secondly, how can devpi download all of these packages I mean the packages and their dependencies very fast?

**Comment by fschulze** [comment]
For the other versions only the necessary info to present it to pip and to download it on request is stored in the database. Only when a package is actually downloaded will it be fetched from pypi and stored on disk. The package metadata is downloaded and stored when it's requested, for example when pip accesses it's simple page.

The term mirror isn't correct here, it behaves more like a cache, but without automatic eviction and cleanup.

**Comment by GreatBahram** [comment]
Yeah, you're right I got that.
