### ISSUE TITLE
Package name clash: always use the local one!

### ISSUE THREAD

**Issue by kierun** [devpi/devpi#624]
I have a devpi server set up to have a local repository which inherits from the main PyPI one. I have a local package called `mead` which clashes with one in PyPI. I assumed that if the local index has the mead package, then I would not need to worry about the PyPI one. 

Running search, this is fine:

```
; pip search mead                           
mead            - [root/public] My crazy package.
nelder-mead     - [root/pypi]
neldermead      - [root/pypi]
```

However, running pip install gives me the *wrong package*:

```
; pip install mead                          
Collecting mead
  Downloading http://devpi.example.org/root/pypi/+f/978/98e728d01b4d3/mead-0.0.11.tar.gz
Collecting redis (from mead)
```

Pinning to a version I know I have *in my local repository* gets me the *right package*:

```
; pip install mead==0.4.0.dev2
Collecting mead==0.4.0.dev2
  Downloading http://devpi.example.org/root/public/+f/492/f6301e2c5305f/mead-0.4.0.dev2.tar.gz (156kB)
    100% |████████████████████████████████| 159kB 26.9MB/s 
```

Apart from renaming my package -- which sounds really stupid and brittle as a solution -- is there a way to set `devpi` so that it ignore modules if they are present in the local index?

Is there a black list I can add to an index?

**Comment by fschulze** [comment]
The ``mirror_whitelist`` setting of an index is for that. It's default value ensures the behaviour you want. Did you change that setting to ``*``? https://devpi.net/docs/devpi/devpi/stable/+d/userman/devpi_indices.html#modifying-the-mirror-whitelist

**Comment by kierun** [comment]
I tried `devpi index /root/public mirror_whitelist=mead` but I am still getting the PyPI versions… Am I missing something?

How do I get it back to the default value?

**Comment by kierun** [comment]
Right… Now that I actually learned how to read⸮ I can see my error. The default value was over ridden via the docker file configuration I used.

Is there a way to get back to the default value or is it re-install time?

**Comment by fschulze** [comment]
The default is empty. ``devpi index mirror_whitelist=`` should do it.

**Comment by kierun** [comment]
@fschulze Thank you so much for your help. That worked fine.
