### ISSUE TITLE
Remove requirement for "register" call

### ISSUE THREAD

**Issue by fschulze** [devpi/devpi#625]
I was thinking about removing the requirement to register for a while now.

It was brought up again in #605 

My biggest concern was typos in package name, but that seems irrelevant now that I thought about it more. The likelihood of having a typo is at the start of a package. The registration step doesn't solve that.

The other concern was accidental uploads of a package to the wrong index. Here the registration step helps, because you get an error if the package wasn't uploaded before.

It's relatively easy to clean up an accidental upload in a volatile index, so this shouldn't be a blocker either.

The only question I still have is:
Should we still require it for non volatile indices, because it's (much) harder to clean them up?
Any input on that question is appreciated. cc @r2dan, @jaraco, @StephanErb, @hpk42, @rhelms

**Comment by jaraco** [comment]
I'm not sure requiring registration helps much either if clients like devpi automatically register... you could still accidentally upload to the wrong index. More importantly, the worlds most prominent non-volatile index, PyPI, doesn't require pre-registration. I think if there's a use-case to protect against new projects, that protection should be a special feature of devpi that's not managed through the tool chains (twine, devpi-client), but instead is a feature exposed through the web/UI, something like "disallow new packages" along with an API/UI to "add/authorize a package". With this feature, even devpi-client wouldn't be able to silently create a project, it would be an explicit step required when this feature es enabled. Is that feature needed? I don't know, but not for our use cases.

**Comment by StephanErb** [comment]
I am fine with dropping the register requirement. I don' see any real issue that is solved by it right now.

**Comment by rhelms** [comment]
I'm fine with dropping the register requirement. In our flow, uploads to the non-volatile index are done by Jenkins, so if we haven't noticed that the name is wrong by then, we deserve what's coming to us.
