### ISSUE TITLE
Fresh install of depvi-server 4.8.0 doesn't start

### ISSUE THREAD

**Issue by pradeeps** [devpi/devpi#629]
Hi,
This is my install 
devpi-server-4.8.0
devpi-web-3.5.0

I've installed these in virtualenv with python 3.7.2 on windows 10

This is the error message when I try to start devpi server:

> 
> C:\Users\pradeepsusarla\Desktop\devpi\devpi_env\Scripts\devpi-server --port 3141 --host=0.0.0.0
> process 'devpi-server' started pid=572
> Traceback (most recent call last):
>   File "c:\program files (x86)\python37-32\Lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\program files (x86)\python37-32\Lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\pradeepsusarla\Desktop\devpi\devpi_env\Scripts\devpi-server.exe\__main__.py", line 9, in <module>
>   File "c:\users\pradeepsusarla\desktop\devpi\devpi_env\lib\site-packages\devpi_server\main.py", line 56, in main
>     return _main(pluginmanager, argv=argv)
>   File "c:\users\pradeepsusarla\desktop\devpi\devpi_env\lib\site-packages\devpi_server\main.py", line 105, in _main
>     return bgserver.start(args, argv[1:])
>   File "c:\users\pradeepsusarla\desktop\devpi\devpi_env\lib\site-packages\devpi_server\bgserver.py", line 78, in start
>     self.xproc.ensure("devpi-server", prepare_devpiserver)
>   File "c:\users\pradeepsusarla\desktop\devpi\devpi_env\lib\site-packages\devpi_server\vendor\xprocess.py", line 171, in ensure
>     raise RuntimeError("Could not start process %s" % name)
> RuntimeError: Could not start process devpi-server

But I can access devpi at the above address anyway. But this error is not supposed to happen. 

Any ideas?

**Comment by fschulze** [comment]
You seem to be using the ``--start`` option. Try without to run in the foreground. The custom process management isn't very good and we started to discourage it's use. Unfortunately we haven't written the documentation for alternatives on various operating systems.

**Comment by fschulze** [comment]
The upcoming devpi-server 5.0.0 will have more examples with the ``--gen-config`` option and slightly better docs.
