### ISSUE TITLE
devpi-test should not report tests results when Interpreter is not found

### ISSUE THREAD

**Issue by r2dan** [devpi/devpi#632]
When running `devpi test` on machine where only one version of Python interpreter is installed and tox is configured to run on multiple Python interpreter versions and skip_missing_interpreters flag is set to true, devpi test uploads the test results even if the interpreter was not available on machine and devpi web displays the test as passed on version.pt page, which might be misleading, as in example below:
![image](https://user-images.githubusercontent.com/26278998/53632964-8207b100-3c16-11e9-9303-97b4ad3899d9.png)

User can check what really happened when checking detailed view (toxresults.pt):
![image](https://user-images.githubusercontent.com/26278998/53633066-bd09e480-3c16-11e9-8652-eb373f7ecb28.png)

IMHO it wouldn't be better to somehow change the devpi-client behaviour to not upload such test results.

**Comment by fschulze** [comment]
devpi-client only uploads what tox produces. I think devpi web should show nothing instead of the green check mark when no tests were run. That should solve this issue.

**Comment by 00willo** [comment]
Maybe an orange or yellow dash or question mark on both pages where no tests were run, to imply an unknown state, as devpi can't determine if no tests running is either good or bad.

**Comment by fschulze** [comment]
I guess the unicode warning sign is most useful here: ⚠️
