### ISSUE TITLE
`devpi list <package_name>` should have an option to list only releases in current index

### ISSUE THREAD

**Issue by r2dan** [devpi/devpi#636]
devpi-client version: 4.3.0

The **devpi list <package_name>** subcommand currently shows all releases of a package specified in the command. Let's see at the output on one of the indexes living on https://m.devpi.net:
```
$ devpi list --index stefan12/dev example                         
https://m.devpi.net/stefan12/dev/+f/7b7/b642210fbccd3/example-1.1.tar.gz
https://m.devpi.net/stefan12/dev/+f/5c0/5b87ff675b39c/example-1.0.tar.gz
https://m.devpi.net/stefan12/prod/+f/5c0/5b87ff675b39c/example-1.0.tar.gz
```

Last result is released on the index that stefan12/dev inherits from. I think that the default behaviour should remain unchanged (as sometimes you do not specify the index name explicitly), but maybe it would be useful to have some kind of switch to limit the result to the current index only (no inherited packages included). I'm not sure about the name of the switch though, maybe someone will come up with a better name ;):

```
$ devpi list --index stefan12/dev example --no-bases                      
https://m.devpi.net/stefan12/dev/+f/7b7/b642210fbccd3/example-1.1.tar.gz
https://m.devpi.net/stefan12/dev/+f/5c0/5b87ff675b39c/example-1.0.tar.gz
```

**Comment by fschulze** [comment]
what about ``--no-inherited``?

**Comment by sober7** [comment]
Hmm, I'd suggest ``--ignore-bases``. This avoids negation and refers to the actual index property (bases), which make it easier to understand what's going on.

**Comment by fschulze** [comment]
This needs server side support. I hope to get it into the next release this week.
