### ISSUE TITLE
RFC Python compatibility policy

### ISSUE THREAD

**Issue by fschulze** [devpi/devpi#638]
For Python 2.7 we will provide support until our infrastructure (travis-ci, appveyor etc) makes it too hard to test it anymore or the workarounds necessary become to costly for our service contract customers.

For Python 3.x this is still an open question. Any input on that? Just recently Python 3.4 had it's EOL, see https://devguide.python.org/

Unfortunately the tests for devpi-client require a running devpi-server and so far we didn't have a good incentive to try to run it with a different Python version. This would also have to work with Travis-CI, Appveyor and in a local dev environment. Otherwise we would only have to care about devpi-common/devpi-client, and devpi-server with all plugins could move on much quicker.

**Comment by StephanErb** [comment]
Most major distributions (e.g. Debian stable) still ship 3.4. Even though it won't get upstream fixes any longer, I think it is reasonable to keep it as part of your build chain as long as no significant effort is necessary to keep it working.

**Comment by hynek** [comment]
Yeah basically what I wrote in http://www.attrs.org/en/stable/python-2.html

While it's mainly about Python 2, the key phrase is:

> We will do our best to support existing users, but nobody is entitled to the latest and greatest features on a platform that is officially end of life.

**Comment by fschulze** [comment]
@hynek and what is your take on Python 3.x?

I think we will apply the same policy as for Python 2: as long as it's feasible

**Comment by nicoddemus** [comment]
@fschulze just thought I would mention: pytest plans to drop support for Python 2 around June in version 5.0: https://docs.pytest.org/en/latest/py27-py34-deprecation.html.

**Comment by hynek** [comment]
> and what is your take on Python 3.x?

I thought I've answered it with the second line. :)

Yeah, as long as it's feasible. My suspicion is that the first things to break are going to be pip/setuptools.

**Comment by fschulze** [comment]
I just committed changes to master which decouple the functional tests for devpi-client and devpi-server. It also contains a change in the way the functional tests are run in devpi-client. Now we don't install devpi-server via tox anymore, but create a virtualenv using Python 3 when running devpi-client tests with Python 2.7. That means the upcoming devpi-server 5.0.0 will be the last version supporting Python 2.7, with 6.0.0 we will drop that support. Only devpi-client (and devpi-common) will continue to support Python 2.7 as long as workarounds for Travis and AppVeyor are feasible. The lowest Python 3 version will be 3.4 for as long as possible.
