### ISSUE TITLE
light-mirror mode

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [devpi/devpi#639]
i'm wondering if there is a sensible way for devpi, to refer to external file locations instead of mirroring the contents of pypi

the idea behind that being to safe space both when involving larger dependency trees, and the pip caches on consumers using the devpi

**Comment by fschulze** [comment]
You mean a pass through mirror instead of a caching one?

**Comment by fschulze** [comment]
See #674

**Comment by RonnyPfannschmidt** [comment]
i wouldnt use the word "pass-trough"
the idea after all is not to cahce/copy, but to serve the external url

**Comment by fschulze** [comment]
Implemented in upcoming devpi-server 5.2.0.
