### ISSUE TITLE
Test use tox's parallel instead of detox

### ISSUE THREAD

**Issue by henryborchers** [devpi/devpi#640]
detox support for tox is deprecated and is not even compatible with versions of tox > 3.6. Any chance devpi could support the newly builtin -p/--parallel flag?

**Comment by fschulze** [comment]
You can use it with ``--tox-args``.

Unlike detox this doesn't really require further support in devpi, it would just be sugar on top.

Also the latest devpi-client release supports plugins, so you could add a ``ptest`` command yourself. Feel free to ask further questions about that here if you get stuck should you decide to try that.
