### ISSUE TITLE
devpi test results uploaded with tox==3.8.4 are interpreted as failed

### ISSUE THREAD

**Issue by r2dan** [devpi/devpi#641]
Hi,

We're struggling with tox==3.8.4 and devpi test uploads as devpi-web renders the test results and test setup as failed, even though the return code of both setup commands and tests commands are 0.

The only difference is that tox==3.7.0 reports `"retcode": "0"`, while new tox: `"retcode": 0` (str vs int). I'm wondering if it makes sense to report it to tox community as well, or to fix it on devpi-common side (https://github.com/devpi/devpi/blob/master/common/devpi_common/viewhelp.py#L65).

What's your opinion?

**Comment by gaborbernat** [comment]
I would say this to be a devpi issue. Can we fix this on devpi side? 👍

**Comment by fschulze** [comment]
I'd also say this is better on the devpi side. I already pushed a branch to my fork for testing with Travis. Will most likely finish it tomorrow.

**Comment by fschulze** [comment]
I have uploaded a devpi-common development release to https://m.devpi.net/fschulze/dev/devpi-common/3.3.2.dev0

**Comment by r2dan** [comment]
When do you expect it to go into official release?

**Comment by fschulze** [comment]
@r2dan does the dev release work for you? Then I can make a release tomorrow

**Comment by r2dan** [comment]
@fschulze: seems to work, no problems observed so far

**Comment by fschulze** [comment]
Release is out now.

**Comment by gaborbernat** [comment]
Thanks!
