### ISSUE TITLE
RAM usage on kubernetes instation

### ISSUE THREAD

**Issue by kierun** [devpi/devpi#656]
I have a local kubernetes deployment of devpi. Looking at it, it was taking 1.4G of RAM on the cluster, which I think is unreasonable. I killed the pod and now it is running with much less RAM -- several M which is fine and reasonable.

I am not sure if this is devpi or my deployment of it on a local kubernetes cluster that causes it. Has anyone else seen something similar?

**Comment by fschulze** [comment]
It could be, that the initial indexing for devpi-web took a lot of RAM. If you can reproduce the RAM usage, then please provide us with more details.

**Comment by fschulze** [comment]
No followup for 3 months. Feel free to reopen with further details.
