### ISSUE TITLE
Support replicating to a specific serial id

### ISSUE THREAD

**Issue by FRidh** [devpi/devpi#657]
In order to let `pip` reproducibly evaluate a given set of requirements, we need a snapshot of PyPI. `devpi` allows one to replicate a PyPI index. Is it possible to replicate it to a given serial id? If not, what would it roughly take to implement such feature?

**Comment by fschulze** [comment]
This isn't possible the way devpi is implemented and I think it's the wrong approach. There are some refactorings of devpi ongoing which should soon (a few weeks) make it possible to have an index which filters releases based on a list of requirements very similar to pip constraints: https://pip.pypa.io/en/stable/user_guide/#constraints-files

**Comment by FRidh** [comment]
We need to resolve a set of packages, but we need to be able to resolve it for both multiple platforms and Python versions, and we do not want the state of PyPI to have changed between resolving one case and resolving the next.

**Comment by fschulze** [comment]
Then it's probably better to create a separate PyPI mirror with bandersnatch or something similar and in devpi create a mirror index which points to that instead of PyPI. The architecture of those mirror tools should be better suited for what you want.

**Comment by FRidh** [comment]
Right, that was the other project. Thanks. I see they already have an attribute `target_serial` so optimistically it may only need a way to explicitly pass it in.
