### ISSUE TITLE
Is there a way to get packages hashes?

### ISSUE THREAD

**Issue by juanformoso** [devpi/devpi#665]
Hi, is there an endpoint in devpi server (or web) I can use to get the version hashes like I can in pypi?

I mean something like this: https://pypi.org/pypi/devpi-client/json  
I can get the sha256 of every version via that URL, I can't find something similar in devpi nor an 
 existing plugin.

Thanks

**Comment by fschulze** [comment]
Try something like this:
``curl -H "Accept: application/json" https://m.devpi.net/fschulze/devpi49/devpi-server/4.9.0``

**Comment by fschulze** [comment]
And they are in the source code of the simple pages:
https://m.devpi.net/fschulze/devpi49/+simple/devpi-server/

**Comment by juanformoso** [comment]
Awesome, that should work. 
Thanks a lot!
