### ISSUE TITLE
Question for devpi packages？

### ISSUE THREAD

**Issue by zhangsimingshannonai** [devpi/devpi#669]
Hello，I'm using devpi and I'm on Ubuntu 16.04,but I met so many problem,wait for you answer~

1.when I upload my python package like:
```
zhangsiming@cpuserver:/usr/local$ devpi upload test-2.3.4.5.tar.gz 
register test-2.3.4.5 to http://localhost:3141/zhang/aaa/
file_upload of test-2.3.4.5.tar.gz to http://localhost:3141/zhang/aaa/
```
I know it will add on the index and I can use "devpi install package" to install it.
What I want to ask is where the package itself will be upload to ?
Can I delete the package on my local after the upload operation?
Or give me some method on how to manager my private python packages.

2.The command "devpi" is default Install in "$HOME/.local/bin/devpi" ,but when I switch a user ,the command cannot even found ,this is so inconvenient and affect the normal use , like below:
```
zhangsiming@cpuserver:~$ which devpi
/home/zhangsiming/.local/bin/devpi
zhangsiming@cpuserver:~$ sudo su 
root@cpuserver:/home/zhangsiming# which devpi
root@cpuserver:/home/zhangsiming# devpi use
devpi: command not found
```
Is there something I can do to fix it ?
I sincerely and urgently need your reply and help for the above two questions ,thanks a lot!

**Comment by fschulze** [comment]
> 1.when I upload my python package like:
> 
> ```
> zhangsiming@cpuserver:/usr/local$ devpi upload test-2.3.4.5.tar.gz 
> register test-2.3.4.5 to http://localhost:3141/zhang/aaa/
> file_upload of test-2.3.4.5.tar.gz to http://localhost:3141/zhang/aaa/
> ```
> 
> I know it will add on the index and I can use "devpi install package" to install it.
> What I want to ask is where the package itself will be upload to ?
> Can I delete the package on my local after the upload operation?
> Or give me some method on how to manager my private python packages.

By default devpi-server stores its data in a special folder in your home directory: ``~/.devpi/server``

You should backup that folder regularly. You should also make a backup using ``devpi export`` every once in a while. If you do so, then it is safe to delete your local package after upload.

> 2.The command "devpi" is default Install in "$HOME/.local/bin/devpi" ,but when I switch a user ,the command cannot even found ,this is so inconvenient and affect the normal use , like below:
> 
> ```
> zhangsiming@cpuserver:~$ which devpi
> /home/zhangsiming/.local/bin/devpi
> zhangsiming@cpuserver:~$ sudo su 
> root@cpuserver:/home/zhangsiming# which devpi
> root@cpuserver:/home/zhangsiming# devpi use
> devpi: command not found
> ```
> 
> Is there something I can do to fix it ?
> I sincerely and urgently need your reply and help for the above two questions ,thanks a lot!

This is a general Unix/Linux question. You should try to find tutorials or books on how to use Unix/Linux.

How did you install devpi-client? It looks like you installed it with ``pipsi``, which is meant to install Python tools per user. I would suggest you either install devpi-client for each user, or learn how the ``PATH`` environment variable works. This issue tracker is not the place for that.

It also looks like you want to work as ``root`` user. I would advice against that. Again, this is general Unix/Linux stuff and you should try to learn about that somewhere else.

**Comment by zhangsimingshannonai** [comment]
> > 1.when I upload my python package like:
> > ```
> > zhangsiming@cpuserver:/usr/local$ devpi upload test-2.3.4.5.tar.gz 
> > register test-2.3.4.5 to http://localhost:3141/zhang/aaa/
> > file_upload of test-2.3.4.5.tar.gz to http://localhost:3141/zhang/aaa/
> > ```
> > 
> > 
> > I know it will add on the index and I can use "devpi install package" to install it.
> > What I want to ask is where the package itself will be upload to ?
> > Can I delete the package on my local after the upload operation?
> > Or give me some method on how to manager my private python packages.
> 
> By default devpi-server stores its data in a special folder in your home directory: `~/.devpi/server`
> 
> You should backup that folder regularly. You should also make a backup using `devpi export` every once in a while. If you do so, then it is safe to delete your local package after upload.
> 
> > 2.The command "devpi" is default Install in "$HOME/.local/bin/devpi" ,but when I switch a user ,the command cannot even found ,this is so inconvenient and affect the normal use , like below:
> > ```
> > zhangsiming@cpuserver:~$ which devpi
> > /home/zhangsiming/.local/bin/devpi
> > zhangsiming@cpuserver:~$ sudo su 
> > root@cpuserver:/home/zhangsiming# which devpi
> > root@cpuserver:/home/zhangsiming# devpi use
> > devpi: command not found
> > ```
> > 
> > 
> > Is there something I can do to fix it ?
> > I sincerely and urgently need your reply and help for the above two questions ,thanks a lot!
> 
> This is a general Unix/Linux question. You should try to find tutorials or books on how to use Unix/Linux.
> 
> How did you install devpi-client? It looks like you installed it with `pipsi`, which is meant to install Python tools per user. I would suggest you either install devpi-client for each user, or learn how the `PATH` environment variable works. This issue tracker is not the place for that.
> 
> It also looks like you want to work as `root` user. I would advice against that. Again, this is general Unix/Linux stuff and you should try to learn about that somewhere else.

Thanks for your reply , I install the devpi-client by:
```
pip3 install -y devpi-client
```
when I switch user, the "devpi" command not found ,I guess it's because the devpi-client in a hidden directory like "$HOME/.local/bin/devpi" ,can I change the default install directory when install devpi-client by "pip3 install -y devpi-client"?

**Comment by zhangsimingshannonai** [comment]
Finally I figured it out by:
```
root@cpuserver:/home/zhangsiming# tail -1 /etc/profile
export PATH=$PATH:/home/zhangsiming/.local/bin/
root@cpuserver:/home/zhangsiming# source /etc/profile
root@cpuserver:/home/zhangsiming# echo $PATH
/opt/miniconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/zhangsiming/.local/bin/:/snap/bin:/home/zhangsiming/.local/bin/
root@cpuserver:/home/zhangsiming# which devpi
/home/zhangsiming/.local/bin//devpi
```
It's something about the environment variable on Linux , thanks very much for your answer!
Sorry for asking you frequently,thanks a lot!
