### ISSUE TITLE
Can you give me some backup Suggestions?

### ISSUE THREAD

**Issue by zhangsimingshannonai** [devpi/devpi#670]
I'm trying to use devpi on Ubuntu 16.04 LTS.
But I didn't found anything about the backups for devpi ,It bothers me ,because backup is essential for using devpi on-line.

Questions:
1.I used devpi-postgresql plugin with a postgresql on my server. I think it is very easy to use.
I looked over the database I use for devpi backup .And I see:
```
postgres=# \c exampledb
You are now connected to database "exampledb" as user "postgres".
exampledb=# \d
          List of relations
 Schema |   Name    | Type  | Owner  
--------+-----------+-------+--------
 public | changelog | table | siming
 public | files     | table | siming
 public | kv        | table | siming
(3 rows)
``` 
I want to know what thing did the database stored .What is the kv、files、changelog? Did it stored the packages I upload?

2.I knew by default the packages and the index information stored in "$HOME/.devpi/server/+files/" ，so is it enough to only back up this directory? Or I should do "devpi export" termly? Do I need "devpi-server replication"?

I'm sorry for too many question about the backup. But I sincerely hope to get your reply for the above two questions. And I'd like to hear your suggestions for the devpi backup.

**Comment by fschulze** [comment]
With devpi-postgresql almost everything is stored in the database. All files and metadata is there. If you backup the database properly (covered in their documentation and a lot of info available on the net) you have everything to recover. The only thing left in ``$HOME/.devpi/server`` are some support files like ``.nodeinfo``, ``.eventserial`` and if you have devpi-web installed the search index. Backing these up makes it easier and faster to recover from a failure, but they are not essential. It is advised to back them up as well though.

We are working on moving everything to the storage backend and explicit configuration, but that work isn't finished yet.

**Comment by fschulze** [comment]
If you use ``devpi-server --export``, then you also have a future proof backup. It's comparable to ``dumpdb`` of postgresql which is version independent. This is most likely the simplest method for backup, but it needs additional space to write the output.

**Comment by zhangsimingshannonai** [comment]
> With devpi-postgresql almost everything is stored in the database. All files and metadata is there. If you backup the database properly (covered in their documentation and a lot of info available on the net) you have everything to recover. The only thing left in `$HOME/.devpi/server` are some support files like `.nodeinfo`, `.eventserial` and if you have devpi-web installed the search index. Backing these up makes it easier and faster to recover from a failure, but they are not essential. It is advised to back them up as well though.
> 
> We are working on moving everything to the storage backend and explicit configuration, but that work isn't finished yet.

Thanks your reply, it help me a lot.
Let me make sure , if I backup everything in postgresql, when my devpi-server is down, I can use:
```
devpi-server --storage pg8000:host=localhost,port=5432,database=devpidb,user=devpi,password=devpipassword --start --init --serverdir /data/server
```
I mean, I can select the same database of postgresql to a new serverdir to recover everything?
And additional, if I use postgresql to backup, can I remove all things in "$HOME/.devpi/server/+files"?

**Comment by fschulze** [comment]
It *should* work, but you should definitely test it first! Using ``devpi-server --export`` will definitely work and everything will be in one place. As long as you haven't tested any other approach, it is the safest option for you and backups are meant to be safe!

**Comment by zhangsimingshannonai** [comment]
> It _should_ work, but you should definitely test it first! Using `devpi-server --export` will definitely work and everything will be in one place. As long as you haven't tested any other approach, it is the safest option for you and backups are meant to be safe!

Thanks for your patient guidance, I will test it later.

**Comment by zhangsimingshannonai** [comment]
Hello, after a test, I found something is not what I thought. If I use postgresql as a backup, it seems that all of the thing was stored in the database. I cannot even see them in `$HOME/.devpi./server/+files`.
```
root@ip-172-31-25-120:/test# ls -a
.  ..  .event_serial  .indices  .nodeinfo  .secret  .serverversion  .xproc
root@ip-172-31-25-120:/test# psql -h localhost -U devpi -d devpidb -p 5432
Password for user devpi: 
psql (9.5.17)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

devpidb=> \d
         List of relations
 Schema |   Name    | Type  | Owner 
--------+-----------+-------+-------
 public | changelog | table | devpi
 public | files     | table | devpi
 public | kv        | table | devpi
(3 rows)

devpidb=> select * from kv;
                        key                         |     keyname     | serial 
----------------------------------------------------+-----------------+--------
 root/.config                                       | USER            |      0
 root/pypi/.mirrornameschange                       | MIRRORNAMESINIT |      1
 .config                                            | USERLIST        |      2
 zhang/.config                                      | USER            |      3
 zhang/dev/test/.versions                           | PROJVERSIONS    |      4
 zhang/dev/.projects                                | PROJNAMES       |      4
 zhang/dev/+f/188/08a00b57ed3c1/test-2.3.4.5.tar.gz | STAGEFILE       |      5
 zhang/dev/test/.simple                             | PROJSIMPLELINKS |      5
 zhang/dev/test/2.3.4.5/.config                     | PROJVERSION     |      5
(9 rows)
```

Now there's an important thing. As we see, the directory don't have a `+files` directory after using postgresql. That means all the information include the package I upload is stored in postgresql.
So, does the database have enough capacity? I will upload many big size package to devpi. I'm so worried about this thing.
Just give me some suggestion.

**Comment by zhangsimingshannonai** [comment]
> It _should_ work, but you should definitely test it first! Using `devpi-server --export` will definitely work and everything will be in one place. As long as you haven't tested any other approach, it is the safest option for you and backups are meant to be safe!

Hello, after a test, I found something is not what I thought. If I use postgresql as a backup, it seems that all of the thing was stored in the database. I cannot even see them in `$HOME/.devpi./server/+files`.
```
root@ip-172-31-25-120:/test# ls -a
.  ..  .event_serial  .indices  .nodeinfo  .secret  .serverversion  .xproc
root@ip-172-31-25-120:/test# psql -h localhost -U devpi -d devpidb -p 5432
Password for user devpi: 
psql (9.5.17)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

devpidb=> \d
         List of relations
 Schema |   Name    | Type  | Owner 
--------+-----------+-------+-------
 public | changelog | table | devpi
 public | files     | table | devpi
 public | kv        | table | devpi
(3 rows)

devpidb=> select * from kv;
                        key                         |     keyname     | serial 
----------------------------------------------------+-----------------+--------
 root/.config                                       | USER            |      0
 root/pypi/.mirrornameschange                       | MIRRORNAMESINIT |      1
 .config                                            | USERLIST        |      2
 zhang/.config                                      | USER            |      3
 zhang/dev/test/.versions                           | PROJVERSIONS    |      4
 zhang/dev/.projects                                | PROJNAMES       |      4
 zhang/dev/+f/188/08a00b57ed3c1/test-2.3.4.5.tar.gz | STAGEFILE       |      5
 zhang/dev/test/.simple                             | PROJSIMPLELINKS |      5
 zhang/dev/test/2.3.4.5/.config                     | PROJVERSION     |      5
(9 rows)
```

Now there's an important thing. As we see, the directory don't have a `+files` directory after using postgresql. That means all the information include the package I upload is stored in postgresql.
So, does the database have enough capacity? I will upload many big size package to devpi. I'm so worried about this thing.
Just give me some suggestion.

**Comment by fschulze** [comment]
The disk space usage is the same. From a performance point of view postgresql should easily handle the load.

**Comment by fschulze** [comment]
No followup. If there is still an issue here, feel free to reopen.

**Comment by JonathanRRogers** [comment]
I decided to use devpi-server --export to make backups rather than backing up the PostgreSQL database because the export excludes mirrored files.

**Comment by fschulze** [comment]
See #674 in case you don't need the local copies.
