### ISSUE TITLE
Question about the plugin "devpi-semantic-ui"

### ISSUE THREAD

**Issue by zhangsimingshannonai** [devpi/devpi#679]
Hello, I'm using devpi on Ubuntu 16.04 LTS for a long time. Today I attempt to use "devpi-semantic-ui" because it is more human-friendly than "devpi-web".

I use:
```
/usr/local/bin/devpi-server --theme semantic-ui --restrict-modify :devpi-admin --ldap-config /ldap/ldap.yaml --storage pg8000:host=xxxxxxxxxx,port=5432,database=devpi,user=devpi,password=xxxxxx --serverdir /data/server --host 0.0.0.0 --port 3141
```
to launch my devpi-server.

And then I access "http://xxxxxxxxxxxx:3141" to the devpi-ui.

Most of things are ok, but I found two things odd:

1.On the devpi-ui, I have a warning on status,here is the screenshot:

![image](https://user-images.githubusercontent.com/49146774/59664609-f5dcc200-91e3-11e9-92fa-bd6b1dc4b747.png)

And each time I refreshed the ui，the log below would be appeared.
```
devpi    | 2019-06-18 08:05:09,958 INFO  [req130] GET /+status
devpi    | 2019-06-18 08:05:10,127 INFO  [req131] GET /robots.txt
devpi    | 2019-06-18 08:05:10,181 ERROR [req131] [Rtx15] while handling http://172.31.28.20:3141/robots.txt?1560845109000:
devpi    | no user 'robots.txt'
``` 
My devpi-server is functional. That confused me a lot, please help me to figure it out.

2.What's the mirror_whitelist's meaning, can you give a crisp and clear account of in which condition should I use it?
![image](https://user-images.githubusercontent.com/49146774/59665194-05103f80-91e5-11e9-8c6d-ed124bb085d1.png)

Waiting for your reply.

**Comment by fschulze** [comment]
The status in this case is about the devpi-web indexing for search. It's most likely that it is still working on indexing ``root/pypi``, which can take an hour or more. It should go away after a while and ``Processed events serial`` should match ``Current serial``.

The ``robots.txt`` error is caused by Google and other web crawlers, refreshing the page should have nothing to do with it, unless ``devpi-semantic-ui`` does something really weird. I looked at it a year ago and it was fine back then.

On ``mirror_whilelist``:
https://devpi.net/docs/devpi/devpi/stable/+d/userman/devpi_indices.html?highlight=mirror_whitelist#modifying-the-mirror-whitelist

**Comment by zhangsimingshannonai** [comment]
> The status in this case is about the devpi-web indexing for search. It's most likely that it is still working on indexing `root/pypi`, which can take an hour or more. It should go away after a while and `Processed events serial` should match `Current serial`.
> 
> The `robots.txt` error is caused by Google and other web crawlers, refreshing the page should have nothing to do with it, unless `devpi-semantic-ui` does something really weird. I looked at it a year ago and it was fine back then.
> 
> On `mirror_whilelist`:
> https://devpi.net/docs/devpi/devpi/stable/+d/userman/devpi_indices.html?highlight=mirror_whitelist#modifying-the-mirror-whitelist

And, what the meaning of "+simple" on the url?

**Comment by fschulze** [comment]
> And, what the meaning of "+simple" on the url?

It's the page which ``pip`` uses for installation. The equivalent of https://pypi.org/simple/

**Comment by zhangsimingshannonai** [comment]
> equivalent

Thanks

**Comment by zhangsimingshannonai** [comment]
Hi ,here is a new question.
![image](https://user-images.githubusercontent.com/49146774/60779272-af3c1100-a16c-11e9-8176-613c9adfd107.png)
Why I can't use the search on ui to search packages in pypi?
where should I configure? and I after a little bit, I saw the status came to fatal.
![image](https://user-images.githubusercontent.com/49146774/60779352-0215c880-a16d-11e9-8a64-645d5e6ff5cc.png)
In your words, it is working on indexing root/pypi. 

1.The question is how to trigger this indexing on my own?
2.Is it searching the "index-url" in "~/.pip/pip.conf" of the "mirror_url" of the root/pypi index? If I want to search packages in other place, what should I do? 

Waiting for you reply.

**Comment by zhangsimingshannonai** [comment]
@fschulze

**Comment by fschulze** [comment]
First up, please stop adding separate posts pinging me with ``@fschulze``, I get notified anyway.

With the latest devpi-web 3.5.2 there should be regular progress output for indexing mirrors like ``root/pypi`` in the log output of devpi-server. As I stated before, indexing ``root/pypi`` takes quite some time. Just let it run and check the log output. If there are error messages related to indexing, then report back with a copy of those errors.

**Comment by fschulze** [comment]
No followup. Feel free to reopen if there is still an issue here.
