### ISSUE TITLE
Inherit from multiple indexes, combine packages

### ISSUE THREAD

**Issue by jrast** [devpi/devpi#680]
I have setup the following indexes:

- root/pypi --> default mirror of PyPi
- root/piwheels --> mirror of pywheels.org index
- org/prod --> local packages, inherits from root/pypi and root/piwheels

Now I want to install numpy from a raspberry pi which uses the org/prod index. Numpy is available as wheel on root/piwheels and therefore I expect that it will be available from there. However, pip uses the source package which is available on root/pypi.
If I use the devpi web search I can find numpy in both indexes (root/pypi and root/piwheels), why does pip use the wrong package? Or is this a limitation of devpi which hides one of the indexes because the package is available in both indexes?

**Comment by jrast** [comment]
After revising the docs, i think this would be possible:

- root/pypi --> default mirror of PyPi
- root/piwheels --> mirror of pypwheels.org index, bases=root/pypi, whitelist=*
- org/prod --> local packages, bases=root/pywheels

Is it legal for a mirror to have a base and would this work?

**Comment by fschulze** [comment]
I just tried it and I think you found a bug. Your second idea won't work, as mirrors don't have bases.

Setting ``bases=root/piwheels,root/pypi`` or ``bases=root/pypi,root/piwheels`` should both work, but devpi only uses the first hit and doesn't mix the links (btw, pywheels threw me off at first, as I couldn't find anything related)

**Comment by fschulze** [comment]
It's a whitelist related bug. You can work around it by doing:
``devpi index org/prod bases=root/pypi,root/piwheels mirror_whitelist="*"``

**Comment by fschulze** [comment]
The more I think about it, the more I'm convinced it is not a bug, but whitelisting is doing what it is supposed to do. Changing it might open up other security issues.

**Comment by jrast** [comment]
Thanks a lot! The trick with the whitelist works as expected. 
However, I'm not shure if this is the cleanest solution. If all packages are whitelisted, someone can upload a newer, malicious, version of an internal package to one of the mirrored indexes.
To prevent this, one can keep a list of whitelisted packages but this requires a lot of manual work to find all packages which are provided by both indexes.

> Changing it might open up other security issues.
What kind of issues do you have in mind?

Maybe a strategy option should be provided if multiple bases are given for an index. Like "Combine Bases", "Prefer First", ...

**Comment by jrast** [comment]
> To prevent this, one can keep a list of whitelisted packages but this requires a lot of manual work to find all packages which are provided by both indexes.

Or maybe I can add an intermediate index which just combines the two indexes with whitelisting and inherit the actual index from this intermediate index:

- root/pypi --> mirror of pypi
- root/piwheels --> mirror of piwheels.org
- root/combo  --> intermediate index, bases=root/pypi,root/piwheels, mirror_whitelist=*
- org/prod --> bases=root/combo

**Comment by fschulze** [comment]
Did you try that last one? It looks like it should work.

**Comment by jrast** [comment]
Sorry, never had time to test this. I will look into this during the next days.

**Comment by fschulze** [comment]
@jrast see #725
