### ISSUE TITLE
Unable to enter password starting with dash from script

### ISSUE THREAD

**Issue by davidsmf** [devpi/devpi#683]
We use `devpi-gitlab-auth` which allows us to authenticate using short-lived build tokens from gitlab.

We have a line that says:
> devpi login "gitlab-ci-token" --password "$CI_BUILD_TOKEN"

Unfortunately the builds fail every so often. It turns out that this is due to `CI_BUILD_TOKEN` starting with a dash (`-`).

The error message looks like: 
```

# devpi login gitlab-ci-token --password '-example-password'
usage: devpi [-h] [--version] [--debug] [-y] [-v] [--clientdir DIR]
             {quickstart,use,getjson,patchjson,list,remove,user,passwd,login,logoff,logout,index,upload,test,push,install,refresh}
             ...
devpi: error: argument --password: expected one argument
```

I can't find a way to specify a password with a dash. Can we have a way to specify via a file (maybe enable `fromfile_prefix_chars` on `argparse.ArgumentParser`, or have a separate `--password-file` option), or via an env var? Maybe `DEVPI_PASSWORD` could be checked before using `getpass`.

**Comment by fschulze** [comment]
Try ``--password="$CI_BUILD_TOKEN"``

**Comment by davidsmf** [comment]
Oh, thanks, that does work.
