### ISSUE TITLE
How to use “--root-passwd-hash” ?

### ISSUE THREAD

**Issue by zhangsimingshannonai** [devpi/devpi#684]
I see it in devpi-server --help, It seem that I can set a hashed password when initialize a devpi-server. But you didn't give a declare on which hash arithmetic it supports. I tried some hash but failed.
 
Just give me a way to gengrate a hash password?
Here is my (wrong) way:
```
mkpasswd -m sha-512 test
$6$ZfNZMZv8KAu$yxxNPl8z4CcR3mvf2EYqcxTwaq8PxWry9PHBY5WqANk2K9gNiQ2jJ8fC4Wc1xo4GmsAn3AUGMKFHUWh4/Yzjh/
```
In my method, `yxxNPl8z4CcR3mvf2EYqcxTwaq8PxWry9PHBY5WqANk2K9gNiQ2jJ8fC4Wc1xo4GmsAn3AUGMKFHUWh4/Yzjh/` part is hash for "test". But I cannot use "test" to login root.

```
devpi-server --theme semantic-ui --root-passwd-hash yxxNPl8z4CcR3mvf2EYqcxTwaq8PxWry9PHBY5WqANk2K9gNiQ2jJ8fC4Wc1xo4GmsAn3AUGMKFHUWh4/Yzjh/ --restrict-modify ${adminuser} --ldap-config ${ldapfile} --serverdir /data/jjj --start --host 0.0.0.0 --port 3141 --init 
```

SO, Just give me a way to gengrate a effective hash password? Thanks

**Comment by zhangsimingshannonai** [comment]
Here's my Error output:
```
root@ip-172-31-28-20:/data# devpi login root
password for user root: test
WARN: devpi-client-4.4.0 got an unversioned reply, assuming API-VERSION 2 (as implemented by devpi-server-2.0)
POST http://localhost:3141/+login
500 Internal Server Error: Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)
```

**Comment by fschulze** [comment]
Devpi uses argon2. In the devpi-server virtualenv, you can run the following:
``python -c "from devpi_server.auth import hash_password; print(hash_password('password'))"``

**Comment by zhangsimingshannonai** [comment]
> Devpi uses argon2. In the devpi-server virtualenv, you can run the following:
> `python -c "from devpi_server.auth import hash_password; print(hash_password('password'))"`

Thanks for your reply.
First which part should I use ,I generate a password in your way 
```
root@ip-172-31-28-20:/data# python -c "from devpi_server.auth import hash_password; print(hash_password('666666'))"
$argon2i$v=19$m=102400,t=2,p=8$9P6/t3ZuLWWMEWJMCcGY8w$y2B6Njugs2MYTHdkn6jkMg
```
Is `8$9P6/t3ZuLWWMEWJMCcGY8w$y2B6Njugs2MYTHdkn6jkMg` the password?
I use it, but when I login, the same error appeard.
```
root@ip-172-31-28-20:/data# devpi login root
password for user root: 
WARN: devpi-client-4.4.0 got an unversioned reply, assuming API-VERSION 2 (as implemented by devpi-server-2.0)
POST http://localhost:3141/+login
500 Internal Server Error: Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)
```
I can do a login use other users in my ldap successfully! That confused me.

**Comment by zhangsimingshannonai** [comment]
@fschulze

**Comment by fschulze** [comment]
The complete ``$argon2i$v=19$m=102400,t=2,p=8$9P6/t3ZuLWWMEWJMCcGY8w$y2B6Njugs2MYTHdkn6jkMg`` is the password hash. If you just want to set your ``root`` password once, then you can also use ``--root-password``, which is much easier. The ``--root-password-hash`` option is for automated deployment tools etc.

If you use devpi-ldap, then that is an additional source of users. The devpi internal users still work if they don't exist in your ldap. Also the ``root`` user is always the devpi internal user, never from ldap.

**Comment by zhangsimingshannonai** [comment]
> The complete `$argon2i$v=19$m=102400,t=2,p=8$9P6/t3ZuLWWMEWJMCcGY8w$y2B6Njugs2MYTHdkn6jkMg` is the password hash. If you just want to set your `root` password once, then you can also use `--root-password`, which is much easier. The `--root-password-hash` option is for automated deployment tools etc.
> 
> If you use devpi-ldap, then that is an additional source of users. The devpi internal users still work if they don't exist in your ldap. Also the `root` user is always the devpi internal user, never from ldap.

By your way, the log show:
```
ValueError: hash could not be identified
```
What does it mean?

**Comment by fschulze** [comment]
It means you left out the beginning and because of that the password library doesn't know what to do with the value. The ``$argon2i$v=19$m=102400,t=2,p=`` part is essential.

**Comment by zhangsimingshannonai** [comment]
> It means you left out the beginning and because of that the password library doesn't know what to do with the value. The `$argon2i$v=19$m=102400,t=2,p=` part is essential.

I have that part.....I promise

**Comment by zhangsimingshannonai** [comment]
> > It means you left out the beginning and because of that the password library doesn't know what to do with the value. The `$argon2i$v=19$m=102400,t=2,p=` part is essential.
> 
> I have that part.....I promise

**Comment by zhangsimingshannonai** [comment]
Finally I figured it out by adding single quotes at both ends.
```
--root-passwd-hash '$argon2i$v=19$m=102400,t=2,p=8$KEXoHcNYS2kNoVQqxfhfiw$luYMxy265LUEIVk/wLX1cQ'
```
If don't use this, it will be error. Thanks

**Comment by fschulze** [comment]
Seems like this is resolved. If there is still an issue, please reopen with more details.
