### ISSUE TITLE
How do I upload documentation without using the devpi command?

### ISSUE THREAD

**Issue by exhuma** [devpi/devpi#685]
We are moving to devpi and all of our projects use `fabric` tasks to build the docs (instead of `setup.py build_sphinx`).

How can I upload our existing documentation to the devpi server?

**Comment by fschulze** [comment]
You can upload the generated doc zip. The filename should be in this form: ``[packagname]-[version].doc.zip``, then it will be linked to the correct version. For example:
``devpi upload devpi-5.0.doc.zip``

Also see #619

**Comment by exhuma** [comment]
Is it also possible without using the devpi client? We currently use `twine` to push the packages. The client is not necessarily available in the environments.

**Comment by fschulze** [comment]
I don't think that is possible, because twine is made for PyPI and it doesn't support documentation hosting anymore.

**Comment by exhuma** [comment]
Hmmm... this might be a bit problematic. We publish our packages (including deocs) in an automated pipeline. This pipeline needs write access to the repository. Incidentally, this is one reason we use `twine`. `twine` parses `~/.pypirc` which in this case contains the password. We are aware on the risks but we are currently unaware of better alternatives.

We would pass the password as command-line argument, but that way it would leak into our logs. It being in `~/.pypirc` of the pipeline runner makes this much more difficult to access.

But security aside, I can't find any mention of `~/.pypirc` in the `devpi-client` docs, and it does not seem that it is used. I can see that `~/.devpi/client/current.json` contains authentication details, but the token for that user expires after 10 hours. Is it possible to create a token which never expires?

Or even better, make `devpi` read the `pypirc` file.

**Comment by exhuma** [comment]
Nevermind. I just found #666 which pointed me to using `devpi push` with the `pypi:` prefix. I missed that as I automatically assumed this was reserved for the official `pypi` repository.

This should solve all the problems until I figure out how to call it 😅

**Comment by exhuma** [comment]
... alas ... I can't quite figure out how to push it... it keeps complaining with the following error:

```
$ devpi push --debug fabprips==2.17.0 pypi:devpi-staging
using pypirc /home/users/malbert/.pypirc
PUSH http://devpi-stg.dtt.ptech.lu/coss/public
400 Bad Request: there are no files for fabprips-2.17.0 on stage coss/public
```

I don't quite understand why it complains that there are no files. That's the point of "pushing", no? When I push a file it is quite normal that they are not yet on the repo.

I *assume* that "push" is different from "upload" in that "push" will only move files from one repo into another one.

This leaves the question: How do I *upload* using the `~/.pypirc` file to get passwordless uploads (if there is no other passwordless alternative)?

**Comment by fschulze** [comment]
the ``keyring`` package has a devpi-client plugin, would that help for your use case?

**Comment by exhuma** [comment]
I will need to give that a go. Our current sprint is coming to an end and I will need to shift focus to something else soon. I hope I won't forget about this once I get back around to this :)

**Comment by fschulze** [comment]
See https://github.com/devpi/devpi/pull/698 which will be in devpi-client 5.1.0

**Comment by fschulze** [comment]
Have you been able to try it?

**Comment by exhuma** [comment]
I have not gotten around to it yet. I'll set a reminder for next week and give it a go.

**Comment by exhuma** [comment]
I'll have a look now.

**Comment by exhuma** [comment]
This seems to be working. Even in `5.0.0`

Thank you for the pointers.
