### ISSUE TITLE
requires_dist metadata missing

### ISSUE THREAD

**Issue by pierreluctg** [devpi/devpi#688]
When uploading a new release with `devpi upload`, I have noticed that `requires_dist` metadata is missing. Calling `devpi upload` a second time on the same source is adding the `requires_dist` metadata even on non-volatile index.

**Comment by fschulze** [comment]
Does this happen for each version?

**Comment by pierreluctg** [comment]
Yes, for each new version of a package, I have to call `devpi upload` twice in order to have `requires_dist` metadata showing.

**Comment by fschulze** [comment]
The problem seems to be the upload order. The ``requires_dist`` metadata is only supplied with wheel uploads, but not with source uploads. When the source is uploaded after the wheel, then the missing metadata is removed. I have to think about the implications of changing this.

**Comment by fschulze** [comment]
@pierreluctg try ``devpi upload --formats sdist && devpi upload --formats bdist_wheel`` vs ``devpi upload --formats bdist_wheel && devpi upload --formats sdist``, that should also produce different outcomes. Anyway, I know what the core issue is, just have to think about it and check what warehouse (pypi.org) does in this case.
