### ISSUE TITLE
doc.devpi.net is down

### ISSUE THREAD

**Issue by vinnyfuria** [devpi/devpi#690]
https://doc.devpi.net/ is not accessible from anywhere. Is there a mirror somewhere?

**Comment by fschulze** [comment]
The host had a hardware failure and there were several stumbling stones along the way to recovery so far. The source for the docs is in https://github.com/devpi/devpi/tree/master/doc, I hope that helps in finding infos until recovery is complete.

**Comment by fschulze** [comment]
It is back

**Comment by vinnyfuria** [comment]
Thanks for info and update @fschulze!
