### ISSUE TITLE
How to allow unauthenticated uploads?

### ISSUE THREAD

**Issue by fj-sanchez** [devpi/devpi#691]
I have tried setting the `acl_upload` of one index to `:ANONYMOUS:` but when calling `devpi upload` I get the next message: `need to be authenticated (use 'devpi login')`. I would like to allow anyone with the URL to push to this index, is this possible?

**Comment by fschulze** [comment]
I'm pretty sure this is a ``devpi-client`` issue. With something like ``twine`` it should be possible to upload without password. If that is the case, then we should fix ``devpi-client``.

**Comment by fj-sanchez** [comment]
How can I use twine to upload without user/password?

**Comment by fj-sanchez** [comment]
After a few experiments with twine it seems impossible to upload anything unless you use an existing user. When using an existing user then you can push to the indexes that have `:ANONYMOUS:` in the `upload_acl` variable, but a user seems to be always required...

**Comment by con-f-use** [comment]
Sorry for the necro, but as a somewhat related issue:

Can I do something like `upload_acl=*` or `upload_acl=:AUTHENTICATED:` to allow any user to upload to the index, as long as they are logged in (or used someting like `twine upload -u their_user -p  <their_password> ...`?

**Comment by fschulze** [comment]
@con-f-use have you tried ``upload_acl=:AUTHENTICATED:``? It should work.

The documentation needs a lot of work.

**Comment by con-f-use** [comment]
Yeah, that works, sweet! Lucky guess then, didn't think to try it before.

Btw. @fschulze  is `*` a valid username for devpi? Asking because I had tried `upload_acl=*` and `upload_acl='*'` and didn't get an error. I'd hail that a bug, if these are not valid values and suggest printing an error.
