### ISSUE TITLE
token support ala pypi.org

### ISSUE THREAD

**Issue by fschulze** [devpi/devpi#699]
I'd like to add support for upload tokens like pypi.org.

The biggest issue I see right now is handling the keys for the tokens.

Currently the 10 hour login tokens are signed using one key stored on the filesystem. The only other thing that is hidden from normal users are the password hashes. These are accessible via the replication protocol if those endpoints aren't properly secured (these are blocked by default and it is documented).

So we currently have no way of securely storing the keys.

I think we should extend the hiding of the password hash to another key in the user config. In there we store a salt for each token from which we derive the key for the token in combination with the key stored on the filesystem at runtime. That way an attacker needs both information from the db and the filesystem and it is easy to revoke a token key by removing the salt from the db. All tokens can be invalidated by changing the server key. For key derivation we could use argon2 like for the password hashes. The derived keys would be cached during runtime, otherwise the performance impact would be impractical. From a security point of view this looks no different to me than storing the keys in the db as pypi does.

**Comment by RonnyPfannschmidt** [comment]
how about using json web token

an example would be https://jwt.io/#debugger-io?token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VybmFtZSIsImluZGV4IjoicHktcGFja2FnZXMiLCJzY29wZSI6InVwbG9hZCIsImxpbWl0LXRvIjoibW15LXNwZWNpaWMtcGFja2FnZSIsImlhdCI6MTUxNjIzOTAyMn0.Gr_CF6LoUEGFojCB8JYGLHPt2MLE5hUPVrciJDJdVV1luzOlwOTMyVybHrd2DVkqxwX3YvNz3JSyrsqKmM7mUQ

those can contain data about allowed indexes and packages (so one could make tokens for specific users/indexes/packages to be uploaded)

**Comment by RonnyPfannschmidt** [comment]
and of course, the server secret could be used for validation/invalidation

**Comment by fschulze** [comment]
See https://github.com/devpi/devpi-tokens

**Comment by fschulze** [comment]
I have released devpi-tokens 1.0.0.
