### ISSUE TITLE
Kubernetes, mixed content, and TLS.

### ISSUE THREAD

**Issue by kierun** [devpi/devpi#702]
I have devpi deployed in kubernetes with a custom TLS via the ingress. Devpi runs as "normal" without any certificates whatsoever. My set up works fine but for mixed content warnings. looking at the source, I can see that a lot of CSS are fetched via `http` which clearly is causing Firefox to moan about "mixed content".

*How could I solve this?*

What more information would you need to help?

**Comment by fschulze** [comment]
Set the X-Outside-URL proxy header:
https://devpi.net/docs/devpi/devpi/stable/+doc/quickstart-server.html?highlight=outside#nginx-devpi-conf-nginx-site-config

**Comment by kierun** [comment]
Is there no way to do that without using nginx? I guess I could but so far my docker image just depends on Python and runs the server like so: `devpi-server --restrict-modify root --host 0.0.0.0 --port 3141` with kubernetes doing the ingress from http/https to the pod running the image.

Maybe it is not the best way to do it… ☺

**Comment by fschulze** [comment]
What is doing the TLS? Can't you set the header there? If not, there is the ``--outside-url`` option.

**Comment by kierun** [comment]
TLS is done by the kubernetes ingress. The kubernetes service maps the 443 and 80 ports to a pod running devpi on port 3141.

I just tried with `--outside-url` and all the content is fine.

Many thanks indeed.
