### ISSUE TITLE
devpi-server wheel includes test_devpi_server

### ISSUE THREAD

**Issue by jayvdb** [devpi/devpi#705]
Should `test_devpi_server` be included in the wheels at https://pypi.org/project/devpi-server/#files?

`packages=find_packages(),` at https://github.com/devpi/devpi/blob/master/server/setup.py#L48 looks like it might be unintentionally allowing the test package `test_devpi_server` be included in the generated wheel.

The `MANIFEST.in` is explicitly including `test_devpi_server` which is another sign that it should have been excluded by `packages=..`

**Comment by fschulze** [comment]
I've seen several places in devpi-web tests which also require it. I will try to gradually clean that up if possible.

**Comment by fschulze** [comment]
There is no way around keeping the ``test_devpi_server`` package, but the ``pytest_devpi_server`` plugin might go away. That is tracked in https://github.com/devpi/devpi/issues/780
