### ISSUE TITLE
Error 401 with mirrored pypi with basic auth

### ISSUE THREAD

**Issue by dequis** [devpi/devpi#710]
Hey there! Not sure if bug or just something I'm doing wrong.

My company has a private pypi index with http basic auth, specified in the example below `https://user:pass@pip.example.com/`.

I'm setting up a laptop cache like this:

```
devpi login root --password ''
devpi index example type=mirror mirror_url=https://user:pass@pip.example.com/ bases=root/pypi
devpi use --set-cfg root/example
```

Public pypi packages appear to work just fine (most of the time. i had a spurious 502 error once that i couldn't reproduce)

Fetching package lists and versions from the private index is also working fine, but the actual downloading of packages doesn't pass the user/pass through:

```
$ pip install --user somelib
Looking in indexes: http://localhost:3141/root/example/+simple/
Collecting somelib
Could not install packages due to an EnvironmentError: 502 Server Error: Bad Gateway for url: http://localhost:3141/root/example/+f/cdc/a8022e7cbb68a/somelib-3.0.0-py3-none-any.whl
```

Logs show a 401 error for the upstream fetch:

```
2019-09-19 11:57:46,535 INFO  [req52] GET /root/example/+simple/somelib/
2019-09-19 11:57:46,579 INFO  [req53] GET /root/example/+f/cdc/a8022e7cbb68a/somelib-3.0.0-py3-none-any.whl
2019-09-19 11:57:46,785 ERROR [req53] [Wtx17] error 401 getting https://pip.example.com/packages/somelib-3.0.0-py3-none-any.whl
```

Version:

```
$ devpi --version
devpi-client 5.0.0

current devpi server: http://localhost:3141/
    devpi-server 5.1.0
```

No plugins.

Upstream pypi server:

>This instance is running version 1.2.1 of the [pypiserver](https://pypi.python.org/pypi/pypiserver) software.

**Comment by fschulze** [comment]
This usecase isn't supported yet. We would need to extract the username and password from the mirror url and add it to the links returned for the simple pages. But this has several security issues which people need to be aware of (the password is leaked in several places), which is why I'm reluctant to just add this functionality. Doing it right would mean quite a lot of work and it could still go wrong. I would instead suggest something like https://tinyproxy.github.io/ running on your Laptop which adds the authorization header for you.

A side note, mirrors don't have ``bases``, only regular indexes do.

**Comment by dequis** [comment]
Thanks for the quick reply!

>But this has several security issues which people need to be aware of (the password is leaked in several places)

Hmm, such as logs, or what else do you have in mind?

I think for the laptop mirror use case that wouldn't be an issue, so maybe we could go for a warning text in the documentation for a setting that enables this behavior?

>A side note, mirrors don't have bases, only regular indexes do.

Oh, okay, I thought that was needed to have it lookup and cache packages in the root pypi when they don't exist in the private repo. Is that done automatically?

**Comment by fschulze** [comment]
> > But this has several security issues which people need to be aware of (the password is leaked in several places)
> 
> Hmm, such as logs, or what else do you have in mind?
> 
> I think for the laptop mirror use case that wouldn't be an issue, so maybe we could go for a warning text in the documentation for a setting that enables this behavior?

For the laptop usecase it would be fine, but once something like this is available people start using it and the password will leak via devpi-web and the json interface. There is no telling where it can end up.

With tinyproxy this should be relatively quick to fix without any of these issues.

> > A side note, mirrors don't have bases, only regular indexes do.
> 
> Oh, okay, I thought that was needed to have it lookup and cache packages in the root pypi when they don't exist in the private repo. Is that done automatically?

You would have to create a regular index which has both mirrors as bases. There are some gotchas with whitelisting then though, the order of bases matters for example.

**Comment by fschulze** [comment]
No reply in more than 3 months. Feel free to reopen this issue if it isn't solved yet.

**Comment by TheFriendlyCoder** [comment]
Based on my understanding, basic auth for remote repositories was working in devpi-server for quite some time, but has just recently been broken. See https://github.com/devpi/devpi/issues/871 for details.
