### ISSUE TITLE
Hundreds of "failed to check mirror whitelist" warnings for private package

### ISSUE THREAD

**Issue by nickwilliams-eventbrite** [devpi/devpi#722]
We have a Devpi index configured as follows:
* Name: `internal/stable`
* Non-volatile
* Mirroring `root/pypi`
* `mirror_whitelist='*'`

We have uploaded several internal packages to this index.

When we run the command `devpi list django`, we get a correct list of its files and no warnings in the Devpi log output. When we run the command `devpi list our-internal-package`, we get a correct list of its files and HUNDREDS of warnings in the Devpi log output that looks like this:

```
2019-09-29 14:51:21,360 WARNING: [req24333] [Rtx13944] Failed to check mirror whitelist. Assume it does not exists (cached not found for project our-internal-package)
```

This happens _every time_ we run `devpi list our-internal-package`. It happens only for internal packages. It happens for all internal packages. The number of warnings varies from ~10 warnings per `devpi list` call to > 100 warnings per `devpi list` call. Everything is working correctly, so the warning appears to be a false warning. This is going to blow up our logs with these warning and we won't be able to see real problems through the noise.

Perhaps we've configured something wrong, but this seems like a bug (or, at the very least, a documentation bug, if we can change something to stop this from happening).

**Comment by nickwilliams-eventbrite** [comment]
Awesome, thanks for fixing that so quickly!

I'm new to using Devpi, so I'm not familiar with its release cycle. How soon should I expect this fix in PyPi? Next few weeks? Or perhaps it's a good candidate for picking into a 5.1.1 patch release?

Thanks again for fixing this so quickly! Wow! :-)

**Comment by fschulze** [comment]
I'm currently in release preparations for 5.2.0, that's one of the reasons this was fixed so quickly. I hope to release it this week.

**Comment by nickwilliams-eventbrite** [comment]
Awesome, thanks! I'll be looking out for it!
