### ISSUE TITLE
predictable download url

### ISSUE THREAD

**Issue by scauglog** [devpi/devpi#726]
link to download package (.egg, .tar.gz, ...) on the webui should be formed with the username, repo name and package. It should not contain randomly generated part.

- current download link: http://localhost:3141/myuser/myrepo/+f/3ce/bf885d4dba0e8/my_package-0.0.1-py2.7.egg

- proposed download link: 
http://localhost:3141/myuser/myrepo/my_package-0.0.1-py2.7.egg

**Comment by fschulze** [comment]
It isn't random, it is based on the content. And pypi.org does the same. When using pip you don't need a predictable download URL. I don't see any reason to implement this. If you really want this, then you could write a plugin and use it from a custom theme.

**Comment by scauglog** [comment]
Thanks for the tips I will look to plugin an theme.
FYI I need this because I build my package to .egg or .zip which is the only way apache spark support them and pip won't download those. In production we use artifactory and we have a predictable URL to download package. I needed a more lightweight pypi server for development and local that still work with the CD tool chain.

**Comment by fschulze** [comment]
@scauglog You can take a look at https://github.com/devpi/devpi-lockdown to see how a devpi-web plugin can add new routes and views (we use Pyramid, [see their docs](http://docs.pylonsproject.org/projects/pyramid/en/1.10-branch/)). In ``setup.py`` is the necessary ``entry_point`` and ``devpiserver_pyramid_configure`` in ``main.py`` is the hook into devpi-web to add stuff to the Pyramid config. The ``includeme`` function is a Pyramid convention used by the ``pyramid_config.include`` call. The theme is necessary to replace the links with the new routes.
