### ISSUE TITLE
attrs dependency missing from devpi-web

### ISSUE THREAD

**Issue by EvaSDK** [devpi/devpi#729]
Trying to upgrade my Docker images here,

my current setup is to have a base image with just devpi-server and devpi-web extend that image. However this leads to a situation where devpi-web dependencies allow me to generate an image of devpi-web-4.0.0 with devpi-server-4.9.0. This should work fine as far as I can tell except for the fact that `attrs` usage was introduced in the last release and it cannot be found as it is only listing in devpi-server-5.2.0 dependencies.

**Comment by fschulze** [comment]
devpi-web 4.0.0 requires devpi-server 5.2.0 anyway.
