### ISSUE TITLE
Simple indexes with "simple/" in addition or as an alternative to /+simple/

### ISSUE THREAD

**Issue by henryborchers** [devpi/devpi#730]

**Comment by fschulze** [comment]
> Is there any way to make the simple indexes to devpi hosted repositories use "/simple/" instead of "/+simple/" URL?

With a webserver in front, yes. For nginx the keyword is ``rewrite``: http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite

Unless there is a compelling argument, I don't think this should be added to devpi-server. The reason we use ``+`` in front is to avoid naming collisions. That URL isn't meant for direct use. In devpi-web it is linked and ``devpi`` provides tools to set it in pip.conf etc.
