### ISSUE TITLE
Configurable validity of login sessions in Server

### ISSUE THREAD

**Issue by meyer89** [devpi/devpi#736]
Right now there is a hard-coded property LOGIN_EXPIRATION in devpi_server/auth.py. In my batch jobs it might happen that there is a long period of time between login and upload of a new package. 

What do you think about making the property LOGIN_EXPIRATION configurable with an environment variable? There might be other reasons to change the validity without manual editing of the code.

**Comment by fschulze** [comment]
Is there actually more than 10 hours between login and upload? Is there no way to create the packages and do login and upload shortly after another? ``devpi upload`` takes paths as arguments for existing files to upload, so you can build your packages and upload them afterwards.

We also want to implement tokens like pypi #699 which would fix this in another way.

**Comment by meyer89** [comment]
Yes, it is. I use devpi-builder for process automation and it does the login once in the beginning and trys to use the login session afterwards. With a long list of packages to update it might take a really long time, especially because I use emulation for different arch.

I see there are multiple possible solutions to my problem, and only one is to extend the session validity. Right now my workaround is to invoke devpi-builder for each package and create a new login session. However, I would like to have a longer validity of the session and just use one single command for devpi-builder.

**Comment by fschulze** [comment]
Tracked in #699.
