### ISSUE TITLE
devpi-server runs at 100% all the time inside my Docker container

### ISSUE THREAD

**Issue by JeffLabonte** [devpi/devpi#737]
I have dockerized devpi-server for my personal use, and I have noticed that it runs at 100% all the time so I reduced the cpus rights of the devpi container as a workaround for now!

I seem to be running the latest version available, here is a screenshot of a `pip freeze`

![image](https://user-images.githubusercontent.com/9425955/68338201-f51fcc00-00af-11ea-8917-24ba7a1b4824.png)

**Comment by fschulze** [comment]
How long did you let it run from first startup? After a fresh install devpi-web will index all the names from root/pypi which takes quite some time. The log should show progress info on that. You can also check the json output of the status page: ``curl -H "Accept: application/json" http://localhost:3141/+status`` (or an equivalent URL to check from the outside). If the ``devpi_web_whoosh_index_queue_size`` is above 0, then it is still indexing something.

**Comment by JeffLabonte** [comment]
You are right! What is it indexing exactly? As far as my knowledge on this application goes, it is basically a proxy that takes my request to install package from Pypi. Am I correct?

**Comment by fschulze** [comment]
Yes, in addition the requested files are stored locally.

The indexing is for the search functionality in the web interface. If you don't need that, you can use ``--indexer-backend null``. You should run ``devpi-web-clear-index`` to remove the index files in that case.

**Comment by JeffLabonte** [comment]
Cool! Thank for the info!

**Comment by JeffLabonte** [comment]
It would be great to document it somewhere tho :)
