### ISSUE TITLE
RuntimeError: Could not start process devpi-server

### ISSUE THREAD

**Issue by CSimpiFoN** [devpi/devpi#740]
devpi-server version 5.2.0 cannot be started on a CentOS 7.7 server with Python3.

`# devpi-server --version`
`5.2.0`

`# devpi-server --start`
`2019-11-15 11:10:00,088 INFO  NOCTX Loading node info from /root/.devpi/server/.nodeinfo`
`2019-11-15 11:10:00,089 INFO  NOCTX wrote nodeinfo to: /root/.devpi/server/.nodeinfo`
`/usr/local/lib/python3.6/site-packages/devpi_server/bgserver.py:31: UserWarning: Use of --start, --stop, --status and --log is deprecated. You should use a process manager of your OS, for example: systemd for Linux, Windows Services, launchd for macOS or http://supervisord.org/`
`Also see the devpi-gen-config option to create example configuration files for such services.`
`  "Use of --start, --stop, --status and --log is deprecated. "`
`starting background devpi-server at http://localhost:3141`
`/root/.devpi/server/.xproc/devpi-server$ /usr/bin/devpi-server`
`process 'devpi-server' started pid=111378`
`Traceback (most recent call last):`
`  File "/usr/bin/devpi-server", line 11, in <module>`
`    sys.exit(main())`
`  File "/usr/local/lib/python3.6/site-packages/devpi_server/main.py", line 80, in main`
`    return _main(pluginmanager, argv=argv)`
`  File "/usr/local/lib/python3.6/site-packages/devpi_server/main.py", line 164, in _main`
`    return bgserver.start(args, argv[1:])`
`  File "/usr/local/lib/python3.6/site-packages/devpi_server/bgserver.py", line 86, in start`
`    self.xproc.ensure("devpi-server", prepare_devpiserver)`
`  File "/usr/local/lib/python3.6/site-packages/devpi_server/vendor/xprocess.py", line 171, in ensure`
`    raise RuntimeError("Could not start process %s" % name)`
`RuntimeError: Could not start process devpi-server`

The service was installed by pip3
`# pip3 install devpi-server`

**Comment by fschulze** [comment]
> devpi-server version 5.2.0 cannot be started on a CentOS 7.7 server with Python3.

> `# devpi-server --start`

Don't use this option. See the warnings it outputs for more details:

> `/usr/local/lib/python3.6/site-packages/devpi_server/bgserver.py:31: UserWarning: Use of --start, --stop, --status and --log is deprecated. You should use a process manager of your OS, for example: systemd for Linux, Windows Services, launchd for macOS or http://supervisord.org/`
> `Also see the devpi-gen-config command to create example configuration files for such services.`

Try with only `# devpi-server` to see what is actually happening.

**Comment by SuperSandro2000** [comment]
The quickstart guide says you should do it like this https://devpi.net/docs/devpi/devpi/stable/+d/quickstart-pypimirror.html

**Comment by fschulze** [comment]
Which reminds me that I have to upload the current docs. See this instead: https://github.com/devpi/devpi/blob/master/doc/quickstart-pypimirror.rst

**Comment by CSimpiFoN** [comment]
Thanks for the update guys! I managed to make it work at last!

**Comment by fschulze** [comment]
Out of curiosity, what was the issue?

**Comment by CSimpiFoN** [comment]
I ran it with the following command:
`/usr/bin/python3 /usr/local/bin/devpi-server --port 8080 --config /etc/devpi/devpi-server.yml`
