### ISSUE TITLE
remove devpi-client's tox dependency for non-development install

### ISSUE THREAD

**Issue by cjw296** [devpi/devpi#746]
I'm confused why tox is a dependency of devpy-client. It seems unrelated to devpi-client's use case and is a pretty heavy dependency that [causes ](https://github.com/tox-dev/tox/pull/1472) [issues](https://github.com/tox-dev/tox/issues/1473).

Would it be possible to remove 'tox' and hopefully 'check-manifest' and maybe even 'pkginfo', or at least make them development-only dependencies?

**Comment by fschulze** [comment]
We might be able to get rid of the tox dependency, since detox is obsolete now and we could just use subprocess now.

The check-manifest and pkginfo packages are used by the upload command and are essential to its functionality. It would be very confusing for users if they would have to install these manually to be able to use ``devpi upload``.

**Comment by fschulze** [comment]
Oh, forgot to mention that ``devpi test`` requires tox.

**Comment by wimglenn** [comment]
Perhaps it could be made into an optional dependency, like `devpi-client[test]`.  I have no interest to use `devpi test` but I do want the twine-like stuff  `use`, `login`, `upload`...

**Comment by fschulze** [comment]
@wimglenn are you aware, that for uploads you can use twine directly? Maybe that is a better solution for you? For other devpi maintenance you would still need devpi-client. We may also be extending the devpi-web UI for some basics in the future.

**Comment by wimglenn** [comment]
Yes, I am aware that twine works for upload, but the devpi-client has several other useful features too..

**Comment by cjw296** [comment]
@fschulze - can twine upload docs to devpi? If so, how? If not, are there any other tools beside devpi-client that can?

**Comment by fschulze** [comment]
I haven't tried twine for docs, but my suspicion is that it doesn't, because PyPI doesn't support that for quite some time now, but the protocol is almost the same, so it might work.

Using ``python setup.py ...`` might also still work.

**Comment by fschulze** [comment]
No reply in more than 3 months. Feel free to reopen this issue if it isn't solved yet.

**Comment by cjw296** [comment]
@fschulze - not sure what reply you were waiting for but nothing has changed and this issue is still a problem. I think @wimglenn's suggestion for `devpi-client[test]`, given that `tox` is pretty huge and onerous dependency.

It looks like the PR is stalled on @wimglenn making the changes you requested, not sure if it makes sense to just track there or to re-open this issue?

**Comment by fschulze** [comment]
Feel free to make a new PR with the required changes. I'm happy to accept it as described, but won't do the work myself.

**Comment by cjw296** [comment]
That's not quite as clear an answer as I was hoping for, but inferring from your reply: you would like this issue to remain closed and just track the problem on #747?

**Comment by fschulze** [comment]
I should have written: "No reply in more than 3 months. Feel free to update the PR or create a new one with the requested changes if you want this change to be added to devpi-client."
