### ISSUE TITLE
Pypi Caching

### ISSUE THREAD

**Issue by kurtabersold** [devpi/devpi#749]
I have some Python2 applications that won't be ported to Python3, and I want to ensure I will have cached copies of the necessary dependencies before the end of support for python2.

If a package gets deleted from pypi, will the cached copy on devpi still be available, or will it also get deleted?

**Comment by fschulze** [comment]
It's complicated 😉 

If a single release is removed, then the reference to it on the simple page is removed, but the file itself is kept in place. So on install with pip you will get a 404 error, but you can still find the file on the filesystem.

If the whole project is removed, then the files will still be served by devpi and you will only see a mention of serving stale data in the logs.

I would recommend to use ``pip freeze`` to create a snapshot of the installed versions and write a shell loop/script which calls ``devpi push --index root/pypi [spec] [targetindex]`` for each line on it's output where ``[spec]`` is something like ``devpi-server==5.2.0`` from the ``pip freeze`` output and the ``[targetindex]`` is a new index of yours where you want to have a copy of the original file. That way you can be assured that you keep the releases you need, even with a ``devpi-export``/``devpi-import`` cycle.

**Comment by fschulze** [comment]
I don't think any releases will be removed because of Python 2 EOL, but one can never know. There have been instances where packages were removed for more trivial reasons.

**Comment by fschulze** [comment]
No reply in more than 3 months. Feel free to reopen this issue if it isn't solved yet.
