### ISSUE TITLE
How to regular clean  the package？

### ISSUE THREAD

**Issue by ZhangSIming-blyq** [devpi/devpi#751]
Here I want to clean my package on /root/dev index, I use a simple shell script:
```shell
#!/bin/bash
#use devpi's dev index
devpi use https://devpi.com/root/dev
devpi login root --password="xxxxxxxx"
#Guaranteed on dev index
devpi use | grep "current devpi index" | grep "/root/dev"
if [ $? != 0 ];then
    exit 1
fi
echo -e "current devpi index is /root/dev\n"

#delete packages use loop
for package in `devpi list | xargs`
do
    devpi remove -y $package >/dev/null 2>&1
    if [ $? == 0 ];then
        echo "Delete package $package on dev index successfully."
    fi
done
```

I want to clean the package which is existed more than 7 days, but how to judge the time about upload?

**Comment by ZhangSIming-blyq** [comment]
Do devpi command line support to find the date of package upload?

**Comment by fschulze** [comment]
You can do that with ``getjson``. I used``devpi use https://m.devpi.net`` and then ``devpi getjson /fschulze/dev/devpi-server`` to get json which for each release includes a ``log`` which has such information.

**Comment by ZhangSIming-blyq** [comment]
> You can do that with `getjson`. I used`devpi use https://m.devpi.net` and then `devpi getjson /fschulze/dev/devpi-server` to get json which for each release includes a `log` which has such information.

Thanks, I'll try.

**Comment by fschulze** [comment]
No reply in more than 3 months. Feel free to reopen this issue if it isn't solved yet.
