### ISSUE TITLE
how to modify devpi-server default mirror_url ?

### ISSUE THREAD

**Issue by lengxu** [devpi/devpi#753]
I want to change default reading remote: https://files.pythonhosted.org/packages url to http://mirrors.aliyun.com/pypi/simple/
What shall I do?

previously on :

$ devpi index root/pypi

```
http://pypi.mydomain.com/root/pypi:
  type=mirror
  volatile=False
  mirror_url=http://mirrors.aliyun.com/pypi/simple/
  mirror_web_url_fmt=https://pypi.org/project/{name}/
  title=PyPI
```

this is devpi-client,i want change devpi-server by default.

tks.

**Comment by fschulze** [comment]
This looks correct to me. The output you posted are the current settings of your ``root/pypi`` index from your devpi server, so it points to ``http://mirrors.aliyun.com/pypi/simple/``. All packages should no be fetched from that URL. The devpi-server log output should show that as well.

Maybe I have misunderstood what you want to achieve.

**Comment by flashfiring** [comment]
> I want to change default reading remote: https://files.pythonhosted.org/packages url to http://mirrors.aliyun.com/pypi/simple/
> What shall I do?
> 
> previously on :
> 
> $ devpi index root/pypi
> 
> ```
> http://pypi.mydomain.com/root/pypi:
>   type=mirror
>   volatile=False
>   mirror_url=http://mirrors.aliyun.com/pypi/simple/
>   mirror_web_url_fmt=https://pypi.org/project/{name}/
>   title=PyPI
> ```
> 
> this is devpi-client,i want change devpi-server by default.
> 
> tks.

![image](https://user-images.githubusercontent.com/32921558/70909332-3b216580-2048-11ea-91d1-45d9d9146ead.png)
how you configure it ? tks

**Comment by fschulze** [comment]
@flashfiring you already did according to the output you marked. The ``mirror_url`` already points to ``http://mirrors.aliyun.com/pypi/simple/``

**Comment by fschulze** [comment]
No reply in more than 3 months. Feel free to reopen this issue if it isn't solved yet.
