### ISSUE TITLE
how to configure parameters of target url

### ISSUE THREAD

**Issue by flashfiring** [devpi/devpi#758]
![image](https://user-images.githubusercontent.com/32921558/70907689-75890380-2044-11ea-909d-e0a2aad0b07b.png)

the value of mirror_url is "https://pypi.org/simple/" by default.
But how to configure it to something else .

**Comment by fschulze** [comment]
``devpi index root/pypi mirror_url=https://...`` you need to be logged in as the ``root`` user with ``devpi login root``.

**Comment by flashfiring** [comment]
After i have logged as the root, can you describe the command in detail, thang you.

**Comment by fschulze** [comment]
I already did, put the URL directly after ``devpi index root/pypi mirror_url=`` and it will change it on the server.

**Comment by fschulze** [comment]
No reply in more than 3 months. Feel free to reopen this issue if it isn't solved yet.
