### ISSUE TITLE
How to update favicon and page title of devpi web

### ISSUE THREAD

**Issue by dullahan8** [devpi/devpi#761]
I am running two instances of the devpi server for my users. A user pointed out it would be a good idea to make the two instances be visually distinguishable from each other. Is it possible to update the page title where it says "devpi" beside the search bar of the web page and the favicon and where would I do it?

**Comment by fschulze** [comment]
You can specify a folder with the ``--theme`` option. In there you create a folder ``templates`` and in there a file ``macros.pt``. In that file you put:
```
<metal:logo define-macro="logo">
    <h1><a href="${request.route_url('root')}">devpi</a></h1>
</metal:logo>
```
After that you can modify it any way you like.
If you want an image, put it in a new ``static`` folder in your theme folder and use ``${request.theme_static_url('logo.jpg')}`` to generate the url in your macro.

There is no direct support to change the favicon, I do that via the nginx I have in front of devpi-server anyway.

**Comment by dullahan8** [comment]
Thanks! I got it working.
