### ISSUE TITLE
Https / X-Original-url potentially not respected when using `devpi use` with Cloudflare's Argo Tunnel

### ISSUE THREAD

**Issue by fgmehlin** [devpi/devpi#765]
Hey,

There seems to be an problem with using `https` to connect to devpi indexes. Currently, our setup looks like the following:

On a kubernetes cluster, we have: [Cloudflare argo tunnel] -> [Nginx] -> [Devpi-Server]

We want to connect to our devpi-server over https, hence using something like 

```
➜  devpi use https://pypi.myserver.com/my-user/prod/ 
Using existing basic auth for '<URL 'https://pypi.myserver.com/my-user/prod/'>'.
The password is stored unencrypted!
current devpi index: http://pypi.myserver.com/my-user/prod (not logged in) # Here devpi-server returns the index's address over http. 
``` 
So, since devpi-server seems to return the index's address over `http`, `devpi login` does not work, since it tries to connect to the `http` index.

```
➜ devpi login my-user --password my-password
*redirected: https://pypi.myserver.com/+login    # Abnormal redirection
GET https://pypi.myserver.com/+login
404 Not Found: The resource could not be found.

predicate mismatch for view PyPIView (request_method = POST) 
```

We have then noticed that devpi-server uses `waitress` to serve as wsgi server:
https://github.com/devpi/devpi/blob/master/server/devpi_server/main.py#L199

From waitress documentation, it seems that the `serve` function should add the `url_scheme='https'`, following what is documented [here](https://docs.pylonsproject.org/projects/waitress/en/latest/reverse-proxy.html).

So in the case of `devpi_server/main`, there should potentially be an additional `kwargs['url_scheme'] = 'https'` added in the function that serves waitress.

I haven't validated that hypothesis yet, will try to do so and update the issue.

Versions:
devpi-client: 5.1.1
devpi-server: 5.3.1
python 3.7

**Comment by fgmehlin** [comment]
I should also add that, currently we fix this issue by forcing the scheme to be `https`. I.e. in https://github.com/devpi/devpi/blob/master/client/devpi/main.py#L140

We've added:

```
            if url.startswith("http://"):
                url = "https" + url[4:]
```

which, for now, works for our purpose.

**Comment by fschulze** [comment]
You have to set the X-Outside-URL proxy header in nginx: https://devpi.net/docs/devpi/devpi/stable/+doc/quickstart-server.html?highlight=outside#generating-example-config-files-for-supervisor-nginx-cron-launchd

**Comment by fgmehlin** [comment]
Thanks for the quick reply. We have added the `x-outside-url` but this doesn't fix the issue. 

Sorry, the title was a bit misleading, this was more a fix for our purpose, rather than a general one. The problem is that the header is not respected/passed to waitress.

Maybe this is the issue: https://github.com/devpi/devpi/blob/master/server/devpi_server/views.py#L407 uses `route_url` where the header is not passed ?

**Comment by fschulze** [comment]
When ``x-outside-url`` is correctly set then all URLs generated by devpi should be properly rewritten. I have several devpi instances behind https doing that. A curl to ``/+api`` on your server should already contain the correct URL for login, it is what ``devpi use`` sees. If that URL is already wrong, then the header isn't passed in correctly or has the wrong value.

**Comment by fgmehlin** [comment]
OK, you are right and the problem is something else. 

What we did now is forcing the scheme to `https` in nginx's `x-outside-url header` and it seems to work:

`proxy_set_header X-outside-url https://$host;`

I think that the problem comes from the cloudflare argo tunnel, which seems to mess with the https URL and sets it to http.

The issue can be closed, I think. Thank you for your help @fschulze 

I will edit the title to include "argo tunnel", in case someone would face the same issue and put the blame here :-). 

Cheers!
