### ISSUE TITLE
Devpi loads whole package into memory

### ISSUE THREAD

**Issue by matthiasha** [devpi/devpi#775]
When downloading a package from Devpi, it loads the whole archive into memory in the following line:

https://github.com/devpi/devpi/blob/c9895ccce9e968c347aef3f3c02c4486787a0a8a/server/devpi_server/views.py#L1170

I believe streaming the file in chunks instead would 
* improve the speed: download will start before the whole package has been read from disk
* use considerably less memory

**Comment by fschulze** [comment]
This isn't trivial, because the storage backend might not provide a chunked file. For example devpi-postgresql. I think it might be possible in many cases though.
The default recommended installation with nginx in front doesn't have this issue, because files are served directly by nginx when the default sqlite backend of devpi is in use.

**Comment by hansingt** [comment]
We do have the same problem (as I've reported here: https://github.com/devpi/devpi/issues/782 sorry for the duplicate!) I've also posted a suggestion to solve this issue with postgresql: The `COPY` extension which is supported by `pg8000` as well.
If any other database backends are planned which don't support this, one could "emulate" it, by doint multiple queries which only get a substring of the whole content. Might not be as performant as the `COPY` extension, but still possible. Anyway, it's always an option to not store the files in the database anyway.

**Comment by fschulze** [comment]
@hansingt there are multiple places where currently the whole package content is accessed or passed on. A PR for devpi-postgresql to use the ``COPY`` extension would be a first welcome step.
You mentioned that the checksum is calculated several times in #782. Could you point out where that happens and you think it is unnecessary? There could be cases where it is needed when the file is stored on the filesystem, but not when it comes from the database.
As I already wrote, completely removing this will be quite a bit of work. So far nobody was willing to invest the time/money, instead the servers just got provided more RAM, which was cheaper so far.

**Comment by hansingt** [comment]
@fschulze I've just done a quick search now, as I don't recall all places by now. For example: The method `store` of the filestore gets the `dir_hash_spec` passed into it or calculates it from the file contents but it does not pass it to the `file_set_content` method:
https://github.com/devpi/devpi/blob/921bb905630753d92e3e1e9d13487a4f74bb080d/server/devpi_server/filestore.py#L116
Thus, this method will calculate the hash again. This is just a simple bug, which can be easily fixed, nevertheless, especially, if an error occurrs, the `get_checksum_error` method also calculates the hash again, even if it might already be calculated before.
https://github.com/devpi/devpi/blob/921bb905630753d92e3e1e9d13487a4f74bb080d/server/devpi_server/filestore.py#L262

This could be avoided by e.g. not passing the contents but a wrapper object with a cached `checksum` property. This ensures, that for a given content, the checksum is only calculated once.
Additionally, this wrapper prepares for easier migration to streams.

**Comment by fschulze** [comment]
For future reference: https://github.com/tlocke/pg8000#copy-from-and-to-a-file

**Comment by fschulze** [comment]
The devpi-server side was relatively easy, the devpi-postgresql side was much harder. With ``COPY`` you can't just use plain binary files. You have to send in specific formats. The ``text`` and ``csv`` formats would have required slow conversion to escape any non ascii data. The ``binary`` format requires wrapping the file data in a header and a footer. Doing that efficiently was quite some work.

This can be tested with https://m.devpi.net/fschulze/dev/devpi-postgresql/3.0.0.dev0 and https://m.devpi.net/fschulze/dev/devpi-server/6.5.0.dev0.

**Comment by fschulze** [comment]
This is included in devpi-server 6.5.0 and devpi-postgresql 3.0.0.
