### ISSUE TITLE
Is `requests-only: false` interpreted the same as `requests-only: foo`?

### ISSUE THREAD

**Issue by aigr** [devpi/devpi#776]
After installing devpi-server, putting in some packages and then letting it sit for a while to get the queue to drop down to zero, I get the error message

```
No changes processed by plugins for more than 30 minutes
```

And `server status` is set to `fatal`

What does that even mean? Any clues about what I should change?

### pip list
```
Package             Version
------------------- ----------
apipkg              1.5
appdirs             1.4.3
argon2-cffi         19.2.0
attrs               19.3.0
beautifulsoup4      4.8.2
bleach              3.1.0
certifi             2019.11.28
cffi                1.14.0
Chameleon           3.6.2
chardet             3.0.4
check-manifest      0.40
cmarkgfm            0.4.2
defusedxml          0.6.0
devpi-client        5.1.1
devpi-common        3.4.0
devpi-server        5.4.0
devpi-web           4.0.2
docutils            0.16
execnet             1.7.1
filelock            3.0.12
hupper              1.9.1
idna                2.8
importlib-metadata  1.5.0
itsdangerous        1.1.0
packaging           20.1
passlib             1.7.2
PasteDeploy         2.1.0
pip                 20.0.2
pkg-resources       0.0.0
pkginfo             1.5.0.1
plaster             1.0
plaster-pastedeploy 0.7
pluggy              0.13.1
py                  1.8.1
pycparser           2.19
Pygments            2.5.2
pyparsing           2.4.6
pyramid             1.10.4
pyramid-chameleon   0.3
python-dateutil     2.8.1
readme-renderer     24.0
repoze.lru          0.7
requests            2.22.0
ruamel.yaml         0.16.7
ruamel.yaml.clib    0.2.0
setuptools          45.2.0
six                 1.14.0
soupsieve           1.9.5
strictyaml          1.0.6
toml                0.10.0
tox                 3.14.3
translationstring   1.3
urllib3             1.25.8
venusian            3.0.0
virtualenv          16.7.9
waitress            1.4.3
webencodings        0.5.1
WebOb               1.8.6
wheel               0.29.0
Whoosh              2.7.4
zipp                1.1.0
zope.deprecation    4.4.0
zope.interface      4.7.1
```

This is on Debian 9.12.

**Comment by fschulze** [comment]
On the ``+status`` page (clicking on the server state badge) should be these two infos:
- Current serial
- Processed events serial

If "Processed events serial" is below "Current serial" and doesn't change (which the error indicates), then no database change events are processed. You should check your devpi-server log to see if there are any exceptions related to event processing. These events are used to trigger search index updates in devpi-web. Some other devpi-server plugins use them as well, but you don't have any installed.

**Comment by aigr** [comment]
Yes, the `Current serial` is currently at 480 and the `Processed events serial` at 477.

I checked `/opt/f/devpi/server/.xproc/devpi-server/xprocess.log`, which I think is the server log, but couldn't find any errors

```
$ grep -vF INFO /opt/f/devpi/server/.xproc/devpi-server/xprocess.log
Serving on http://0.0.0.0:8990
```

There's now also another error message in the status panel

```
Warning: The event processing hasn't been in sync for more than 1 hour 
```

My current configuration is pretty minimal

```
# -*- mode: yaml -*-
devpi-server:
  host: 0.0.0.0
  port: 8990
  serverdir: /opt/f/devpi/server
  secretfile: /home/devpi/.devpi/server/server.secret
  requests-only: false
```

**Comment by fschulze** [comment]
Are you using the ``--start`` option to run devpi-server? Then ``/opt/f/devpi/server/.xproc/devpi-server/xprocess.log`` is the log.
I think you have to remove the ``requests-only: false`` part. It is possible that the parser misinterprets it and only looks for existance and not the actual value. If that is the case, then please update the subject of this ticket accordingly, so I can fix that issue.

**Comment by aigr** [comment]
I run devpi from systemd as
```
[Unit]
Description=devpi
Requires=network-online.target
After=network-online.target

[Service]
User=devpi
Group=alice
WorkingDirectory=/opt/f/devpi/server
Restart=on-success
ExecStart=/home/devpi/env/bin/devpi-server -c /home/devpi/.devpi/server/server.conf

[Install]
WantedBy=multi-user.target
```

I changed the server config and removed the `requests-only` part entirely. After a restart my `server status` immediately went to `ok`.

Thanks!

**Comment by fschulze** [comment]
Then your server log is also managed by systemd (or rather journald). The ``xprocess.log`` is most likely a remnant if you ever used ``--start``. Since the config was the issue there wouldn't be any error messages in that log either.

**Comment by aigr** [comment]
Ah. I could very well have run `--start` some time previously.

**Comment by fschulze** [comment]
I have added a test for ``requests-only: false`` and it works correctly.
