### ISSUE TITLE
Devpi-Server ignores port using `--port`

### ISSUE THREAD

**Issue by VikashKothary** [devpi/devpi#777]
#### Issue
I'm trying to set the port which devpi runs on. I run
`devpi-server --start --host 0.0.0.0 --port $DEVPI_PORT`
I expect that it would use my port but it just uses the default.

#### Thoughts
https://github.com/devpi/devpi/blob/921bb905630753d92e3e1e9d13487a4f74bb080d/server/devpi_server/config.py#L95 Allows devpi to use options such as `--port`.

It doesn't seem to be used. I think It's meant to be added here. https://github.com/devpi/devpi/blob/921bb905630753d92e3e1e9d13487a4f74bb080d/server/devpi_server/init.py#L38
#### Python and OS
Python: 3.7
OS: Debian GNU/Linux 10 (in Docker)

#### pip list
Package                    Version  
-------------------------- ---------
apipkg                     1.5      
appdirs                    1.4.3    
argon2-cffi                19.1.0   
beautifulsoup4             4.8.1    
bleach                     3.1.0    
certifi                    2019.9.11
cffi                       1.12.3   
Chameleon                  3.6.2    
chardet                    3.0.4    
check-manifest             0.39     
cmarkgfm                   0.4.2    
defusedxml                 0.6.0    
devpi-cleaner              0.2.0    
devpi-client               5.0.0    
devpi-common               3.4.0    
devpi-findlinks            2.0.0    
devpi-ldap                 1.2.2    
devpi-lockdown             1.0.1    
devpi-plumber              0.5.1    
devpi-semantic-ui          0.2.2    
devpi-server               5.0.0    
devpi-slack                0.1.3    
devpi-web                  3.5.2    
docutils                   0.15.2   
execnet                    1.7.1    
filelock                   3.0.12   
hupper                     1.8.1    
idna                       2.8      
importlib-metadata         0.23     
itsdangerous               1.1.0    
ldap3                      2.6.1    
more-itertools             7.2.0    
packaging                  19.2     
passlib                    1.7.1    
PasteDeploy                2.0.1    
pip                        19.2.3   
pkginfo                    1.5.0.1  
plaster                    1.0      
plaster-pastedeploy        0.7      
pluggy                     0.13.0   
progressbar2               3.47.0   
py                         1.8.0    
pyasn1                     0.4.7    
pycparser                  2.19     
Pygments                   2.4.2    
pyparsing                  2.4.2    
pyramid                    1.10.4   
pyramid-chameleon          0.3      
python-dateutil            2.8.0    
python-utils               2.3.0    
PyYAML                     5.1.2    
readme-renderer            24.0     
repoze.lru                 0.7      
requests                   2.22.0   
ruamel.yaml                0.16.5   
ruamel.yaml.clib           0.2.0    
setuptools                 41.2.0   
six                        1.12.0   
soupsieve                  1.9.4    
strictyaml                 1.0.5    
toml                       0.10.0   
tox                        3.14.0   
translationstring          1.3      
twitter.common.contextutil 0.3.11   
twitter.common.dirutil     0.3.11   
twitter.common.lang        0.3.11   
urllib3                    1.25.6   
venusian                   1.2.0    
virtualenv                 16.7.5   
waitress                   1.3.1    
webencodings               0.5.1    
WebOb                      1.8.5    
wheel                      0.33.6   
Whoosh                     2.7.4    
zipp                       0.6.0    
zope.deprecation           4.4.0    
zope.interface             4.6.0

**Comment by fschulze** [comment]
At least in devpi-server 5.4.0 this works as expected. It is referenced from addoptions there.

**Comment by VikashKothary** [comment]
Thanks @fschulze. Let me update my devpi-server and give it another go.

**Comment by VikashKothary** [comment]
I can confirm that the latest version works. Thanks for your help @fschulze.
