### ISSUE TITLE
Help connecting to remote devpi server over https

### ISSUE THREAD

**Issue by amuresia** [devpi/devpi#778]
Good day.
I am trying to utilise devpi client to deploy python packages to a remote devpi-server that has ssl configured 

nginx configuration:
```
upstream pypi-backend {
  server localhost:4040;
}

# Redirect HTTP to HTTPS
server {
  listen 80;
  listen [::]:80;
  server_name _;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name example.com;
  root /pypi/pypiserver;
  gzip             on;
  gzip_min_length  2000;
  gzip_proxied     any;

  proxy_read_timeout 60s;
  client_max_body_size 64M;

  ssl			      on;
  ssl_certificate             /etc/ssl/certs/server.crt;
  ssl_certificate_key         /etc/ssl/private/server.key;
  ssl_client_certificate      /etc/ssl/certs/ca.crt;
  ssl_verify_client	      optional;
  ssl_verify_depth            10;
  keepalive_timeout 	      10;
  ssl_session_cache           builtin:1000  shared:SSL:10m;
  ssl_protocols               TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers                 HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
  ssl_prefer_server_ciphers   on;
  error_log  		      /var/log/nginx/error.log debug;
  access_log                  /var/log/nginx/pypi.access.log;

  # try serving static files directly

  if ($ssl_client_verify = FAILED) {
        return 495;
      }

      if ($ssl_client_verify = NONE) {
        return 402;
      }

      if ($ssl_client_verify != SUCCESS) {
        return 403;
      }

  location ~ /\+f/ {
    error_page 418 = @pypi_backend;
    if ($request_method !~ (GET)|(HEAD)) {
      return 418;
    }

    expires max;
    try_files /+files$uri @pypi_backend;
  }

  # try serving docs directly
  location ~ /\+doc/ {
    try_files $uri @pypi_backend;
  }

  location / {
    error_page 418 = @pypi_backend;
    return 418;
  }

  location @pypi_backend {
    proxy_pass              http://pypi-backend; # Using the upstream definition
    proxy_redirect          off;
    proxy_set_header        Host $host;
    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-outside-url $scheme://$host:$server_port;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Host $server_name;
  }
}
```

I am trying to connect to one of the indexes that I created, from a remote server but I keep getting error code 402 which makes me believe that the ssl client certificate is not sent.
Command:
```
REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca.crt devpi use https://example.com: --client-cert=/etc/ssl/certs/client.crt
```
Output:
```
Traceback (most recent call last):
  File "/usr/local/bin/devpi", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/devpi/main.py", line 36, in main
    return method(hub, hub.args)
  File "/usr/local/lib/python3.6/dist-packages/devpi/use.py", line 377, in main
    current.configure_fromurl(hub, url, client_cert=args.client_cert)
  File "/usr/local/lib/python3.6/dist-packages/devpi/use.py", line 234, in configure_fromurl
    r = call_http_api(verify=False)
  File "/usr/local/lib/python3.6/dist-packages/devpi/use.py", line 226, in call_http_api
    verify=verify)
  File "/usr/local/lib/python3.6/dist-packages/devpi/main.py", line 143, in http_api
    auth=basic_auth, cert=cert, verify=verify)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='example.com', port=443): Max retries exceeded with url: /+api (Caused by SSLError(SSLError(336265225, '[SSL] PEM lib (_ssl.c:3524)'),))
```
The following curl command works fine
```
curl https://example.com/+api --key /etc/ssl/private/client.key --cert /etc/ssl/certs/client.crt --cacert /etc/ssl/certs/ca.crt -v
```
Output:
```
{
  "result": {
    "login": "https://example.com/+login",
    "authstatus": [
      "noauth",
      "",
      []
    ],
    "features": [
      "server-keyvalue-parsing"
    ]
  },
  "type": "apiconfig"
}
```
Could you please advise on how to get this up and running?
Please let me know if there are other steps that you would like me to run to troubleshoot the issue/ misconfiguration.

**Comment by fschulze** [comment]
Is that with a self signed certificate in addition to a client certificate? Self signed certificates are really problematic with Python and the requests library, we can't provide support with that. Client side certificates also turned out to be way more painful than the potential added security is worth. I use Let's Encrypt and [devpi-lockdown](https://pypi.org/project/devpi-lockdown/) instead. Recent versions of pip hide the password from the log output when using an index with authentication credentials.

**Comment by amuresia** [comment]
Thank you for the prompt reply @fschulze.
They are not self signed.
We managed to make a bit of progress by concatenating the contests of the cert and the key to one file 
```REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca.crt devpi use https://example.com:/user/index --client-cert=/etc/ssl/concat.crt```
which works ok and creates the file `.devpi/client/current.json`
```
{
  "client_cert": {
    "https://example.com:443/": "/etc/ssl/concat.crt",
  },
  "features": [
    "server-keyvalue-parsing"
  ],
  "index": "https://example.com/user/index",
  "login": "https://example.com/+login",
  "pypisubmit": "example.com/user/index/",
  "simpleindex": "https://example.com/user/index/+simple/"
}
```
However, the login fails :(
```
REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca.crt devpi login user --password=password
```
Output:
```
SSL verification failed 'https:/example.com/+login':
HTTPSConnectionPool(host='example.com', port=443): Max retries exceeded with url: /+login (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
```

I tried adding the below to the `client_cert` mapping
```
    "https://example.com:443/+login": "/etc/ssl/concat.crt"
```
as suggested here https://github.com/devpi/devpi/issues/534#issuecomment-510669447
but still no joy :(

Any idea on how to progress? I've noticed that `devpi login` doesn't take the `--client-cert` option. I'm a bit stuck yet again :(

**Comment by fschulze** [comment]
``devpi use`` will store the client cert info in ``~/.devpi/client/current.json`` as you already discovered and ``devpi login`` should then use it for requests to the server.

If you use a regular server side certificate, then try to remove the client certificate from the nginx config and see if you can login then. If that is the case, you have ruled out issues with the server certificate and you don't need ``REQUESTS_CA_BUNDLE``, that is only needed for self signed server certificates. From there you should try to get the client certificate working with curl first, but with only the ``--cert`` option. You should be able to find guides for that for nginx. Once that works, the same cert should work with devpi. That is at least what worked for me when I implemented it a few years ago. I never wrote a guide, because the problems with client certs were to numerous (it wasn't user friendly with browsers at all) and no one with a support contract had further interest in it.

**Comment by fschulze** [comment]
No followup in two years. Client certificate support will be removed in devpi-client 6.x as it doesn't work properly.
