### ISSUE TITLE
pg8000 ssl interface changed

### ISSUE THREAD

**Issue by fschulze** [devpi/devpi#783]
@JonathanRRogers  pg8000 1.14.0 has changed its ssl interface and I'm not sure how to adapt to it. Instead of options for wrap_socket it now wants an SSLContext object.

**Comment by JonathanRRogers** [comment]
> @JonathanRRogers pg8000 1.14.0 has changed its ssl interface and I'm not sure how to adapt to it. Instead of options for wrap_socket it now wants an SSLContext object.

Yes, I submitted a pull request for tlocke/pg8000#24 which added a single "check_hostname" optional parameter. However, the maintainer tlocke decided to make a bigger change to the interface. Would it be acceptable to require pg8000 1.14.0 or newer going forward?

**Comment by fschulze** [comment]
Yes, that is totally fine.

**Comment by JonathanRRogers** [comment]
I see that server-5.4.1 was released, but postgresql-2.0.0 has not been. Is there anything still to do to resolve this issue?

**Comment by fschulze** [comment]
I'm thinking about dropping Python 3.5 support as well, since it will be EOF in September and its usage is already pretty low. See https://pypistats.org/packages/__all__, though there have been some downloads for 3.5: https://pypistats.org/packages/devpi-postgresql

**Comment by JonathanRRogers** [comment]
> I'm thinking about dropping Python 3.5 support as well, since it will be EOF in September and its usage is already pretty low. See https://pypistats.org/packages/__all__, though there have been some downloads for 3.5: https://pypistats.org/packages/devpi-postgresql

OK, sounds good.

**Comment by fschulze** [comment]
devpi-postgresql 2.0.0 is out now
