### ISSUE TITLE
AssertionError when running devpi-gen-config

### ISSUE THREAD

**Issue by rozsasarpi** [devpi/devpi#785]
When following this [Quickstart](https://devpi.net/docs/devpi/devpi/stable/+d/quickstart-releaseprocess.html), I receive the following assertion error when trying to run `devpi-gen-config`:

```
It is highly recommended to use a configuration file for devpi-server, see --configfile option.
wrote gen-config\crontab
wrote gen-config\net.devpi.plist
wrote gen-config\launchd-macos.txt
wrote gen-config\nginx-devpi.conf
Traceback (most recent call last):
  File "c:\Users\arpada\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\Users\arpada\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\arpada\Wok\Projects\python_sandbox\devpi_test\venv\Scripts\devpi-gen-config.exe\__main__.py", line 9, in <module>
  File "c:\users\arpada\wok\projects\python_sandbox\devpi_test\venv\lib\site-packages\devpi_server\genconfig.py", line 171, in genconfig
    globals()[name](tw, new_args, new_argv, writer)
  File "c:\users\arpada\wok\projects\python_sandbox\devpi_test\venv\lib\site-packages\devpi_server\genconfig.py", line 33, in gen_supervisor
    assert devpibin.exists()
AssertionError
```

I'm using Python 3.7.2 and Windows 10 Enterprise version 1809. I'm using the latest version of devpi.

Any suggestion on how to resolve this error and get all the config files generated?

`pip list`:
```
Package             Version
------------------- ----------
apipkg              1.5
appdirs             1.4.3
argon2-cffi         19.2.0
attrs               19.3.0
beautifulsoup4      4.8.2
bleach              3.1.4
certifi             2019.11.28
cffi                1.14.0
Chameleon           3.7.0
chardet             3.0.4
check-manifest      0.41
cmarkgfm            0.4.2
colorama            0.4.3
defusedxml          0.6.0
devpi-client        5.1.1
devpi-common        3.4.0
devpi-server        5.4.1
devpi-web           4.0.2
distlib             0.3.0
docutils            0.16
execnet             1.7.1
filelock            3.0.12
hupper              1.10.2
idna                2.9
importlib-metadata  1.6.0
itsdangerous        1.1.0
packaging           20.3
passlib             1.7.2
PasteDeploy         2.1.0
pep517              0.8.1
pip                 20.0.2
pkginfo             1.5.0.1
plaster             1.0
plaster-pastedeploy 0.7
pluggy              0.13.1
py                  1.8.1
pycparser           2.20
Pygments            2.6.1
pyparsing           2.4.6
pyramid             1.10.4
pyramid-chameleon   0.3
python-dateutil     2.8.1
readme-renderer     25.0
repoze.lru          0.7
requests            2.23.0
ruamel.yaml         0.16.10
ruamel.yaml.clib    0.2.0
setuptools          39.1.0
six                 1.14.0
soupsieve           2.0
strictyaml          1.0.6
toml                0.10.0
tox                 3.14.6
translationstring   1.3
urllib3             1.25.8
venusian            3.0.0
virtualenv          20.0.15
waitress            1.4.3
webencodings        0.5.1
WebOb               1.8.6
Whoosh              2.7.4
zipp                3.1.0
zope.deprecation    4.4.0
zope.interface      5.0.1
```

**Comment by fschulze** [comment]
Is your virtualenv in ``C:\Users\arpada\Wok\Projects\python_sandbox\devpi_test\venv`` activated? It seems like ``devpi-gen-config`` can't find the ``devpi-server`` executable in the path. There should definitely be a better error message in that case, so leave the ticket open, even if activating the virtualenv fixes it for you.

**Comment by rozsasarpi** [comment]
Yes, I run the commands from a virtualenv located in `C:\Users\arpada\Wok\Projects\python_sandbox\devpi_test\venv` and using windows command prompt with administrator rights.

**Comment by fschulze** [comment]
Could you paste the content of ``C:\Users\arpada\Wok\Projects\python_sandbox\devpi_test\venv\Scripts\`` please? There should be ``devpi-server.exe`` in there.

If you can, then edit ``c:\users\arpada\wok\projects\python_sandbox\devpi_test\venv\lib\site-packages\devpi_server\genconfig.py``. Put a ``print(devpibin)`` line before the ``assert devpibin.exists()`` on line 33. After that try again and copy the output of the ``print`` here (should be just before the traceback).

**Comment by rozsasarpi** [comment]
@fschulze Thank you for your prompt help.

The content of `C:\Users\arpada\Wok\Projects\python_sandbox\devpi_test\venv\Scripts\` (yes `devpi-server.exe` is there):

```
Activate.ps1        devpi-gen-config.exe  pcreate.exe       pserve.exe      rst2html5.py           rstpep2html.py
__pycache__         devpi-import.exe      pdistreport.exe   pshell.exe      rst2latex.py           tox-quickstart.exe
activate            devpi-init.exe        pip.exe           ptweens.exe     rst2man.py             tox.exe
activate.bat        devpi-passwd.exe      pip3.7-script.py  pviews.exe      rst2odt.py             virtualenv.exe
chardetect.exe      devpi-server.exe      pip3.7.exe        pygmentize.exe  rst2odt_prepstyles.py  waitress-serve.exe
check-manifest.exe  easy_install-3.7.exe  pip3.exe          python.exe      rst2pseudoxml.py
deactivate.bat      easy_install.exe      pkginfo.exe       pythonw.exe     rst2s5.py
devpi-export.exe    f2py.exe              prequest.exe      rst2html.py     rst2xetex.py
devpi-fsck.exe      hupper.exe            proutes.exe       rst2html4.py    rst2xml.py
```
This is what `print(devpibin)` prints:
```
C:\Users\arpada\Wok\Projects\python_sandbox\devpi_test\venv\Scripts\devpi-server
```

**Comment by fschulze** [comment]
Ok, that explains the issue, but I wonder why ``.exe`` is not included there.

To solve your immediate problem, remove all ``assert devpibin.exists()`` lines in ``genconfig.py``. You might have to edit the generated files to add the ``.exe``.

I have to investigate whether there is a cross platform way to solve this, otherwise I will just output a warning.

**Comment by rozsasarpi** [comment]
@fschulze Thanks! After removing the `assert devpibin.exists()`s I could run `devpi-gen-config`.

Given that I would need to find the Windows equivalent of `supervisord` probably it is better if I just move to a UNIX-like OS right away, I only wanted use Windows for trying out the package (I'm more comfortable with Windows).

**Comment by fschulze** [comment]
There is one file generated by devpi-gen-config which explains how to setup devpi as a Windows service.
