### ISSUE TITLE
404 on /+login when devpi deployed behind proxies

### ISSUE THREAD

**Issue by DrPyser** [devpi/devpi#787]
devpi-server: `devpi-server 4.7.1`
devpi-client: `devpi-client 5.1.1`

I have a setup with devpi deployed behind an nginx proxy with the generated configuration(edited for our docker infrastructure). Both are also behind a kong api gateway that terminates ssl connections.

Things seemed to be working fine, but now I'm getting `404`s on login(`devpi use htttps://pip.mydomain.com/root/myindex/+simple; devpi login root`):

```
Not Found

The following resource could not be found:

predicate mismatch for view PyPIView (request_method = POST)

    devpi-server-4.7.1
    devpi-web-3.4.1

```

Same issue as this: https://stackoverflow.com/questions/52319514/devpi-server-devpi-login-returns-404

It seems the request ends up being interpreted as a search query instead of correctly hitting the login endpoint?

The nginx log doesn't tell me anything useful, and the devpi log either(both receive the request):
(nginx)
```
...
pip-proxy-default_nginx.1.3wd29cpgedvf@slrs01v00000127    | 10.0.1.4 - - [03/Apr/2020:19:47:14 +0000] "GET /+login HTTP/1.1" 404 1994 "-" "devpi-client/5.1.1 (py3.7.5; linux)"
...
```
(devpi-server)
```
...
pip-proxy-default_devpi.1.ikcyz9ls7hnt@slrs01v00000127    | 2020-04-03 19:46:15,024 INFO  [req2348] GET /+login
...
```

my nginx configuration:

```
server {
    server_name _ $hostname "" localhost;   
    listen 80 default_server;

    resolver 127.0.0.11 ipv6=off;

    gzip             on;
    gzip_min_length  2000;
    gzip_proxied     any;
    gzip_types       text/html application/json; 

    error_log /dev/stderr debug;
    access_log /dev/stdout;

    proxy_read_timeout 60s;
    client_max_body_size 64M;

    # set to where your devpi-server state is on the filesystem
    root /devpi;  

    # try serving static files directly
    location ~ /\+f/ {
        # workaround to pass non-GET/HEAD requests through to the named location below
        error_page 418 = @proxy_to_app;
        if ($request_method !~ (GET)|(HEAD)) {
            return 418; 
        }

        expires max;
        try_files /+files$uri @proxy_to_app;
    }
    # try serving docs directly
    location ~ /\+doc/ {
        try_files $uri @proxy_to_app;
    }
    location / {
        # workaround to pass all requests to / through to the named location below
        error_page 418 = @proxy_to_app;
        return 418;
    }

    location /robots.txt {
        add_header Content-Type text/plain;
        return 200 "User-Agent: *\nDisallow: /\n";
    }

    location @proxy_to_app {
        # the upstream devpi server is in a docker container in the same docker network 
        set $upstream devpi.pip-proxy;
        proxy_pass http://$upstream:3141;
        proxy_set_header X-outside-url $scheme://$host:$server_port;
        proxy_set_header X-Real-IP $remote_addr;
    }
} 
```
That's basicaly what's generated by `devpi-server --gen-config`, with the upstream url changed and the docker dns resolver config.
Is there a `location` block for `/+login` that should be added?

**Comment by fschulze** [comment]
It's possible that docker does its own port forwarding which messes up the values for ``proxy_set_header X-outside-url $scheme://$host:$server_port;``.
Look at the result of ``htttps://pip.mydomain.com/+api`` to see what the generated ``+login`` URL looks like. You might have to set the ``X-outside-url`` header to an explicit value instead of using the variables from nginx.

**Comment by DrPyser** [comment]
@f@fschulze Thanks, it worked! I set the `X-Outside-Url` header in the nginx config.

**Comment by fschulze** [comment]
Glad you were able to fix it.
