### ISSUE TITLE
Exception on devpi login without previous devpi use

### ISSUE THREAD

**Issue by GergelyKalmar** [devpi/devpi#799]
It seems that ``devpi-client`` (v. 5.1.1) fails on Python 3.8:

```
$ devpi login xxx
Traceback (most recent call last):
  File "/home/gregory/.pyorbs/cc/bin/devpi", line 8, in <module>
    sys.exit(main())
  File "/home/gregory/.pyorbs/cc/lib/python3.8/site-packages/devpi/main.py", line 36, in main
    return method(hub, hub.args)
  File "/home/gregory/.pyorbs/cc/lib/python3.8/site-packages/devpi/login.py", line 12, in main
    url=hub.current.root_url.url, username=user)
AttributeError: 'NoneType' object has no attribute 'url'
```

Could support be added? Ubuntu 20.04 LTS comes with Python 3.8 and so I cannot seem to be able to release packages now due to this issue.

**Comment by fschulze** [comment]
You first have to run ``devpi use``. There shouldn't be an exception though. I can reproduce that issue and will look into it.

**Comment by GergelyKalmar** [comment]
@fschulze ah, you're right of course! It does seem to work now. Perhaps a more useful error message will do it in this case. Thanks very much for the quick help!
