### ISSUE TITLE
Offline server copy

### ISSUE THREAD

**Issue by CBtiger** [devpi/devpi#802]
A similar issue was this mentioned here:  #630

I would like to use a devpi server to allow "normal" python development in a stand-alone local network. I did not see that use-case mentioned somewhere. 

One way I see is to set up a devpi server online, install all packages I could think of, then copy the server config file(s) and the repository. On the local network I install an "empty" devpi server, then paste the config and repository. 

However, I would rather try to setup a devpi server online and install a single package, say numpy to that the index is created. Then I would use the tool minirepo ([https://github.com/sganis/minirepo](url) to download all wheel and source packages and store them in the devpi repository folder. Now I guess I would need to have a way to make the devpi server to update its internal index, do I?
Finally I would copy the system as above.

Does one of these approaches work or is there a another, better way to do it?

**Comment by fschulze** [comment]
There are two ways I can think of:
1. Just server the files downloaded with minirepo via nginx and include them in devpi with a mirror index using the ``mirror_url`` option and ``mirror_use_external_urls`` set to ``true``.
2. Upload all the files to a private index. I would use a separate one from your main index and add it to its ``bases``, so public and custom packages are in different indexes.

**Comment by CBtiger** [comment]
thats great news, that the server can be used for this scenario. 

If I understand correctly the second option would result in clone of the online version (or better the laptop situation (when the network is off). All required is a script to feed the whole archive to the server - a good idea.

The second sounds interesting. There is already an apache server service the linux repo. To add a few GB python files sounds like an interesting option. I think I will look further though the documentation on how to set up the server with mirror_url/mirror_use_external_urls and try that one. 

Would you think there is a performance difference on the server(s) between the two options? I am looking at CPU/Disk loads during normal operation for installs and searches. One time setup impact is not critical.

**Comment by RonnyPfannschmidt** [comment]
Bandersnatch is a offline mirror tool

**Comment by fschulze** [comment]
@RonnyPfannschmidt but it's all or nothing and by now PyPI is quite big.

@CBtiger I don't think there is much of a difference performance wise.

**Comment by CBtiger** [comment]
@fschulze Thanks for the competent support. Great work!
