### ISSUE TITLE
Documentation is stuck at 5.2

### ISSUE THREAD

**Issue by hynek** [devpi/devpi#806]
Not sure what's happening, but I noticed it while looking at the changelog: https://devpi.net/docs/devpi/devpi

Since devpi's Docs seem to be self-served using devpi, maybe the last releases have only been uploaded to PyPI proper?

**Comment by fschulze** [comment]
The documentation upload is lagging, but mostly because nothing was added to it. Some smaller features are only mentioned in the changelog so far. I hope to add to it for the upcoming 6.0.0.

**Comment by fschulze** [comment]
I have uploaded new docs for the 6.0.0 release.
