### ISSUE TITLE
Mirror without caching?

### ISSUE THREAD

**Issue by pfmoore** [devpi/devpi#812]
Is it possible to create a PyPI mirror *without* a local cache? Pip already caches files downloaded from the index, and when running a local devpi index on my laptop, I end up with everything cached twice - particularly annoying for packages like tensorflow which take 500M a time. And it's not obvious how to clear cached items when a new release happens - pip has `pip cache remove`, so keeping the pip cache under control is possible, but short of removing and rebuilding the devpi server, I couldn't find any information on how to manage the cache.

**Comment by RonnyPfannschmidt** [comment]
It's possible to declare the pypy mirror to use the original URLs

Atm im on mobile and can't look it up

**Comment by thomasf** [comment]
it is also possible to disable the pip cache so you have that option as well

**Comment by pfmoore** [comment]
> It's possible to declare the pypy mirror to use the original URLs

Awesome! A link to the relevant docs would be great, when you have the chance (no rush!) I find the docs fine for tutorial and learning, but not so easy to use for reference 🙁

**Comment by fschulze** [comment]
Unfortunately it isn't documented yet. Set the ``mirror_use_external_urls`` option on the PyPI index to ``true``. Currently there is no easy way to remove already cached files. You either have to remove and recreate the mirror index (copy the existing settings for reference) or you have to remove the releases with ``devpi remove [url]``, but you have to come up with a list of them yourself (using the files from the filesystem to create a list of links works quite well with some shell or python scripting).

**Comment by pfmoore** [comment]
Thanks for the information, that's exactly what I needed 🙂
