### ISSUE TITLE
Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

### ISSUE THREAD

**Issue by jijoosper** [devpi/devpi#815]
Hi,

In our local environment, when we build a python app, required packages are pulled from a local devpi container. If the devpi is not hosting the package, it will contact the pypi cloud ECS container at https://pip.domain.com (domain has to be replaced). However, we are sometimes getting the below error in the docker logs of devpi

===
2020-08-06 03:11:06,488 WARNI [IDXQ] [Rtx7256] upstream error (URL 'https://pip.domain.com/simple/' returned -1 ConnectionError(MaxRetryError("HTTPSConnectionPool(host='pip.domain.com', port=443): Max retries exceeded with url: /simple/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff04404a4a8>: **Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',**))",),)): using stale projects list
===

what may be causing this? pip.doamin.com is listening on an ELB on port 443 and it forwards the traffic to an nginx container. Pypi container is the upstream for this nginx container. I tried checking nginx error log, ELB logs and docker logs of pypi container but no luck :-(
Will this be due to[ DNS Quotas](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-dns.html#vpc-dns-limits) ?

**Comment by fschulze** [comment]
devpi is using the default Python stuff for name resolution, which in turn should use the default OS facilities. You should check the TTL of that domain to see if it is very low, which would cause frequent cache misses that could lead to this. Anything below 1 hour is pretty much waste except for very few use cases. Besides that I have no clue and doubt it is a devpi issue.

**Comment by fschulze** [comment]
If this is still a problem, please reopen this ticket with more information.
