### ISSUE TITLE
PEP 592 support not released?

### ISSUE THREAD

**Issue by matthiasha** [devpi/devpi#818]
Hi,

I have seen PEP 592 support has been implemented in #797 back in April. However, it seems this has not been included in any releases yet? I have not found any mentions in the release notes. 

It seems the release notes are outdated: https://devpi.net/docs/devpi/devpi/stable/+d/changelog.html and it is unclear to me if versions refer to devpi-server, devpi-web or devpi-client.

I have also downloaded the sources for `devpi-web==4.0.5` and `devpi-server==5.5.0` and grepped for `yank` without success.

Thanks for your help!

**Comment by fschulze** [comment]
This change is still waiting for a release on the ``main`` branch. There is no ETA for it yet though.

**Comment by fschulze** [comment]
I finally release devpi-server 6.0.0.
