### ISSUE TITLE
ETA for devpi-server 6.0.0

### ISSUE THREAD

**Issue by pierreluctg** [devpi/devpi#820]
Hi @fschulze, can you share when you are planning to release devpi-server 6.0.0?

I am explicitly looking to the fix for #725 

Thank you

**Comment by fschulze** [comment]
There are some issues with the replication changes and some new hooks are still being worked on. Everything else has been stable during testing so far.

If you don't use/need replication, then you can use https://m.devpi.net/fschulze/dev/devpi-server/6.0.0.dev13 to get everything else that will be in 6.0.0.

**Comment by pierreluctg** [comment]
Thank you @fschulze, but I do use the replication.

**Comment by fschulze** [comment]
I have uploaded https://m.devpi.net/fschulze/dev/devpi-server/6.0.0.dev20 which is the current release candidate.

**Comment by fschulze** [comment]
Make sure to read the changelog carefully.

**Comment by fschulze** [comment]
I finally release devpi-server 6.0.0.
