### ISSUE TITLE
Cache maintenance

### ISSUE THREAD

**Issue by diego-maravankin** [devpi/devpi#822]
Hi Guys! Thanks for this amazing project! I am implementing devpi as a cache in order to reduce installation time in dynamic workloads.

The thing is, this workloads change constantly, and perharps a certain module is not being used anymore and the disk space can be reclaimed. I'd like to know if there is a way of keeping only the used cached modules and deleting those that were not downloaded in the last 15 days (or 30 days).

Thanks in advance!

**Comment by fschulze** [comment]
No follow-up for several months. If this is still an issue, feel free to re-open.
