### ISSUE TITLE
OS error during httpget

### ISSUE THREAD

**Issue by iigx** [devpi/devpi#826]
Enrionment:
    Windows server 2019
    Python 3.6.7
    devpi-server 5.5.0
    devpi-common 3.6.0
    devpi-client 5.2.1
Issue:
 OS error during http get of repo., however, i can install modules with pip install from this repo.

![image](https://user-images.githubusercontent.com/46487494/103027078-2ac39500-4590-11eb-9670-066bfe8cdeb8.png)

**Comment by fschulze** [comment]
It seems like your devpi-server at 10.9.1.3 has problems connecting to https://pypi.tuna.tsinghua.edu.cn/simple/

Can you try to connect to https://pypi.tuna.tsinghua.edu.cn/simple/ from your server at 10.9.1.3 with a tool like ``curl`` or ``wget``?

You can also try running devpi-server with the ``--debug`` option to get more information about the OS error in the log output.

**Comment by fschulze** [comment]
If this is still a problem, please reopen this issue with more information as requested.
