### ISSUE TITLE
allow devpi-server to bind to multiple sockets

### ISSUE THREAD

**Issue by wnoise** [devpi/devpi#827]
Currently one can only bind to a single socket (well, one IP/port combination, and possibly one unix socket.  Is this intended?  It looks like it tries to disable listening on IP, but only if both host and port are the default).
I'm using devpi-server to cache downloads for Docker builds.  As such, the safest thing is to have it bind to
the docker bridge network interface's IP address.  In addition, I want to use it as a caching server and repository for normal interactive development.  I do not however want to bind to '0.0.0.0', as exterior clients should not be able to interact with it.

Waitress supports this via the `listen` kwarg to `serve()`, e.g. waitress.serve(listen="127.0.0.1:3141 172.17.0.1:3141").  Alternately, you can bind them yourself, and use the `sockets` kwarg to pass a list.

There are, of course, a number of workarounds (running docker build on the 'host' net, or having normal clients also access via the docker bridge interface, or running a trivial netcat pipe between the two).  Still, this is a generally useful option.

**Comment by fschulze** [comment]
What would you propose as a fix? I'm thinking of deprecating ``--host`` and ``--port`` and add a new ``--listen`` instead which would be passed on to waitress as is. Would that solve your issue?

**Comment by wnoise** [comment]
That would 100% work for me.  I was hesitant to suggest such a radical interface change to a long-existing project.
