### ISSUE TITLE
pip install did not filter the correct version when using python2

### ISSUE THREAD

**Issue by liuzhenwubigboss** [devpi/devpi#828]
Hello, thanks for your great project! 

Now I have a strange problem and need some help.When I use python2's pip, the python3's packages will be found too,some of the packages does not support python2 and it will throw an error.

For example, the  python2's  `setuptools` newest version is `44.1.1` and The  python3's  `setuptools` newest version is `53.0.0`.

Here's my env and pip logs,so what's the possible problem?

![image](https://user-images.githubusercontent.com/31624973/106846957-e546cb80-66e8-11eb-95e7-4445351993bb.png)
![image](https://user-images.githubusercontent.com/31624973/106847010-0ad3d500-66e9-11eb-91a1-2badacaf07a7.png)

**Comment by fschulze** [comment]
I think you may have to upgrade your pip in Python 2 first, you got 8.1.1 there. Not sure when the requires Python support was added, or if there were bugs. I did a quick scan of the pip changelog and I think that version already supports it, but I'm not certain.

If you can, take a look at the HTML source of http://localhost:9999/root/pypi/+simple/setuptools/ to see if the links have the correct ``data-requires-python`` attribute.

**Comment by liuzhenwubigboss** [comment]
> I think you may have to upgrade your pip in Python 2 first, you got 8.1.1 there. Not sure when the requires Python support was added, or if there were bugs. I did a quick scan of the pip changelog and I think that version already supports it, but I'm not certain.
> 
> If you can, take a look at the HTML source of http://localhost:9999/root/pypi/+simple/setuptools/ to see if the links have the correct `data-requires-python` attribute.

ok, I think it's my fault, I forgot to add `+simple` in the index-url.Actually there was an old version of devpi(4.0.0) in our company and it has the problem mentioned above, the old version does not have `data-requires-python` attribute and I try to upgrade devpi and now it's ok, thanks!
