### ISSUE TITLE
loads of project_ trm & pst files

### ISSUE THREAD

**Issue by MrMontesa** [devpi/devpi#829]
Hey, 
we're using devpi-server and love the project. We're just hosting a bunch of our own packages within 2 indexes (stable & staging) and have a root for for the global packages.
This morning our monitoring alerted due to full disk and indeed the .devpi folder has grown to 40 GB. When searching where storage is used I came accross _/space/.devpi/server/.indices_ folder containing 2.5 million files and 25 GB. All named project_SOMEID.[pst|trm]. 

Is this normal behavior? Is there a way to cleanup?
Here's the yearly graph of disk usage:
![image](https://user-images.githubusercontent.com/600125/107340394-02e7ac80-6abe-11eb-8bdc-a9df5f8d2fd2.png)

Some details about my system:
```
[root@nbg-web01 .indices]# cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core)
[root@nbg-web01 .indices]# /space/devpi-server/bin/python --version
Python 3.7.8
[root@nbg-web01 .indices]# /space/devpi-server/bin/python /space/devpi-server/bin/devpi-server --version
5.5.0
[root@nbg-web01 .indices]# pwd
/space/.devpi/server/.indices
[root@nbg-web01 .indices]# ls -al | wc -l
2540829
[root@nbg-web01 .indices]# du -hs
25G     .
[root@nbg-web01 .indices]# cat project_000dog2h9s3x2zam.trm
HSH3
[root@nbg-web01 +files]# pwd
/space/.devpi/server/+files
[root@nbg-web01 +files]# du -hs *
0       user1
19M     user2
15G     root
```

**Comment by fschulze** [comment]
Those are the index files for the search. If you don't need search, then you can disable it with ``--indexer-backend=null`` and remove the ``.indices`` folder. Currently this isn't reflected in the UI though, which is why this isn't documented yet. The search field will still be displayed.

**Comment by MrMontesa** [comment]
Thanks for your swift reply. This is for searching in devpi-web, right? Or does it also apply when adding simple index to IDE and searching there? I guess an IDE does "load all" and searches its own index rather than sending the search pattern to devpi-web search.

And I guess I only have to add ```--indexer-backend=null``` to the devpi-server start string, right?
Thanks much

**Comment by fschulze** [comment]
> Thanks for your swift reply. This is for searching in devpi-web, right? Or does it also apply when adding simple index to IDE and searching there? I guess an IDE does "load all" and searches its own index rather than sending the search pattern to devpi-web search.

The IDE might use the xml-rpc backend. The ``null`` backend has rudimentary support for that by searching the package names, but nothing else.

> And I guess I only have to add `--indexer-backend=null` to the devpi-server start string, right?

Yes. You can also add it to test with the ``null`` backend and only remove the ``.indices`` folder if it is successful. If you need to remove the ``null`` backend again, devpi-web will update the still existing index as required.

**Comment by MrMontesa** [comment]
Thanks for confirmation. I disabled the search index and wiped the folder. All is still running as we need.
Will close here.
Thanks
