### ISSUE TITLE
checksum error on cryptography package with new devpi

### ISSUE THREAD

**Issue by techsolo** [devpi/devpi#833]
Hi,

When downloading requirements using a devpi-mirror (existing one up to date and new one) like this in a Jenkins job:

`/data/pyenv/versions/3.6.7/bin/pipenv --bare install --python /data/pyenv/versions/3.6.7/bin/python --dev --pypi-mirror https://pypi.python.org/simple/`

Will work fine with the default mirror but not with one of our devpi mirrors. But it always fails on Cryptography. And it only recently stopped working.

    devpi-server-5.5.0
    devpi-web-4.0.5

I see this in the output of the devpi-web container:

`
2021-02-11 22:00:26,042 INFO  [req842] GET /root/pypi/cryptography/
2021-02-11 22:00:26,140 INFO  [req843] GET /root/pypi/+simple/cryptography/
2021-02-11 22:00:27,375 INFO  [req844] GET /root/pypi/+f/ee5/e19f0856b6fbb/cryptography-3.4.4.tar.gz
2021-02-11 22:00:27,399 INFO  [req844] [Wtx372] reading remote: https://files.pythonhosted.org/packages/27/5a/007acee0243186123a55423d49cbb5c15cb02d76dd1b6a27659a894b13a2/cryptography-3.4.4.tar.gz, target root/pypi/+f/ee5/e19f0856b6fbb/cryptography-3.4.4.tar.gz
2021-02-11 22:00:27,443 INFO  [Wtx372] fswriter373: committed: keys: 'root/pypi/+f/ee5/e19f0856b6fbb/cryptography-3.4.4.tar.gz', files_commit: +files/root/pypi/+f/ee5/e19f0856b6fbb/cryptography-3.4.4.tar.gz`

but the package is not installed in .cache and the build job fails on dependencies.

`pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmp95jviqogbuild/cryptography/`

Any idea what could be the issue here?

Kind regards,

Solo

**Comment by fschulze** [comment]
This might be a build issue with cryptography itself. Is there a reason pip doesn't use the provided binary wheels? They recently introduced Rust into the build dependencies and ``setuptools-rust`` is required. I think you can get more detailed output with ``pip install -v`` as well, maybe this will give you additional clues. If you still can't find the problem, could you paste the full output of pip?

I also think the subject of this issue is misleading, the output you provided doesn't indicate any checksum error, or did you forget to paste something?

**Comment by techsolo** [comment]
It actually looks a lot like this issue: 

https://github.com/pypa/pipenv/issues/2722

But mine fails on:

`  connexion==1.1.13         requires clickclick>=1.2, flask>=0.10.1, inflection>=0.3.1, jsonschema>=2.5.1, pathlib>=1.0.1, pyyaml>=3.11, requests>=2.9.1, six>=1.9, swagger-spec-validator>=2.0.2, typing>=3.6.1
  graypy==0.2.14            requires -
  cerberus==1.3.2           requires setuptools
  cryptography==3.4.6 not in cache, need to check index
Traceback (most recent call last):
  File "/data/pyenv/versions/3.6.7/lib/python3.6/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/data/pyenv/versions/3.6.7/lib/python3.6/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/data/pyenv/versions/3.6.7/lib/python3.6/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,`

**Comment by fschulze** [comment]
Only now saw that you use pipenv. Anyway, please provide the full output, those single errors aren't enough to analyze this. If pipenv has an option like ``-v`` to provide more output, please use it as well.

**Comment by techsolo** [comment]
[log_devpi.txt](https://github.com/devpi/devpi/files/6034797/log_devpi.txt)

**Comment by fschulze** [comment]
Try it with ``--pypi-mirror https://devpi.local:4041/root/pypi/+simple/``. Notice the added ``+simple/``. We might have to add an automatic redirect for pipenv. Could be it is using a user agent which isn't recognized by the existing redirect.

**Comment by techsolo** [comment]
I seem to get the same result. 
[log_devpi.txt](https://github.com/devpi/devpi/files/6035355/log_devpi.txt)

**Comment by fschulze** [comment]
Could you provide the log output with PyPI as mirror for comparison? I still think it uses wheels with PyPI and for some reason tries to build from source with devpi which fails, most likely because of the Rust requirement to build cryptography since version 3.4.0.

**Comment by techsolo** [comment]
@fschulze I ran the same build again with both, just to be sure. 

[pypi_succeed.txt](https://github.com/devpi/devpi/files/6342458/pypi_succeed.txt)
[devpi_fail.txt](https://github.com/devpi/devpi/files/6342464/devpi_fail.txt)

**Comment by fschulze** [comment]
pipenv only outputs a traceback ending in:
```
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmp_qkc_bmpbuild/cryptography/
```

The actual output of ``python setup.py egg_info`` which fails is needed here. The current output is just not sufficient. It doesn't write which files (or URLs) are used (source release or wheel etc) and doesn't print the error output of the failed command. Either you need to find a command line option in pipenv which outputs that additional info, add it yourself in pipenv, or ask the maintainers if they can add that additional info.

You could also try to download the cryptography 3.4.6 source from pypi and try to run the above egg_info command yourself to see what happens. I still have no clue what the difference could be causing it to fail.

It also looks like the PyPI case uses cached data. Check if there is an option to run without the cache or delete the cache content before running. It could be that without the cache you get the same error.

**Comment by fschulze** [comment]
No updates for several months, so I consider this issue obsolete. If that is not the case, feel free to reopen with more information as requested in last comment.
