### ISSUE TITLE
hide user without index on main page

### ISSUE THREAD

**Issue by MrMontesa** [devpi/devpi#839]
Hey devpi specialists,
quick question: Is it possible to hide user indexes?

Long description:
WE do have 2 main indexes (stable & staging) under a certain user (called packages). We have different teams pushing to those indexes and for logical separation, they received different users based on their team name.
All those users are also listed in the index overview without an index. Since there is nothing to retrieve from those users, would be good to hide them.
![image](https://user-images.githubusercontent.com/600125/113841758-56ab0500-9792-11eb-9a79-37ea8e1ca469.png)

Something like "hide_user_without_index = true" or "hide_users=user1,user2,user3"
Any hint if this is possible?
Thanks much

**Comment by fschulze** [comment]
You can use a theme for that.

- create a directory for your theme
- in there a directory ``templates``
- copy [``root.pt``](https://github.com/devpi/devpi/blob/main/web/devpi_web/templates/root.pt) from devpi-web source there
- replace the ``<dl tal:repeat="user users">`` tag with ``<tal:users repeat="user users"><dl tal:condition="user.indexes">``
- replace the equivalent closing ``</dl>`` with ``</dl></tal:users>``
- use the theme with the ``--theme <path to your theme directory>`` option on the command line you start devpi-server with

You can set ``PYRAMID_RELOAD_TEMPLATES=true`` before starting devpi-server to more easily adjust the template. It should not be used in production for performance reasons.

The devpi-web changelog will contain mentions if the template ever changes, so on updates you should check there and redo your change with the new template.

**Comment by fschulze** [comment]
Seems to be resolved, feel free to reopen if not.
