### ISSUE TITLE
Url given to `devpi use` is overridden by the outside-url value of the server

### ISSUE THREAD

**Issue by mathbou** [devpi/devpi#840]
### Issue:

A bit of context first, I use Devpi inside a docker container, with a Traefik reverse proxy above. Due to this setup, I have to set `--outside-url https://devpi.local`, otherwise, I get 'mixed content' errors.
Next to this, I have a GitLab instance that does some CI/CD jobs. Devpi and Gitlab share a common closed network that allows them to communicate directly without getting out through Traefik. 
![devpi](https://user-images.githubusercontent.com/13415583/114240519-ebc31f00-9987-11eb-9079-9c606617757e.jpg)

The problem now is when I want to upload packages from a CI job, I set `devpi use http://devpi/my-user/my-index` (devpi is the hostname of my container) but the url in the config is replaced by the outside-url 'https://devpi.local' which leads to login failure (https stuff are managed at Traefik level).

I tried to modify the client config file to force the hostname url, and it works. So the big question is, Is there a way to force devpi-client to use the given url instead of the url returned by the server? 

### Infos:
My Devpi container is built upon the python:3.7-slim image, so it's Debian-based.
Server: 5.5.1
Web: 4.0.6
Client: 5.2.2

**Comment by fschulze** [comment]
Instead of ``--outside-url`` you can use a ``X-Outside-URL`` header in your Traefik proxy. There is some info on that [in the docs](https://devpi.net/docs/devpi/devpi/stable/+doc/quickstart-server.html#nginx-devpi-conf-nginx-site-config).

**Comment by fschulze** [comment]
According to the docs of Traefik you can add headers: https://doc.traefik.io/traefik/middlewares/headers/

**Comment by mathbou** [comment]
I already tried them, but it doesn't change anything, it's worse than my test on Nginx.

I dig into the client code and found something that corresponds to my problem:
https://github.com/devpi/devpi/blob/2033769b98095b5e5da07a072d12bd4047e6e5a6/client/devpi/use.py#L259-L266

Is there any reason that `val` isn't cut to keep only the URL path instead of the full URL? By adding `val = URL(val).path` between L264-L265 I was able to get rid of the override

**Comment by fschulze** [comment]
There are many other places where the correct URL is required and ``X-Outside-URL`` is the way to go. I have this setup myself in various instances and it works correctly. Without the header devpi-web doesn't work when available at more than one virtual host.

Did you remove the ``--outside-url`` option and restart devpi-server when you tried setting the headers? Did you use ``https://devpi.local`` as the header value for Traefik? Did you check that Traefik actually adds the header? The header needs to be set via ``traefik.http.middlewares.testHeader.headers.customrequestheaders`` if I read the docs correctly, so devpi-server sees the header. With ``traefik.http.middlewares.testHeader.headers.customresponseheaders`` only devpi-client would see it, which doesn't know how to handle it.

**Comment by mathbou** [comment]
No need to paraphrase the doc, I can read, and I literally tried for hours to make it work using headers and middlewares, with or without the flag, at best nothing changed, at worst it wasn't even reachable.

Besides, as I stated earlier, the server itself works without all of those headers modifications. And from my understanding of the [use.py](https://github.com/devpi/devpi/blob/2033769b98095b5e5da07a072d12bd4047e6e5a6/client/devpi/use.py) code, it wouldn't help much as  `_configure_from_server_api` uses the URL from the `/+api` response instead of the passed arg, so whatever I do on the server-side, it always will be overridden on the client-side.

**Comment by fschulze** [comment]
I was trying to make sure the requirements were understood correctly. That the result of ``/+api`` is used is the point. If the server and proxies in front are configured correctly, everything then works as expected. Changing how devpi-client works would just hide the fact that the configuration is wrong. If the configuration is correct, a ``curl http://devpi/+api`` and ``curl https://devpi.local/+api`` will contain the correct URLs for each case.

You can do some debugging:

In ``devpi_server/views.py`` in the ``__call__`` method of ``OutsideURLMiddleware`` put a ``pdb.set_trace()`` at the start. Run the above ``curl`` commands and check that the ``if not outside_url:`` branch is taken and the ``environ`` updated correctly in the next ``if outside_url:`` branch. If that isn't the case, then your configuration isn't getting through to devpi-server and you have to check the parts before devpi-server is reached.

**Comment by mathbou** [comment]
My first config may appear wrong but from a user point of view it works: when I force the hostname (http://devpi) in the Devpi config file, devpi-client commands works (except `use` of course).

If an `/+api` query is always made with the `use` command (which is the case), the following should be correct:
- I get a response from `/+api`, which means my arg is good -> we use the arg url
- if it fails, the arg is wrong -> nothing is set

But currently, the command does this:
- I get a response from `/+api`, which means my arg is good -> arg is replaced by `/+api` response 
- if it fails, the arg is wrong -> nothing is set

Which is a really odd and unexpected behavior.

<br>
Also, I'm curious about your statement below. Which places are you referring to?

> There are many other places where the correct URL is required

---

Here the results of my debugging, using Traefik:
curl http://devpi is launched from a container in the same docker network as Devpi.
curl https://devpi.local is launched from my computer, outside of the docker network.

### With --outside-url

curl http://devpi :
- `if not outside-url` -> not taken
- `if outside-url` -> taken and outside-url=https://devpi.local

curl https://devpi.local :
- `if not outside-url` -> not taken
- `if outside-url` -> taken and outside-url=https://devpi.local

### Without --outside-url

curl http://devpi :
- `if not outside-url` -> taken and outside-url=None
- `if outside-url` -> not taken

curl https://devpi.local :
- `if not outside-url` -> taken and outside-url=None
- `if outside-url` -> not taken
- Mixed content error in the browser

### Headers

curl http://devpi :
- `if not outside-url` -> taken and outside-url=None
- `if outside-url` -> not taken

curl https://devpi.local :
- `if not outside-url` -> taken and outside-url=https://devpi.local
- `if outside-url` -> taken and outside-url=https://devpi.local

**Comment by fschulze** [comment]
> My first config may appear wrong but from a user point of view it works: when I force the hostname (http://devpi) in the Devpi config file, devpi-client commands works (except `use` of course).
> 
> If an `/+api` query is always made with the `use` command (which is the case), the following should be correct:
> 
>     * I get a response from `/+api`, which means my arg is good -> we use the arg url
> 
>     * if it fails, the arg is wrong -> nothing is set
> 
> 
> But currently, the command does this:
> 
>     * I get a response from `/+api`, which means my arg is good -> arg is replaced by `/+api` response
> 
>     * if it fails, the arg is wrong -> nothing is set
> 
> 
> Which is a really odd and unexpected behavior.

The *content* of ``/+api`` is important, not only whether it is reachable. That is why it is overwriting the arg. There could be a 302 redirect involved in case the server is moved etc. There are many reasons the content of the ``/+api`` result may differ from the command line arg.

> Also, I'm curious about your statement below. Which places are you referring to?
> 
> > There are many other places where the correct URL is required

All of devpi-web needs to know the correct outside URL to generate any URL for static files like css and for basically every link. That is why you get mixed content errors in the browser.

> Here the results of my debugging, using Traefik:
> curl http://devpi is launched from a container in the same docker network as Devpi.
> curl https://devpi.local is launched from my computer, outside of the docker network.
> ### With --outside-url
> 
> curl http://devpi :
> 
>     * `if not outside-url` -> not taken
> 
>     * `if outside-url` -> taken and outside-url=https://devpi.local
> 
> 
> curl https://devpi.local :
> 
>     * `if not outside-url` -> not taken
> 
>     * `if outside-url` -> taken and outside-url=https://devpi.local
> 
> 
> ### Without --outside-url
> 
> curl http://devpi :
> 
>     * `if not outside-url` -> taken and outside-url=None
> 
>     * `if outside-url` -> not taken
> 
> 
> curl https://devpi.local :
> 
>     * `if not outside-url` -> taken and outside-url=None
> 
>     * `if outside-url` -> not taken
> 
>     * Mixed content error in the browser
> 
> 
> ### Headers
> 
> curl http://devpi :
> 
>     * `if not outside-url` -> taken and outside-url=None
> 
>     * `if outside-url` -> not taken
> 
> 
> curl https://devpi.local :
> 
>     * `if not outside-url` -> taken and outside-url=https://devpi.local
> 
>     * `if outside-url` -> taken and outside-url=https://devpi.local

These all look exactly like *I* expected. The last one is almost there. There are two ways this could be fixed:

1. add nginx in front of devpi-server for ``http://devpi`` to add the header
2. we change the behaviour of ``--outside-url`` to only apply when the header is *not* set instead of overwriting it

I think 2. is actually the way to go. I can't think of a good reason to always overwrite the header. Using the arg as the default for when the header is not set makes much more sense as your case shows.

Could you try the following patch with ``--outside-url=http://devpi`` and the header in Traefik set to ``https://devpi.local``?

```diff
diff --git a/server/devpi_server/views.py b/server/devpi_server/views.py
index ece15f47..0ccf5e12 100644
--- a/server/devpi_server/views.py
+++ b/server/devpi_server/views.py
@@ -152,9 +152,9 @@ class OutsideURLMiddleware(object):
         self.xom = xom
 
     def __call__(self, environ, start_response):
-        outside_url = self.xom.config.args.outside_url
+        outside_url = environ.get('HTTP_X_OUTSIDE_URL')
         if not outside_url:
-            outside_url = environ.get('HTTP_X_OUTSIDE_URL')
+            outside_url = self.xom.config.args.outside_url
         if outside_url:
             # XXX memoize it for later access from replica thread
             # self.xom.current_outside_url = outside_url
```

**Comment by mathbou** [comment]
Your patch seems to work, but the need for the flag and the headers tends to be heavy on the configuration side. 

I played a bit with the function, what about something like that?

```python
def __call__(self, environ, start_response):
    outside_url = self.xom.config.args.outside_url
	
    if not outside_url:
        scheme = environ.get('HTTP_X_FORWARDED_PROTO', "http")
        host = environ.get('HTTP_HOST')
        outside_url = f"{scheme}://{host}"

    # XXX memoize it for later access from replica thread
    # self.xom.current_outside_url = outside_url
    outside_url = urlparse(outside_url)
    environ['wsgi.url_scheme'] = outside_url.scheme
    environ['HTTP_HOST'] = outside_url.netloc
    if outside_url.path:
        environ['SCRIPT_NAME'] = outside_url.path
```
We only use standard headers from the request, and at the same time remove the X-Outside-Url requirement. 

Or eventually, if X-Outside-Url is mandatory for some cases, use the standard headers as a backup if it's not set, which would change the first line of my snippet with something like this:
```python
def __call__(self, environ, start_response):
    outside_url = environ.get('HTTP_X_OUTSIDE_URL', self.xom.config.args.outside_url)
    # ...
```

**Comment by fschulze** [comment]
The ``X-FORWARDED-PROTO`` etc headers are supported by waitress which we use as the server library, but they added a required option to trust the ip the request is coming from, which we don't support yet. I'll look into adding that. Also only with ``X-Outside-URL`` is it possible to use a sub path like ``https://example.com/devpi/``.

**Comment by mathbou** [comment]
I did some research about the prefix case, it turns out you can get rid of the X-Outside-URL. 

Using the following nginx.conf:

<details><summary>nginx.conf</summary>

```nginx
worker_processes  auto;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    upstream devpi {
        server backend:3141;
        # server worker-1:3141;
    }

    server {
        server_name localhost $hostname "";
        listen 80;

        gzip             on;
        gzip_min_length  2000;
        gzip_proxied     any;
        gzip_types       application/json;

        proxy_read_timeout 60s;
        client_max_body_size 64M;

        # set to where your devpi-server state is on the filesystem
        root /devpi/serverdir;

# -- no need of +f and +doc redirections

# ++ Redirect if no trailing slash
        location = /test {
            return 301 $scheme://$http_host$uri/;
        }

        location /test/ {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;

# ++ Set prefix in headers
            proxy_set_header X-Forwarded-Prefix test;

            proxy_pass http://devpi/;

        }


# ++ without prefix / location would look like this
#       location / {
#            proxy_set_header X-Real-IP $remote_addr;
#            proxy_set_header X-Forwarded-Proto $scheme;
#            proxy_set_header Host $http_host;
#
#            proxy_pass http://devpi/;
#
#        }

    }
}
```

</details>

Or those trafik labels:

```yaml
- 'traefik.enable=true'
- 'traefik.http.routers.devpi.rule=(Host(`devpi.local`) && PathPrefix(`/test`))'
- 'traefik.http.services.devpi.loadbalancer.server.port=3141'
- "traefik.http.middlewares.devpi-prefix.stripprefix.prefixes=/test"  # stripprefix set X-Forwarded-Prefix automatically
- 'traefik.http.routers.devpi.middlewares=devpi-prefix'
```

And a tiny update in my snippet:

```diff
if not outside_url:
    scheme = environ.get('HTTP_X_FORWARDED_PROTO', "http")
    host = environ["HTTP_HOST"]
    outside_url = f"{scheme}://{host}"

+    prefix = environ.get("HTTP_X_FORWARDED_PREFIX", "").strip("/")
+    if prefix:
+        outside_url = f"{outside_url}/{prefix}"
```

You can handle prefixes in a more elegant/flexible way. I'm not even sure that  `self.xom.config.args.outside_url` is still relevant doing this way

**Comment by Zeebrow** [comment]
Thank you @mathbou for the nginx config. I wanted to share my success for people like me who struggle with proxies.
My conf.d/nginx-devpi.conf file:
```
server {
    server_name 192.168.1.57;
    listen 80;
    gzip             on;
    gzip_min_length  2000;
    gzip_proxied     any;
    gzip_types       application/json;

    proxy_read_timeout 60s;
    client_max_body_size 64M;

    # set to where your devpi-server state is on the filesystem
    root /mnt/devpi-storage/devpi;

    location /devpi {
        return 301 $scheme://$http_host$uri/;
    }
    location /devpi/ {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Prefix devpi;
        proxy_pass http://localhost:3141/;
    }
}
```
and my devpi-server.yml devpi configuratin file:
```
devpi-server:
  serverdir: /mnt/devpi-storage
  host: localhost
  port: 3141
  outside-url: http://192.168.1.57/devpi
  absolute-urls: True
```
Again, thanks to you both for the detailed back-and-forth!

**Comment by melvyn-oviavo** [comment]
Adding 2 cents:
- It would be nice if the URL is being corrected from the provided argument, that a warning is shown. I thought the change in protocol was a bug and I'd edit the devpi client config to get rid of it.
- In the default nginx config `$scheme` is used. This is correct for the cases where nginx is the SSL terminator. However, if it's behind a load balancer or WAF that is the SSL terminator and it's running on insecure itself, your nginx config looks awesome, but is wrong and you need to replace `$scheme` with a hardcoded `https` for X-Outside-Url header.

**Comment by fschulze** [comment]
The upcoming devpi-client 6.0.0 will warn if scheme, host or port are rewritten by the server.

**Comment by fschulze** [comment]
See
https://m.devpi.net/fschulze/dev/devpi-client/6.0.0.dev9
and
https://m.devpi.net/fschulze/dev/+f/5fe/c5286f35d0d8a/devpi_client-6.0.0.dev9-py2.py3-none-any.whl

**Comment by fschulze** [comment]
@melvyn-apryl I think the following should make the scheme always work (got it from https://github.com/devpi/devpi/issues/539#issuecomment-1236411586). If that is the case, I will add it to the example config created by ``devpi-genconfig``:
```nginx
map $http_x_forwarded_proto $x_scheme {
    default $scheme;
    http http;
    https https;
}
server {
    ...
    location @proxy_to_app {
        proxy_pass http://localhost:%(port)s;
        proxy_set_header X-Forwarded-Proto $x_scheme;
        proxy_set_header X-outside-url $x_scheme://$http_host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
```

**Comment by melvyn-apryl** [comment]
@fschulze One minor improvement: `proxy_pass $scheme://localhost:%(port)s;`, but otherwise should work yes. Not in a position timewise to test on production environment, but I can later this week, if you're not in a hurry.

**Comment by fschulze** [comment]
I tested it locally with curl passing in the header and it seems to work.

@melvyn-apryl Why add the $scheme to the proxy url? The devpi-server app is always listening on http, never https.

**Comment by melvyn-apryl** [comment]
@fschulze For future https support :) Nah, you're right. Just forgot, devpi doesn't have the option to run on https itself.
