### ISSUE TITLE
threading.Thread.setDaemon has been deprecated in favor of setting daemon attribute directly in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [devpi/devpi#842]
Ref : python/cpython#25174

https://github.com/devpi/devpi/blob/2033769b98095b5e5da07a072d12bd4047e6e5a6/server/devpi_server/mythread.py#L46

**Comment by fschulze** [comment]
The attribute doesn't say when it was added, but the class takes a daemon keyword option since 3.3 which we should be able to use. Thanks for the heads up!

**Comment by tirkarthi** [comment]
The attribute is present since Python 2.7. This method was deprecated since Python 3.
