### ISSUE TITLE
Possible memory leak in 6.x

### ISSUE THREAD

**Issue by fschulze** [devpi/devpi#844]
I suspect the changed simple links parsing, but am still investigating. If anyone can provide hints, please do so in this ticket.

**Comment by fschulze** [comment]
So far it looks like it is no leak, but the changelog cache. Due to several projects on PyPI with many releases and the support of the "yanked" info, the changelog entries can become quite big. In addition to that on startup the database is iterated when devpi-web is installed or devpi-server is running as a replica.

I have a mitigation in the works, which on m.devpi.net reduces the memory usage from 8GB to 4GB and the spikes during indexing from 14GB to 9GB. This should be ready in the next days.

For quite some time there is also a new storage backend in the works which will further reduce this issue. It is planned for the next major release, but still needs work.

**Comment by fschulze** [comment]
On m.devpi.net I found an obvious real memory leak when fetching the simple project list of root/pypi. It is not leaking Python objects. So far I can only reproduce this on m.devpi.net which runs Python 3.7.3 on Debian 10.

**Comment by fschulze** [comment]
It also happens with self compiled Python 3.7.11 and 3.8.11.

**Comment by fschulze** [comment]
This also happens on FreeBSD, but I still haven't seen it on macOS.

The virtual and resident memory keeps increasing, but the allocated Python memory arenas stay roughly the same size after a while. Looking at the arena stats also indicates that fragmentation shouldn't be the problem. Still I see memory increases of several MB after stepping through pure Python code and manually running gc.collect() doesn't help.

**Comment by Derek-Xiang** [comment]
I saw a similar behaviour. After the devpi is up, within 5mins, the memory usage will climb quickly from 2G to almost 8G, is there any one had been through this?

**Comment by fschulze** [comment]
@Derek-Xiang the initial climb is normal if you use devpi-web. On startup it makes sure the search index is up to date and unfortunately has to touch quite a lot of data to do so.

The simplest way I can reproduce the leak works even with a new instance. Just fetch ``/root/pypi/+simple/`` one after another with curl. A smaller but still significant leak happens with large project pages like ``/root/pypi/+simple/botocore/``.

**Comment by Derek-Xiang** [comment]
Yes, with `journalctl -u devpi.service`, I found on starting up, it fetch all the data to the memory, although when export them, they are not like 8G big, but this can be the issue. Don't know if there is way to only load the data when the index is searched, cause there is no need to load everything at the beginning.

**Comment by fschulze** [comment]
It looks like ``waitress`` is the culprit, or the way we use it. As a test I'm currently using ``cheroot`` on m.devpi.net and it seems to have stable memory usage so far. I will observe this further, as with ``waitress`` it sometimes took a while to really grow with normal use.

**Comment by slav0nic** [comment]
is `cheroot` was used with same threads number (50)?
for example, for process memory ~300mb with waitress default 4 threads what i see:
![memory](https://user-images.githubusercontent.com/199555/146640125-2a200e59-9363-458f-9b5b-463581cec786.png)

it's looks like half of memory taken for cache

**Comment by fschulze** [comment]
This should be fixed with devpi-server 6.5.0 and waitress 2.1.1.
