### ISSUE TITLE
error ERROR [REP] 403 Forbidden: failed fetching http://localhost:8080/+changelog/0-?initial_fetch

### ISSUE THREAD

**Issue by Felix0829** [devpi/devpi#845]
devinit --role replica --master-url http://localhost:8080 --serverdir replica
devpi-server --master-url http://localhost:8080port 4000 --serverdir replica --host 0.0.0.0

log error ：
2021-07-30 17:15:24,118 ERROR [REP] 403 Forbidden: failed fetching http://localhost:8080/+changelog/0-?initial_fetch
2021-07-30 17:15:24,119 INFO  [REP] fetching http://localhost:8080/+changelog/0?initial_fetch
2021-07-30 17:15:24,126 ERROR [REP] 403 Forbidden: failed fetching http://localhost:8080/+changelog/0?initial_fetch
w2021-07-30 17:15:29,128 INFO  [REP] fetching http://localhost:8080/+changelog/0-?initial_fetch
2021-07-30 17:15:29,138 ERROR [REP] 403 Forbidden: failed fetching http://localhost:8080/+changelog/0-?initial_fetch

help

**Comment by fschulze** [comment]
The replica needs to use the same secret as the master. There should be info and possibly warnings in the master log. The master also requires the role option with master.

**Comment by fschulze** [comment]
No reply for several months, so I consider this fixed. Feel free to reopen with more info if there are still problems.

**Comment by nsballmann** [comment]
I had to find this issue to obtain this information. I expected information like this on [here](https://devpi.net/docs/devpi/devpi/stable/+doc/adminman/replica.html).
I suspected something like this, but not finding it in the documentation was surprising to me, given the good state of documentation for the whole devpi project.

**Comment by Felix0829** [comment]
The problem has been solved

**Comment by tomerschwartz24** [comment]
was it solved by using the same secret only? because even when i use the same secret (copying from master to replica) it still does that
