### ISSUE TITLE
Release devpi client to use latest pluggy

### ISSUE THREAD

**Issue by zerocewl** [devpi/devpi#850]
Please release a new version of `devpi-client` to allow pluggy >= 1.0.

The current version of `devpi-client` is `5.2.2` which still installs pluggy < 1.0 => `Collecting pluggy<1.0,>=0.6.0`

This leads later to an error with pip's dependency resolver if the pkg already uses the current version of pluggy `1.0.0`.

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
myFancyProject 0.11.5 requires pluggy==1.0.0, but you have pluggy 0.13.1 which is incompatible.
```

**Comment by fschulze** [comment]
I have release devpi-client 5.2.3 with an updated pluggin pin.
