### ISSUE TITLE
Replica 500s when visiting a package uploaded to a custom index

### ISSUE THREAD

**Issue by AWhetter** [devpi/devpi#862]
We have a replica devpi server and a master server. There's a custom index that's back by the pypi index:

```
http://devpi/root/custom-prod:
  type=stage
  bases=root/pypi
  volatile=False
  acl_upload=root
  acl_toxresult_upload=:ANONYMOUS:
  mirror_whitelist=
  pypi_whitelist=
```

When visiting the page of certain packages or when downloading those packages through pip, the devpi server returns a 500 error. 

The replica logs show the following:

```
2021-11-24 17:09:56,341 INFO  [REP] fetching http://devpi1/+changelog/32451
2021-11-24 17:10:00,947 INFO  [req8756] GET /root/custom-prod/mypackage/0.5.4
2021-11-24 17:10:06,103 WARNI [req8756] [Rtx32450] HTTPError during httpget of http://devpi1/root/pypi/+simple/mypackage/ at /usr/lib/python2.7/site-packages/devpi_server/extpypi.py:396::get_simplelinks_perstage
...
```

The master logs show the following:

```
2021-10-19 02:23:56,780 INFO  [req4639997] GET /root/pypi/+simple/mypackage
2021-10-19 02:23:56,907 INFO  [req4639998] GET /root/pypi/+simple/mypackage/
2021-10-19 02:23:56,909 ERROR [req4639998] [Rtx31045] while handling http://devpi1/root/pypi/+simple/mypackage/: The project mypackage does not exist.
```

So it looks like the replica isn't aware that the package is custom. The replica status page reports that it is up to date with the master. The package can be searched, and documentation that was uploaded with the package can also be viewed.
How can I further debug this issue?

`pip list`:
appdirs (1.4.4)
argon2-cffi (19.2.0)
attrs (21.2.0)
Babel (0.9.6)
backports.entry-points-selectable (1.1.0)
backports.ssl-match-hostname (3.5.0.1)
Beaker (1.5.4)
beautifulsoup4 (4.3.2)
bleach (3.1.0)
blessings (1.5)
bodhi (2.11.0)
bodhi-client (2.11.0)
CCColUtils (1.4)
cffi (1.14.6)
Chameleon (3.9.1)
chardet (2.2.1)
check-manifest (0.46)
Cheetah (2.4.4)
click (6.7)
configobj (4.7.2)
configparser (4.0.2)
configshell-fb (1.1.23)
contextlib2 (0.6.0.post1)
cupshelpers (1.0)
decorator (3.4.0)
defusedxml (0.7.1)
devpi-client (4.0.1)
devpi-common (3.3.1)
devpi-ldap (1.2.0)
devpi-server (4.9.0)
devpi-web (3.2.2)
distlib (0.3.2)
distro (1.2.0)
dockerfile-parse (0.0.5)
docutils (0.17.1)
empy (3.3.2)
enum34 (1.1.10)
ethtool (0.8)
execnet (1.9.0)
ExifRead (2.1.2)
eyeD3 (0.7.5)
fedpkg (1.36)
filelock (3.0.12)
fros (1.0)
futures (3.1.1)
git-review (1.24)
gitdb (0.6.4)
GitPython (1.0.1)
html5lib (0.999)
hupper (1.10.3)
importlib-metadata (1.3.0)
iniparse (0.4)
iotop (0.6)
ipaddress (1.0.16)
IPy (0.75)
itsdangerous (1.1.0)
javapackages (1.0.0)
Jinja2 (2.7.2)
kerberos (1.1)
kitchen (1.1.1)
kmod (0.1)
langtable (0.0.31)
lazy (1.4)
ldap3 (2.9.1)
lockfile (0.9.1)
lvm (2.02.180-2-RHEL7.-2018-07-20-)
lxml (3.2.1)
M2Crypto (0.21.1)
Magic-file-extensions (0.2)
Mako (0.8.1)
Markdown (2.4.1)
MarkupSafe (0.11)
meld (3.16.4)
meld3 (0.6.10)
mercurial (2.6.2)
munch (2.0.2)
nose (1.3.7)
numpy (1.7.1)
offtrac (0.1.0)
openidc-client (0.6.0)
osbs-client (0.32)
packagedb-cli (2.14.1)
packaging (21.0)
passlib (1.7.4)
Paste (1.7.5.1)
PasteDeploy (2.1.1)
pathlib (1.0.1)
pathlib2 (2.3.6)
pcp (4.1)
perf (0.1)
pexpect (2.3)
Pillow (2.0.0)
pip (8.1.2)
pkginfo (1.7.1)
plaster (1.0)
plaster-pastedeploy (0.7)
pluggy (0.13.1)
policycoreutils-default-encoding (0.1)
psutil (2.2.1)
psycopg2 (2.7.7)
py (1.10.0)
pyasn1 (0.4.8)
pycparser (2.20)
pycrypto (2.6.1)
pycups (1.9.63)
pycurl (7.19.0)
Pygments (1.4)
pygobject (3.22.0)
pygpgme (0.3)
pyinotify (0.9.4)
pyliblzma (0.5.3)
pyOpenSSL (0.13.1)
pyparsing (2.4.7)
pyramid (1.10.4)
pyramid-chameleon (0.3)
pyroute2 (0.4.13)
pysmbc (1.0.13)
python-augeas (0.5.0)
python-bugzilla (2.2.0)
python-dateutil (2.8.2)
python-dmidecode (3.10.13)
python-fedora (0.10.0)
python-linux-procfs (0.4.9)
python-yubico (1.2.3)
pyudev (0.15)
pyusb (1.0.0b1)
pyxattr (0.5.1)
pyxdg (0.25)
PyYAML (3.11)
readme-renderer (29.0)
repoze.lru (0.7)
requests (2.6.0)
requests-kerberos (0.7.0)
rpkg (1.57)
rtslib-fb (2.1.63)
scandir (1.10.0)
scdate (1.10.6)
schedutils (0.4)
seobject (0.1)
sepolicy (1.1)
setproctitle (1.1.6)
setuptools (0.9.8)
six (1.16.0)
slip (0.4.0)
slip.dbus (0.4.0)
smmap (0.9.0)
SSSDConfig (1.16.2)
strictyaml (1.4.4)
supervisor (3.1.4)
targetcli-fb (2.1.fb46)
targetd (0.8.5)
Tempita (0.5.1)
tito (0.6.11)
toml (0.10.2)
tornado (4.2.1)
tox (3.24.3)
translationstring (1.4)
UNKNOWN (0.0.0)
urlgrabber (3.10)
urllib3 (1.10.2)
urwid (1.1.1)
venusian (1.0a7)
virtualenv (20.7.2)
waitress (1.4.2)
webencodings (0.5.1)
WebOb (1.8.7)
Whoosh (2.7.4)
wxPython (2.8.12.0)
wxPython-common (2.8.12.0)
yum-langpacks (0.4.2)
yum-metadata-parser (1.1.4)
zim (0.69.1)
zipp (0.5.0)
zope.deprecation (4.4.0)
zope.interface (5.4.0)

This is on CentOS 7.6
```bash
λ python --version
Python 2.7.3
λ uname -r
3.10.0-957.21.3.el7.x86_64
```

Package versions:
devpi-ldap-1.2.0
devpi-server-4.9.0
devpi-web-3.2.2

**Comment by fschulze** [comment]
1. In the notification mail there was ``while handling http://zrodevpi1/root/pypi/+simple/apitrack/: The project mypackage does not exist``, but it isn't there in the ticket. Did you edit something? Are you sure you copied the log output correctly?
2. You use devpi-server 4.9.0, which is really old and there have been plenty of changes and fixes in the meantime. I would suggest to upgrade first and try again. Such old versions aren't supported.

**Comment by AWhetter** [comment]
1. I was trying to remove some internal server names and internal package names but I missed one 😅 

2. Oh wow we _are_ out of date. I totally missed that devpi doesn't support Python 2 anymore. Sorry for wasting your time. I'll close this for now, see if we can update to a newer version, and reopen if we're still having problems.

Thanks for your help!
