### ISSUE TITLE
Is there any way to get index from pypi without downloading packages

### ISSUE THREAD

**Issue by wqh17101** [devpi/devpi#872]
Hi there, i want to block some packages by remove them from index of Pypi.
So, i want to get the index from Pypi without downloading packages and then modify part of them from index.
Is it possible?

**Comment by fschulze** [comment]
Not directly, but take a look at [devpi-constrained](https://pypi.org/project/devpi-constrained/). With that you can add a constrained index that inherits from ``root/pypi`` and block specific packages and/or versions.

**Comment by fschulze** [comment]
It is not in the readme and I haven't tested it yet, but it should be possible to block a whole package with ``pkg>=0``.

**Comment by wqh17101** [comment]
yeah,but as a  devpi-server , i don`t know whether it will download index and packages together when it starts.

**Comment by fschulze** [comment]
Packages are only downloaded when first requested. You can also set ``mirror_use_external_urls=true`` on the mirror index to prevent downloads altogether.

**Comment by wqh17101** [comment]
You mean the first time i use `pip install -i xxxx`?

**Comment by fschulze** [comment]
Yes, or directly downloading any of the URLs listed in ``/root/pypi/+simple/{pkg}/``.

**Comment by wqh17101** [comment]
emmm,i don`t want it to download packages.

**Comment by fschulze** [comment]
It won't unless you access them. Just looking at ``/root/pypi/+simple/{pkg}/`` doesn't download them. You can freely look at all the pages, just don't access the release URLs.

**Comment by fschulze** [comment]
I think everything was explained. If there are still problems, feel free to reopen.
