### ISSUE TITLE
Automatically refresh mirror in background

### ISSUE THREAD

**Issue by Mr-Pepe** [devpi/devpi#911]
I am using devpi as a local mirror of a physically remote PyPI server that has high latency (around 400ms) and slow downloads. When I install a package after `mirror-cache-expiry` has expired, devpi checks for new versions on the remote PyPI which makes package installation really slow. Is there a setting that makes devpi check for new versions of all cached packages in the background every `mirror-cache-expiry` seconds? That way, my mirror would always be up to date and installation from my local devpi server would be very fast.

**Comment by fschulze** [comment]
There is no such option yet. I plan to improve the PyPI fetching a bit by using the provided ETags, which should make cases with no changes faster and reduce bandwidth usage. I'm also thinking about a PyPI specific plugin to restore watching for changes using the RSS feeds (until devpi-server 2.3.0 it was done using the XMLRPC API).

**Comment by Mr-Pepe** [comment]
Thank you for the prompt reply! That sounds like a good solution for the official PyPI but I am mirroring a private [pypiserver](https://github.com/pypiserver/pypiserver) instance.
I am thinking about writing a cron job that simply installs all cached packages every `mirror-cache-expiry - x` seconds. Do you have a better idea for a quick fix?

**Comment by Mr-Pepe** [comment]
Got it! Feel free to close or keep this ticket as you see fit.
