### ISSUE TITLE
Pip caching support

### ISSUE THREAD

**Issue by Mr-Pepe** [devpi/devpi#912]
It seems that pip's caching mechanism does not work when using a devpi server as a mirror. However, [this issue](https://github.com/devpi/devpi/issues/812) suggests that it worked at some point. Is this a bug or is my configuration incorrect?

I am using pip 22.1.2 and devpi-server 6.5.1. The configuration for my mirror is:

```
type=mirror
volatile=True
mirror_url=https://pypi-somewhere-else.de/simple/
mirror_use_external_urls=False
```

Downloads from my local devpi server are very fast but still mean that packages need to be copied unnecessarily.

**Comment by fschulze** [comment]
I'm not sure what you mean. Could you describe what you expect and what happens instead in more detail?

**Comment by fschulze** [comment]
For ``http://`` there is no caching, see https://github.com/pypa/pip/blob/main/src/pip/_internal/network/session.py#L393 and https://github.com/pypa/pip/blob/main/src/pip/_internal/network/session.py#L366

**Comment by Mr-Pepe** [comment]
Understood, thank you very much :+1:
