### ISSUE TITLE
Consider making aiohttp an extra

### ISSUE THREAD

**Issue by gaborbernat** [devpi/devpi#918]
aiohttp is a compiled c-extension so it's causing some issues with adopting Python 3.11 changes. Considering we do not really need aiohttp for sync models, do we really need to have aiohttp a hard dependency?

**Comment by fschulze** [comment]
It is required for mirrors and ``root/pypi`` is created by default.
It would be hard to explain and usability would suffer. Python 3.11 is still an rc and it is very likely that there will be updated releases soon before or right after release. It is just™ a matter of running current cython and make wheels with Python 3.11.

**Comment by gaborbernat** [comment]
> . Python 3.11 is still an rc and it is very likely that there will be updated releases soon before or right after release. It is just™ a matter of running current cython and make wheels with Python 3.11.

This blokes tox from adding 3.11 support which is a bit of PITA.

**Comment by fschulze** [comment]
Huh, how does it block tox? Do you have a ticket or something for that?

**Comment by gaborbernat** [comment]
Can't tell because this stops the test suite from running https://github.com/tox-dev/tox/pull/2466
