### ISSUE TITLE
ConnectionResetError(104, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by 369Martin369** [devpi/devpi#922]
my binance-connector scripts runs for hours and....sporadically they abort

These are the 2 error I suffer:

1) requests.exceptions.ConnectionError: ('Connection aborted.', OSError(107, 'Transport endpoint is not connected'))
2) requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

see more here: [https://replit.com/@CompensationNetwork/versioncheck/#errors.txt]
full program: [https://replit.com/@CompensationNetwork/versioncheck#main.py]

Since I have no watchdog, I have to re-start the program manually.
Please be so kind and suggest me how to handle such errors, so that the program restarts from scratch after waiting time of 10 sec.

Thanks a lot for your Consulting
Was not able to find fixes anywhere....

**Comment by fschulze** [comment]
This has nothing to do with devpi.
