### ISSUE TITLE
remove dependency on execnet serializer

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [devpi/devpi#923]
for the next major iteration i plan to drop it
as far as im aware devpi is the only external user

this has a >6 month time horizen

**Comment by fschulze** [comment]
Thanks for the heads up, but it is already fine by me. I have a custom optimized version in ``devpi_server/fileutil.py``. The dependency is only left in tox.ini for compatibility tests. I can easily remove that once it starts failing.
