### ISSUE TITLE
Version 6.6.0 of the server is 100 time slower to list packages

### ISSUE THREAD

**Issue by wouterdb** [devpi/devpi#929]
# Problem

After upgrading to server version above 6.6.0, we observed that a package listing took 39s instead of 0.39s.
After downgrading to 6.5.1 performance was restored 

# Probable cause
We traced this issue back to two recent changes:

1. require full index search for `has_project_perstage` https://github.com/devpi/devpi/commit/bf5fa1162cf8b2d561115ed29a790e685abfc127#diff-271e697ddfa170f45a0252964ddccc2a50567df3090b84a0b0c43664f2919664R724
1. introduction of the normalization, even when hitting the cache https://github.com/devpi/devpi/commit/3e9384d4d0854481eb8edca1fd4f6d51c86209ae

# Details

We produced some performance traces and it struck us that two calls to get a project fan out to 95 list project calls and 38M name normalizations. 

Traces attached below :

![image](https://user-images.githubusercontent.com/1788254/197192233-e4592230-bdd8-4dfd-99e3-5df83510ef41.png)

We removed `ensure_unicode` from the code to get 

![image](https://user-images.githubusercontent.com/1788254/197192487-60121451-abcd-4477-9822-41cf217484a3.png)

**Comment by fschulze** [comment]
Thanks for the detailed report. How much was the performance improved for you after the removal of ``ensure_unicode``? It would be great if that change alone would be enough, as it would be hard to impossible to get rid of the repeated ``normalize_name`` calls without a database change which would require a major release and an export/import cycle to upgrade.

**Comment by fschulze** [comment]
I mean the total runtime of 39s vs the ``ensure_unicode`` removal vs the original version with 0.39s.

**Comment by fschulze** [comment]
The only thing we could change without a db schema change is storing the normalized names as a dictionary in ``cache_projectnames`` instead of the un-normalized names in the current ``frozendict``. That change was done to reduce memory usage though as the previous use of a ``set`` seemed to cause increased memory usage over time and I didn't test with a ``dict`` yet.

**Comment by fschulze** [comment]
Which view does this affect the most? I see that the second graph is for ``/user/index/project``, but I'm not sure about the first graph, is that the same? My guess is that ``/user/index`` is the slowest as that will check each uploaded package name against the mirror. With many private packages that would explain the repeated ``has_project_perstage`` calls. For ``/user/index/project`` it looks like ``has_project_perstage`` is called for each version. It should be possible to add some simple caching for that. With ``/user/index/project/version`` there should only be one call.

**Comment by wouterdb** [comment]
Hi,

I don't have the data anymore about the normalization cost, but removing the ensure_unicode didn't help a lot, I think the other change, where `self.get_simplelinks_perstage(project)` is replaced by `return project in self.list_projects_perstage()` is a lot more significant, as it makes us consider every package in the python ecosystem when listing all version for a specific package. 

Wouter

**Comment by fschulze** [comment]
Could you try this dev release?

https://m.devpi.net/fschulze/dev/devpi-server/6.8.0.dev0
https://m.devpi.net/fschulze/dev/+f/e9d/aea78508f8c26/devpi_server-6.8.0.dev0-py3-none-any.whl

**Comment by jdavisp3** [comment]
Might be seeing this as well. When this fix is released can it be upgraded in place? Or will we need an export/import? Also, is adding /+simple/ still recommended for best performance?

**Comment by fschulze** [comment]
Have you been able to test the 6.8.0.dev0 release?

> Might be seeing this as well. When this fix is released can it be upgraded in place? Or will we need an export/import?

It is drop in with no export/import.

> Also, is adding /+simple/ still recommended for best performance?

In general yes, but with latest pip using the json Accept headers it shouldn't matter anymore.

**Comment by jdavisp3** [comment]
> Have you been able to test the 6.8.0.dev0 release?

I will try to test today.

> > Might be seeing this as well. When this fix is released can it be upgraded in place? Or will we need an export/import?
> 
> It is drop in with no export/import.

🆒 

> > Also, is adding /+simple/ still recommended for best performance?
> 
> In general yes, but with latest pip using the json Accept headers it shouldn't matter anymore.

Awesome, thanks!

**Comment by jdavisp3** [comment]
Working functionally correctly so far @fschulze, using this version:

https://m.devpi.net/fschulze/dev/+f/187/bc7b2db56e27c/devpi_server-6.8.0.dev0-py3-none-any.whl#sha256=187bc7b2db56e27cd02453df27ed65a1a5a3e8a64eaf654e5e607efff47c833e

What's a good way to test performance? It's not clear to me which package is really slow.

**Comment by fschulze** [comment]
The impact is highest on the devpi-web index view when there are several private packages with names that are not on PyPI, the more there are the more pronounced it becomes.

**Comment by jdavisp3** [comment]
> The impact is highest on the devpi-web index view when there are several private packages with names that are not on PyPI, the more there are the more pronounced it becomes.

Ok, I was able to deploy to an instance with ~400 internally published packages that also mirrors pypi.org. Loading the index page and the simple index page seemed pretty speedy (<1s).  Doing a search was the same.

**Comment by jdavisp3** [comment]
I was also able to install an application with ~350 dependencies including internal and external using this version of devpi-server.

**Comment by wouterdb** [comment]
The patched 6.8.0.dev0 reduces the time from `34s` to `1s`, which is still slower than the `0.39s` it was on older version, but manageable.

**Comment by fschulze** [comment]
@wouterdb I'm investigating to switch to a dictionary which would map from the name to the normalized name. That should restore the original performance. I think that will go into a point release though, so the worst performance regression will be gone sooner.

**Comment by brupelo** [comment]
@wouterdb That profile graph looks neat 😮 ... which tool  did you use to generate it?

**Comment by wouterdb** [comment]
> @wouterdb That profile graph looks neat open_mouth ... which tool did you use to generate it?

https://github.com/jrfonseca/gprof2dot

**Comment by jdavisp3** [comment]
> @wouterdb I'm investigating to switch to a dictionary which would map from the name to the normalized name. That should restore the original performance. I think that will go into a point release though, so the worst performance regression will be gone sooner.

So 6.8.0 will be the currently tested fix?

**Comment by fschulze** [comment]
This one, yes:
https://m.devpi.net/fschulze/dev/devpi-server/6.8.0.dev3
https://m.devpi.net/fschulze/dev/+f/d93/6f0c1a1642c1c/devpi_server-6.8.0.dev3-py3-none-any.whl

**Comment by fschulze** [comment]
This should be fixed with devpi-server 6.8.0.

**Comment by jdavisp3** [comment]
@fschulze Thank you ❤️
