### ISSUE TITLE
is there a setup possible that allows whitelisting from one base but not the other?

### ISSUE THREAD

**Issue by krpatter-intc** [devpi/devpi#933]
Is it possible to add intermediate indexes such that I could effectively create a different whitelist based on the base (or mirror in this case) ?

In this scenario: `helloworld==1` might be on root/something-else, and `helloworld==2` is on production, but we want to make sure to not accidently grab `helloworld` from root/pypi

```mermaid
flowchart TD
    production --whitelist=* --> root/something-else
    production --whitelist=none--> root/pypi
``` 
   
If the "why" matters: I was hoping offload really old releases from our devpi server to a different server. This would save disk space on my primary server my replicas. Sure they may mirror the versions most needed, but it wouldn't be N replicas with ALL the old versions.

Any ideas/feedback would be appreciated. Thank you.

**Comment by fschulze** [comment]
Currently I can't think of a way to achieve this. The more I think about it the more I come to the conclusion, that mirror indexes currently are still stuck in the original PyPI only mode. It would make sense that they work more like private indexes in regard to ``bases`` etc, so they can have parents and not only be roots.

So your setup would look like this:
```mermaid
flowchart TD
 production --whitelist=* --> root/something-else --whitelist=none --> root/pypi
```

Not entirely sure this wouldn't open another can of worms in regard to whitelist and filtering etc.

**Comment by krpatter-intc** [comment]
That's what I feared, but thank you for the quick response.

**Comment by fschulze** [comment]
Reopening for future consideration.
