### ISSUE TITLE
How to install devpi-server service on windows10?

### ISSUE THREAD

**Issue by brupelo** [devpi/devpi#936]
Hi,

I'm trying to install a win10 service with the latest release of devpi-server, here's the steps I've followed:

- Create virtualenv: `virtualenv venv_devpi`
- Activate: `venv_devpi\Scripts\activate`
- Install devpi-server: `pip install devpi-server`
- Test the server (it runs at localhost:3141): `devpi-server`
- Stop it: `ctrl+c`
- Create windows service: `sc create devpi-server binPath="D:\venv_devpi\Scripts\devpi-server.exe"`
- Test new service: `sc start devpi-server`

And I'm getting the following error:

    # sc start devpi-server [SC] StartService FAILED 1053:
    
    The service did not respond to the start or control request in a timely fashion.

Here's the information of the service:

    # sc qc devpi-server
    [SC] QueryServiceConfig SUCCESS
    
    SERVICE_NAME: devpi-server
            TYPE               : 10  WIN32_OWN_PROCESS
            START_TYPE         : 3   DEMAND_START
            ERROR_CONTROL      : 1   NORMAL
            BINARY_PATH_NAME   : D:\venv_devpi\Scripts\devpi-server.exe
            LOAD_ORDER_GROUP   :
            TAG                : 0
            DISPLAY_NAME       : devpi-server
            DEPENDENCIES       :
            SERVICE_START_NAME : LocalSystem

I know if you run `devpi-gen-config` one folder with some instructions for windows will be generated and it's suggesting to use the tools `instsrv.exe` or `srvany.exe`, neither of them not being available on windows10.

Is there any easy way to fix this error code `1053` without relying on these old tools from windows2003 server?

Anyway, I've tried using [nssm](https://nssm.cc/) tool and here's what I've got:

![image](https://user-images.githubusercontent.com/18058492/202894946-2344bade-7899-4f53-8496-bd97def09cd6.png)

After pressing install the service and querying the info...

![image](https://user-images.githubusercontent.com/18058492/202894993-d94ffe1d-6891-446c-90dd-c51867c800be.png)

So If I try to start it will fail :(

Has anyone been able to install devpi-server on windows 10 successfully?

**Comment by fschulze** [comment]
Using ``sc`` directly doesn't work, as it expects the application to respond a certain way when started. It seems nssm is still the way to go. Maybe the following will help:
https://stackoverflow.com/questions/32404/how-do-you-run-a-python-script-as-a-service-in-windows

**Comment by brupelo** [comment]
@fschulze Hi Florian, thanks for taking a look to this one.

Mmmm, this is strange... so maybe I'm not using properly nssm? As you can see above when I've created the service using nssm I've specified the devpi-server executable path that lives in the Scripts folder of the virtualenv... but you can see the information displayed by `sc qc TestDevpiServer` is fishy as the `BINARY_PATH_NAME` field is pointing out to nssm.exe path directly... That's weird :/

Just for the record I've compiled the latest version of nssm from the official tracker https://git.nssm.cc/nssm/nssm

Were you able to make it work with nssm?

I'll read carefully that SO thread later on and try again just in case... But I'm not sure why nssm isn't using the path I've specified tbh

**Comment by brupelo** [comment]
@fschulze Ok, here's the thing, I've created just a little dummy flask server, make an exe out of it on a virtualenv and created the service with nssm, it worked like a charm without any hazzle... I've been even able to redirect stdout/stderr to a file and it works perfectly. Also it seems it's the normal thing to see the path pointing to nssm, ie:

```
# sc qc flask_test
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: flask_test
        TYPE               : 10  WIN32_OWN_PROCESS
        START_TYPE         : 2   AUTO_START
        ERROR_CONTROL      : 1   NORMAL  BINARY_PATH_NAME   : d:\software\nssm\out\Release\win32\nssm.exe
        LOAD_ORDER_GROUP   :
        TAG                : 0
        DISPLAY_NAME       : flask_test
        DEPENDENCIES       :
        SERVICE_START_NAME : LocalSystem
```

I'll try do the same now with nssm to see if it's writing anything to stdout/stderr and go from there... :/ . The good news is that
nssm seems to be the easiest way to go here on win10

**Comment by brupelo** [comment]
Ok, I've finally managed to solve it!

Problem wasn't nssm... problem was just me not paying attention... The solution is just making sure to add stdout & stderr redirection when installing the service so you'll know why the service wasn't not able to run, as simple as that.
