### ISSUE TITLE
Packaging 22.0 breaks devpi-server for many packages

### ISSUE THREAD

**Issue by fyhertz** [devpi/devpi#939]
Hello,

To reproduce the issue, start a fresh instance of `devpi-server` and access http://localhost:3143/root/pypi/pytz. `packaging` 22.0 raises an exception when `devpi` tries to parse old versions of `pytz` such as `2004d`.

I've made a PR to force `packaging <= 21.3` here: https://github.com/devpi/devpi/pull/938

Regards,
Simon

**Comment by fschulze** [comment]
I created a fix without pinning. See https://github.com/fschulze/devpi/commit/2aba62c961653aa82181b201995ecbdcb63ce639

When there is a parse error, a new legacy version is created which is always sorting smaller than a regular version and uses "natural" sorting with other legacy versions. The order might be different than with packaging. I think I should warn about that in the changelog, but by now every tool warns about legacy version strings, so people shouldn't be using them anymore for current releases. It may affect devpi-client commands like ``remove`` with any specifier other than ``==``.

Could you try with this release?
https://m.devpi.net/fschulze/dev/devpi-common/3.7.1.dev0
https://m.devpi.net/fschulze/dev/+f/6ac/e7aaa2d1196f1/devpi_common-3.7.1.dev0-py2.py3-none-any.whl

**Comment by fschulze** [comment]
I think I will do a 3.7.1 with the pinning fix and a 4.0.0 with my fix with the next major devpi-server and client releases, as all devpi packages have a ``devpi-common<4`` pin. This should prevent any surprises.

**Comment by fschulze** [comment]
Fixed with released devpi-common 3.7.1.

**Comment by nlewo** [comment]
@fschulze Would it be possible to publish a new release with the support of `packaging` in version 22?

In [nixpkgs](https://github.com/NixOS/nixpkgs), we are currently no longer able to build `devpi-common` because the dependencies of `devpi-common`  already switched to `packaging-22.0`: https://github.com/NixOS/nixpkgs/issues/231346.
