### ISSUE TITLE
Error retrieving particular (google) package

### ISSUE THREAD

**Issue by VolvoxGlobator** [devpi/devpi#941]
I am getting error for
http://my_server:3141/root/pypi/+simple/google-api-python-client/
other packages seem to work fine, e.g. I get proper output for
http://my_server:3141/root/pypi/+simple/progressbar2/

I am kinda stuck what to do as the setup seems to be working for other packages I have tried. 

devpi-server 6.8.0
pip list in attachment (for .venv via pipenv)
Windows server 2016, Python 3.9.7, pipenv 2022.11.30

server launched:
pipenv run devpi-server --host my_server --port 3141 --serverdir d:\devpi\data

[pip_list.txt](https://github.com/devpi/devpi/files/10245828/pip_list.txt)

[devpi_stdout.log](https://github.com/devpi/devpi/files/10246040/devpi_stdout.log)

**Comment by fschulze** [comment]
See #939 and #940. Update to devpi-common 3.7.1.

**Comment by VolvoxGlobator** [comment]
Thanks a lot!
