### ISSUE TITLE
Configuring the sphinx-build path to conf.py

### ISSUE THREAD

**Issue by Decee1** [devpi/devpi#951]
Hello,

Some time ago i asked a question on stacked but nobody provided a answer to the question:
https://stackoverflow.com/questions/74773453/configuring-source-dir-for-sphinx-documentation-conf-py-file/75182823#75182823
Could somebody take a look at it? It is pretty relevant to how sphinx is built and in my case causes a lot of issues.

**Comment by Decee1** [comment]
I can see that the fix for this is implemented in next release of the client.
Could i push forward for a release of client?

**Comment by fschulze** [comment]
Oh, I didn't realize I hadn't released that fix yet. I hope to do that by next week.

**Comment by Decee1** [comment]
Good, surely looking forward to this this release. Thank you.

**Comment by Decee1** [comment]
@fschulze Hello again, 
Just a reminder to make a new release

**Comment by fschulze** [comment]
I released devpi-client 6.0.3.
