### ISSUE TITLE
sqlite3.OperationalError: attempt to write a readonly database

### ISSUE THREAD

**Issue by aalcalajitc** [devpi/devpi#952]
devpi-server won't start saying that `sqlite3.OperationalError: attempt to write a readonly database`, noticed that a `.sqlite-journal` file was created in the server directory next to the database file.

Is there a way to recover the database and get this devpi-server instance working again?

**Comment by fschulze** [comment]
First I would recommend making a backup before trying a recovery.

Then check the files and folders, it could be as simple as wrong permissions.

Then I would look into sqlite documentation or search the internet on how to recover from that if it isn't solved by anything simple.

**Comment by fschulze** [comment]
No follow-up for several months. If this is still an issue, feel free to re-open.

**Comment by aalcalajitc** [comment]
Thanks very much for the follow-up, in the end I managed to get devpi-server to work again by copying over the database from a working replica plus manual patches regarding missing files.
