### ISSUE TITLE
I want to modify the url

### ISSUE THREAD

**Issue by zhenzi0322** [devpi/devpi#956]
hold

http://{ip}:3141/root/pypi/+Simple

Repair

http://{ip}:3141/pypi/simple

How to modify it?

```
 pip install django==2.2.0 -i http://xxxx:3141/root/pypi/+simple  --trusted-host xxxx:3141
```
Modify to
```
 pip install django==2.2.0 -i http://xxxx:3141/pypi/simple  --trusted-host xxxx:3141
```

**Comment by fschulze** [comment]
This is possible with nginx or another proxy in front of devpi-server. You can use ``devpi-gen-config`` to create example configurations. You then need to change the configuration of the proxy to rewrite the URL. See for example https://nginx.org/en/docs/http/ngx_http_rewrite_module.html
