### ISSUE TITLE
How to modify the downloaded image source mirror_ url

### ISSUE THREAD

**Issue by zhenzi0322** [devpi/devpi#957]
```
devpi index root/pypi mirror_url="https://pypi.tuna.tsinghua.edu.cn/simple"
```
Not effective

![image](https://user-images.githubusercontent.com/34839719/223682754-d2533c8b-6e99-4726-b7b6-3bf426c82514.png)

**Comment by fschulze** [comment]
There is most likely old data from the previous URL in the database.

You should delete ``root/pypi`` and create it again with the new ``mirror_url``.

**Comment by zhenzi0322** [comment]
> There is most likely old data from the previous URL in the database.
> 
> You should delete `root/pypi` and create it again with the new `mirror_url`.

I rebuilt a docker with new data

**Comment by zhenzi0322** [comment]
> There is most likely old data from the previous URL in the database.
> 
> You should delete `root/pypi` and create it again with the new `mirror_url`.

How to delete a database

**Comment by fschulze** [comment]
You can delete ``root/pypi`` with ``devpi index --delete root/pypi``.
Then you create it again with the new url ``devpi index -c type=mirror mirror_url=https://pypi.tuna.tsinghua.edu.cn/simple``.

If you want to start from the beginning with an empty database from nothing, you can prevent the creation of ``root/pypi`` with the ``--no-root-pypi`` for ``devpi-init``. Then you can use ``devpi index -c type=mirror mirror_url=https://pypi.tuna.tsinghua.edu.cn/simple`` as above.
