### ISSUE TITLE
devpi_server.model.UpstreamError: serial mismatch on

### ISSUE THREAD

**Issue by zhenzi0322** [devpi/devpi#958]
```
docker logs devpi
```

![image](https://user-images.githubusercontent.com/34839719/223908775-3b46492d-88cd-40ac-aaa0-416ab2d6b376.png)

devpi_server.model.UpstreamError: serial mismatch on GET URL('https://pypi.tuna.tsinghua.edu.cn/simple/django/'), cache_serial 16940182 is newer than returned serial -1

**Comment by fschulze** [comment]
This is caused by the change of the ``mirror_url`` in https://github.com/devpi/devpi/issues/957
