### ISSUE TITLE
 How do I write a theme web for devpi

### ISSUE THREAD

**Issue by zhenzi0322** [devpi/devpi#961]
How do I write a theme web for devpi

**Comment by fschulze** [comment]
Take a look at https://github.com/fschulze/devpi-example-theme

**Comment by zhenzi0322** [comment]
Thank you.

**Comment by zhenzi0322** [comment]
There are theme examples, and how can I use them in devpi? Easy to debug operation

**Comment by fschulze** [comment]
The ``devpi_example_theme/theme`` folder can be used with ``devpi-server --theme`` when devpi-web is installed. For the other use cases shown in the example you have to install the package and it will work automatically because of this: https://github.com/fschulze/devpi-example-theme/blob/master/devpi_example_theme/__init__.py#L11

**Comment by zhenzi0322** [comment]
> Use `devpi-server --theme ./devpi_example_theme/theme`

There will be errors when starting this method.

![image](https://user-images.githubusercontent.com/34839719/228456439-a483dced-f59f-4ad4-87ab-be393b3f805b.png)

error:
```bash
 File "notfound_c8e146b183910da68a9a0290a3fa599d.py", line 239, in render
 - Expression: "request.macros['footer']"
 - Filename:   ... WaY0Jl\lib\site-packages\devpi_web\templates\notfound.pt
 - Location:   (line 14: col 33)
 - Source:     ... al:footer use-macro="request.macros['footer']" />
                                        ^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  view: <function ('notfound',) at 0x1e3d8b48dc0>
               renderer_name: templates/notfound.pt
               renderer_info: <RendererHelper ('None',) at 0x1e3d9fdb430>
               context: <HTTPNotFound ('None',) at 0x1e3da112620>
               request: <Request ('None',) at 0x1e3d9fdb580>
               req: <Request ('None',) at 0x1e3d9fdb580>
               get_csrf_token: <partial ('None',) at 0x1e3da0895d0>
               msg: <HTTPNotFound ('None',) at 0x1e3da112620>
               target_language: <NoneType ('None',) at 0x7ffb9fa687f8>
               repeat: <RepeatDict ('None',) at 0x1e3d9fdb460>
               macroname: request.macros['footer']

````

**Comment by fschulze** [comment]
I have to look into that error.

Maybe this is a simpler example:
https://github.com/devpi/devpi.net/tree/master/theme

**Comment by fschulze** [comment]
There are also some docs: https://devpi.net/docs/devpi/devpi/stable/+d/adminman/web.html#themes

**Comment by zhenzi0322** [comment]
Ok.
