### ISSUE TITLE
How to make devpi automatically download packages

### ISSUE THREAD

**Issue by zhenzi0322** [devpi/devpi#962]
Is there any way to automatically download devpi in the background https://pypi.org Packages in

**Comment by fschulze** [comment]
No, this needs to be triggered externally. A full mirror is way too big nowadays (those AI packages have huge binary releases) and everyone needs a different set of packages. Also many of the old releases are never used anymore, except if you have legacy software relying on them.

**Comment by zhenzi0322** [comment]
> In the past there was a feature which downloaded new releases of packages which had downloads before. I always thought about creating a plugin to restore that, but nobody asked for it yet.

I may need to use it, but the question is how to use this plug-in in devpi

**Comment by fschulze** [comment]
It does not exist yet. I would have to write it.
