### ISSUE TITLE
[devpi-server] Is there a way to fallback to a secondary mirror-url?

### ISSUE THREAD

**Issue by donateur** [devpi/devpi#975]
Hello, thanks so much for writing and maintaining devpi!

I've got an unusual situation.  I need to cache pypi in an environment which may as well be disconnected from the internet.  Further complicating things, I don't have a reliable pypi mirror to source from, but two different mirrors which each may be missing different packages.

Is there any way to use devpi-server such that if it is unable to find a module from one mirror_url it could retry with a different mirror_url?
_(I've tried to use apache in front of devpi-server but can't rewrite on 404 as well as proxy to either server...it's a long story but it may not be a viable option)_

Thanks again!

**Comment by fschulze** [comment]
There is an experimental ``--offline-mode``, but I'm not sure that is applicable here.

I would try to add both mirrors as separate ``mirror`` indexes and then create an index which has both as ``bases``.

**Comment by donateur** [comment]
> There is an experimental `--offline-mode`, but I'm not sure that is applicable here.
> 
> I would try to add both mirrors as separate `mirror` indexes and then create an index which has both as `bases`.

Thanks so much!  I won't be able to test this for a few days but will get back to you.

**Comment by donateur** [comment]
Thanks for your help @fschulze.

It turns out that for policy reasons access between the server running devpi-server and the second pypi repo wasn't permitted.  So we ended up using a pip.conf which uses and `--extra-index-url` with the second repo.  While we can't determine which repo will be used, it doesn't really matter, clients will use the newer version of a package with the same name from whichever repo is more up to date.

Thanks again!
