### ISSUE TITLE
Pluggy's update broke devpi

### ISSUE THREAD

**Issue by max851** [devpi/devpi#980]
installation by default broke devpi (fast fix - pin pluggy to 1.0.0 version):

> /---/.local/share/virtualenvs/PyHub2-wdL7C7Hv/bin/activate
> (PyHub2) ➜  PyHub2 git:(master) ✗ devpi-server --help                                                     
> Traceback (most recent call last):
>   File "/Users/---/.local/share/virtualenvs/PyHub2-wdL7C7Hv/bin/devpi-server", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/Users/---/.local/share/virtualenvs/PyHub2-wdL7C7Hv/lib/python3.11/site-packages/devpi_server/main.py", line 75, in main
>     pluginmanager = get_pluginmanager()
>                     ^^^^^^^^^^^^^^^^^^^
>   File "/Users/---/.local/share/virtualenvs/PyHub2-wdL7C7Hv/lib/python3.11/site-packages/devpi_server/config.py", line 49, in get_pluginmanager
>     pm._implprefix = "devpiserver_"
>     ^^^^^^^^^^^^^^
> AttributeError: 'PluginManager' object has no attribute '_implprefix'
>

**Comment by jrast** [comment]
See also: https://github.com/pytest-dev/pluggy/issues/402

**Comment by fschulze** [comment]
Thanks for the quick heads up, the release is out for only about an hour 😉

**Comment by jrast** [comment]
CI reveals everything in such situations 😉

**Comment by fschulze** [comment]
@koallen for devpi-client I'm currently investigating another issue, after which there will be a release. For devpi-server/devpi-web it might take a bit longer, as it is recommended to pin your dependencies for deployments anyway and there is nothing else requiring a release for them yet.

**Comment by bluetech** [comment]
Note, pluggy 1.1 was yanked, and 1.2 will have the offending code change reverted, so you don't need to worry about fixing this quickly.
