### ISSUE TITLE
Give obvious warning if version file is included in uploaded package

### ISSUE THREAD

**Issue by Decee1** [devpi/devpi#982]
Hello,

I have had problems where I by accident committed __version__ to my project and that caused the tag to change.
I would like there to be implemented an obvious warning if the __version__ i detected in the project. 
In our case we use scm so in the setup.py we got {'write_to': "package_name/__version__.py"},
which could be one way of detecting it. Some also prefer not calling it __version__.py and calls it version.py

**Comment by fschulze** [comment]
I have no idea how that relates to devpi. To build a package, devpi-client calls ``python -m build`` or ``python setup.py build``. I have no clue how or what would change the tag.

**Comment by Decee1** [comment]
Hello, 
I just assumed it was devpi since the version changed when it was run though devpi
My bad, I'll close it then
