### ISSUE TITLE
forgot the root password,how to reset the root password

### ISSUE THREAD

**Issue by shengkaixuan** [devpi/devpi#988]
devpi login root --password=""
POST https://pypi.flexiv.cloud/+login
401 Unauthorized: user 'root' could not be authenticated

how to reset the root password?? thank you?

**Comment by fschulze** [comment]
On the server you can set a new password with the ``devpi-passwd`` command.

**Comment by fschulze** [comment]
No follow-up for several months. If this is still an issue, feel free to re-open.
